### ISSUE TITLE
quick priority setting when swiping right on items

### ISSUE THREAD

**Issue by oneyb** [orgzly/orgzly-android#100]
Hi orgzly wizards,

orgzly rocks. I see there are a bunch of feature requests. I only allow myself to offer the following suggestion, because it may be simple and would reduce redundancy, and thus would improve the workflow with orgzly, in my opinion.

I tend to have a bunch of TODOs which I then give a priority. Maybe it would be better to go all GTD and just use NEXT. Nonetheless, unless one has a ton of possible STATES, cycling through them is quick. All one has to do is swipe right. Therefore, I suggest we only need one button to cycle between states, instead of both clockwise and counterclockwise. 

The replacement button would be to cycle between priorities. This feature would also allow quickly giving priority to other states (i.e. NEXT) actions as well.

![screengrab-1496870325661](https://user-images.githubusercontent.com/7442808/26902015-08dadcc4-4bd8-11e7-996e-1f129b9ca6aa.png)

If you don't like my idea, I think orgzly is great and am looking forward to see where you take it. Thanks anyways!
Cheers
Brian

**Comment by oneyb** [comment]
I am pretty happy with the GTD-system as it is. Gonna close this. Thanks guys!

**Comment by nevenz** [comment]
This will probably be added eventually, probably as part of horizontally scrollable bottom bar.
