### ISSUE TITLE
LOGBOOK not folded in search view

### ISSUE THREAD

**Issue by pestyleader** [orgzly/orgzly-android#1003]
I've noticed that the logbook of a note is no longer folded in searches. I believe this was introduced in the 1.8.10 update. This way, repeating items with regularly changing to-do states make for a long, unwieldy agenda. I have attached a screenshot of this problem.

I would prefer the previous approach of a folded logbook, which is still the case in the normal "note view."

![Screenshot_20221111-124854~2](https://user-images.githubusercontent.com/117988955/201335719-171a6cd7-0446-492c-988d-c8caa24be760.png)

**Comment by ghost** [comment]
Any work on this would be greatly appreciated. I unfortunately lack the ability myself. The logbook didn't show up like this until recently. This makes the search less effective as an agenda view.

**Comment by ghost** [comment]
It seems that this problem only appears when there are too many entries under LOGBOOK—deleting old entries solves this.

**Comment by quzyte** [comment]
I am having this problem in the normal note view. My note has just over 80 log entries, and recently I noticed that I am not able to close the LOGBOOK.
Is there any solution for this other than having to deleting old entries?

In view of this, I request this issue be re-opened.
