### ISSUE TITLE
Default notebook is ignored when adding notes from notification and '+' of widget

### ISSUE THREAD

**Issue by jflinchbaugh** [orgzly/orgzly-android#1006]
I have default notebook set to my 'GTD' notebook, but every time I open a new note from notification or from widget, it picks randomly between my 'GTD' list and my 'Grocery' list, so new notes often mysteriously end up in the Grocery list. Adding from widgets used to work fine, but has been misbehaving for the past few months at least.

**Comment by jflinchbaugh** [comment]
Default notebook may be working for quick note from notification, but new note and widget are adding randomly to any notebook for which I have a search and widget.

**Comment by jflinchbaugh** [comment]
if i add a widget that views a 3rd list "b.Beer" in my case, then I can get that 3rd list in the random rotation of chosen notebooks.

**Comment by nevenz** [comment]
If the selected query in the widget contains `b`, that notebook will be selected when widget's `+` is tapped. If not, the default notebook from the preference should be used.

I can't reproduce this. Does "Default notebook" value match the notebook's name exactly (note that the value of `#+TITLE` is not matched against) ? Make sure there are no extra spaces or such. ( That preference should really be a notebook selector. )

**Comment by jflinchbaugh** [comment]
Your description of how it should work sounds very intuitive, and exactly what I'd expect. :smile: 

Here's a reproduction for what I'm seeing:

I have 3 notebooks in place: GTD, Grocery, Beer, basically in that order in the Notebook List.

I usually have 3 widgets:
* Next (b.GTD i.next .o.created)
* New (i.new)
* Grocery (b.Grocery it.todo)

If I REMOVE all the widgets, I can set the Default Notebook to "GTD" or "Beer", and the "New Note" works fine from the notification shade.

If I leave the Default List as "Beer", and add the Grocery widget, then the notification and the + both show "Grocery" as the list when it opens the "New Note" screen. (Notification is using the widget's "b.Grocery", it seems.)

Once I add a second widget, my "Next" widget from above, then both the notification and the + on either widget start choosing randomly between "Grocery" and "GTD".

If I had to diagnose, I'd guess it's grabbing the first widget it finds, and that list really ordered, instead of the widget that owned the +. I've pulled code, because I think it would be fun to look, but I haven't really setup Android Studio yet.

Thanks for your time.

**Comment by nevenz** [comment]
Thanks, that was useful, I managed to reproduce it.

All pending intents for new-note (created for ongoing notification and all widgets) were the same (to Android, as only extra data was different). So notification setup and selecting queries for the widget were overwriting each other's pending intents.

It should work now with the fix (with multiple widgets too).

**Comment by jflinchbaugh** [comment]
I'm glad to see this fixed, but I don't think it was released.
