### ISSUE TITLE
Dropbox Sync failed: Unknown API function /2/files/get_metadata

### ISSUE THREAD

**Issue by kisp** [orgzly/orgzly-android#1011]
This morning, dropbox sync stopped working for me.

I am getting the error (right at the start of the sync attempt):

```
Sync failed
Failed getting the list of files in dropbox:/orgmode listing /orgmode:
Error in call to API function "files/get_metadata": Unknown API function:
/2/files/get_metadata
```

I will try on my other device when at home and then let you know.

**Comment by karlacio** [comment]
Same here!

Update: after half an hour the problem seems to have resolved. Dropbox fault?

**Comment by anoduck** [comment]
Interesting ... I tested out the script I wrote [org-orgzly](https://github.com/anoduck/org-orgzly), and orgzly sync. Both worked without a hitch. More than likely someone at dropbox is tinkering.

**Comment by nevenz** [comment]
Yeah, it seems to be something on their side: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Getting-Unknown-API-function-2-files-get-metadata/m-p/638959/highlight/true

**Comment by kisp** [comment]
For me, everything is now also back to normal.
