### ISSUE TITLE
Can not find dropbox option

### ISSUE THREAD

**Issue by azzamsa** [orgzly/orgzly-android#104]
I installed new version of orgzly from F-Droid, but in setting > adding repo, I just have directory option. I cant find Dropbox option

**Comment by azzamsa** [comment]
but The solution for me is, I use https://syncthing.net. and this works really great.

I really love this orgzly, thanks lot for making this app.
I hope I can give my support.

**Comment by MackieLoeffel** [comment]
The problem is, that F-Droid allows only open source packages, but the dropbox sdk is not open source. This means, that there are two flavors of orgzly: one with dropbox support, which is distributed through the google playstore and one without dropbox support for F-Droid.

**Comment by azzamsa** [comment]
Yes, before I want to try that. I want to remove my orgzly from F-Droid and try to install from Playstore. but I also don't like Dropbox to much. Hope can set up owncloud in following days.

@MackieLoeffel is installed orgzly from Playstore works well with sync from dropbox?

**Comment by MackieLoeffel** [comment]
Yes, the dropbox synchronisation in the playstore version works well.

**Comment by azzamsa** [comment]
okay, thanks lot.

and thanks for your contribution to orgzly. thanks lot.

**Comment by stormwatch** [comment]
Hi.Could you please add a paragraph to the release notes and FAQ describing the problem? Maybe it is already there and I skimmed. Instructions on how to set syncthing up would be a plus. Thank you both

**Comment by nevenz** [comment]
> Could you please add a paragraph to the release notes and FAQ describing the problem? Maybe it is already there and I skimmed.

It's not, it should be added, this has been asked few times before.

> Instructions on how to set syncthing up would be a plus. Thank you both

I don't use it, so pull requests welcome (https://github.com/orgzly/documentation).
