### ISSUE TITLE
orgzly donation

### ISSUE THREAD

**Issue by azzamsa** [orgzly/orgzly-android#110]
is orgzly does not accept monetary donation ?

**Comment by nevenz** [comment]
No, there will probably be in-app payments on Google Play in the future. Thanks though. :)

**Comment by azzamsa** [comment]
alright, thank you so much for this great application.

**Comment by kxpvcr** [comment]
I know this is closed, but even a Patreon/Flattr/Liberapay/etc. would be nice to have, right? I **really** like the app, it's very well made, but don't use the Play Store.

**Comment by tekstrong** [comment]
I too would love to donate towards Orgzly via Patreon (or the like).

**Comment by karlicoss** [comment]
@nevenz perhaps if you don't need donations at the moment, you could list some developers you'd like to support so people could send money to them? Org-mode developers are perhaps the obvious choice, but maybe you've got your own idea :)

**Comment by nevenz** [comment]
@karlicoss, I could create a list of people who want to be included in it with their link(s) for donating and contribution (which can be just a link like https://github.com/orgzly/orgzly-android/commits?author=nevenz).

**Comment by vjjaimez** [comment]
Yes, please. An alternative to the Play store would be very much appreciated. I don't use the Play store either, but I would like to contribute financially to the development of this app.
