### ISSUE TITLE
Bring the keyboard up when adding a node

### ISSUE THREAD

**Issue by mardukbp** [orgzly/orgzly-android#115]
This is a small nuisance and hopefully it is easy to fix. Every time I add a node I see the cursor blinking in the Title field, but I have to tap on the field in order to bring the keyboard up.

Version: 1.4.13.

**Comment by nevenz** [comment]
On which device are you seeing this? (This is explicitly done already.)

**Comment by mardukbp** [comment]
On an LG G4 with Android 6.0
