### ISSUE TITLE
Note count per notebook

### ISSUE THREAD

**Issue by fresheed** [orgzly/orgzly-android#117]
As discussed in #112, requested features should be implemented one by one so here I would like to clarify note count. 

- Where do you think it should be put - to widget and/or note view? As for me, counter at widget is most needed one. 
- Is corresponding setting needed for that or it should always be displayed?

**Comment by nevenz** [comment]
Are you referring to #62 widget or something else?

I though it would be a count next to a notebook - in the list of notebooks and/or drawer. I don't think there needs to be a setting for that.
