### ISSUE TITLE
Timeline or Roadmap?

### ISSUE THREAD

**Issue by keithcrone** [orgzly/orgzly-android#118]
Just curious if you had a roadmap anywhere of what you planned on working on next or if there was a schedule for releases.

**Comment by nevenz** [comment]
No, I can start using milestones here on GitHub?

**Comment by keithcrone** [comment]
Whatever is good for you.

I'm really starting to use this to manage much of a small business I run. The final piece for me (after notifications) is going to be internal note linking. Naturally though, that doesn't make that anyone else's priority, so I'm only trying to do some planning. If (as a guess) it might only be a few months before something like that is implemented, then I'll wait. If it's going to be way longer, then I'll work on trying it myself

**Comment by keithcrone** [comment]
Or contracting someone to do it for me. But either way, I'm just trying to gauge for myself what is happening.

Thanks.

**Comment by nevenz** [comment]
I've created https://github.com/orgzly/orgzly-android/milestone/1 for now.
