### ISSUE TITLE
http library in webDAV

### ISSUE THREAD

**Issue by rafaelleru** [orgzly/orgzly-android#119]
Hy im finishing the webDAV support but after update to android O in my nexus 6P I get the following error:

```
FATAL EXCEPTION: main
                                 Process: com.orgzly, PID: 14297
                                 java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/client/protocol/HttpClientContext;
                                 at com.github.sardine.impl.SardineImpl.<init>(SardineImpl.java:163)
```
I try to add   ```useLibrary 'org.apache.http.legacy``` to the gradle file but it doesn't work.
and I can't figure out how to fix it. any suggestion? 

PD: I'm using sardine for the webDAV stuff.

**Comment by nevenz** [comment]
How can this be reproduced? Which code and actions?

**Comment by rafaelleru** [comment]
oh sorry, you need to pull my fork, run it on a phone (I'm using android O preview), go to settings and try to add a new repository.

**Comment by rafaelleru** [comment]
I'm sure that the problem comes from sardine library. But I can't find other webDAV implementation for use it in android.

**Comment by nevenz** [comment]
So whatever is using Apache's client seems to have an issue it seems. Dropbox SDK moved away from it for example (dropbox/dropbox-sdk-java#26).

Do we even need a library? Seems mobileorg is not using it for example? Have you checked that code?

**Comment by rafaelleru** [comment]
Ok I will look the mobileorg app and try to make it work. I started with sardine for simplicity but I will find another solution. Thanks @nevenz

**Comment by nevenz** [comment]
Let's keep these discussions contained in one relevant PR or issue.
