### ISSUE TITLE
Preservation of content indentation

### ISSUE THREAD

**Issue by chrisberkhout** [orgzly/orgzly-android#12]
This is not about the expected whitespace changes [mentioned in the documentation](http://www.orgzly.com/help#orga863f57).

I've noticed that content inside `#+BEGIN_EXAMPLE` and `#+BEGIN_SRC` blocks gets rewritten with no indentation. The first non-whitespace character of every line is aligned directly below the tag.

**Comment by nevenz** [comment]
Can you post a small sample org file, I can't reproduce it.

Note content should be written as it is, without any modifications.

**Comment by chrisberkhout** [comment]
Sorry! False alarm.

I've mostly been using Orgzly, but now I realize that [SyncOrg was the source of this problem](https://github.com/wizmer/syncorg/issues/47).

The changes made by Orgzly are indeed only the expected whitespace changes, as confirmed by the following example.

Before edit:
```org
* Top
** First
Content unindented
  Indented 2
    Indented 4
** Second
   Content indented
     Indented 2 more
       Indented 4 more
** Third
#+BEGIN_EXAMPLE
=============================
Example unindented
  Indented 2
    Indented 4
=============================
#+END_EXAMPLE
** Fourth
  #+BEGIN_EXAMPLE
  =============================
  Example indented
    Indented 2 more
      Indented 4 more
  =============================
  #+END_EXAMPLE
```
After inserting heading `New above first`:
```org
* Top
** New above first
** First

Content unindented
  Indented 2
    Indented 4

** Second

   Content indented
     Indented 2 more
       Indented 4 more

** Third

#+BEGIN_EXAMPLE
=============================
Example unindented
  Indented 2
    Indented 4
=============================
#+END_EXAMPLE

** Fourth

  #+BEGIN_EXAMPLE
  =============================
  Example indented
    Indented 2 more
      Indented 4 more
  =============================
  #+END_EXAMPLE

```
Diff:
```diff
1a2
> ** New above first
2a4
> 
5a8
> 
6a10
> 
9a14
> 
10a16
> 
17a24
> 
18a26
> 
25a34
> 
```

**Comment by nevenz** [comment]
Note you can also control addition of those extra new-lines in

`Settings -> Org file format -> Separate notes with an empty line`

**Comment by chrisberkhout** [comment]
Thanks!

**Comment by tsuflux** [comment]
@nevenz What is the intended behavior of `Separate notes with an empty line`?

Currently, if I have set it to `Never`, Orgzly will insert a blank line between the heading and content. If it is set to `Multiline notes only`, Orgzly additionally inserts a blank line after the content of a note. And if set to `Always`, Orgzly inserts a blank line after every heading regardless if there is a note attached to it.

**Comment by chrisberkhout** [comment]
> Currently, if I have set it to Never, Orgzly will insert a blank line between the heading and content.

I noticed that too, for items with content.

**Comment by nevenz** [comment]
Yes, that option is only for new-lines between notes and note here is defined as heading+content.

New-line between heading and content is always added. Content here is text below heading, and it does not include planning times, PROPERTIES etc. Those are always glued to heading.

I guess a new option to control that space too is required? Like "Separate content from heading" or such. Shoot an issue if you'd find it useful.
