### ISSUE TITLE
Chinese characters disappear

### ISSUE THREAD

**Issue by geokon-gh** [orgzly/orgzly-android#121]
Maybe it;s an issue with some configuration on my end, but my Chinese character disappear semi-randomly when sync'ing. This works both way, if I input on my phone and sync to my computer or when I input chinese on my computer and sync to my phone. Occasionally it works, but often the characters are replaced either with blanks or some weird symbols. My guess it's some encoding issue?

**Comment by nevenz** [comment]
Which syncing method are you using (Dropbox or Directory) ?

Probably related to #30.

**Comment by geokon-gh** [comment]
Directory with Syncthing :)

**Comment by cnshijin** [comment]
Chinese character disappear when syncing to directory, but it's fine when exporting to directory.

**Comment by nevenz** [comment]
> Chinese character disappear when syncing to directory, but it's fine when exporting to directory.

Do you see missing characters in the file on the actual device (the one in the synced directory)? Or further downstream (where Syncthing is syncing to, if you're using it too)?

Also, are _all_ characters gone?

And if you enable `Settings -> (Notebooks) Details -> Detected/Used encoding`, what's displayed in the list of notebooks for the notebook that has issues? Does it have a "<encoding> detected/used" lines? And is so, which encoding is that?

Thanks!

**Comment by cnshijin** [comment]
> Also, are all characters gone?

No, the english character was fine. The detected encoding is `GB18030 used`.

Thank you for your replying.

**Comment by cnshijin** [comment]
> Do you see missing characters in the file on the actual device (the one in the synced directory)?

The file in the sync directory is wrong. But the note in orgzly app is right, and it can export the note correctly to directory.

**Comment by nevenz** [comment]
> The file in the sync directory is wrong. But the note in orgzly app is right, and it can export the note correctly to directory.

Can you try the latest `v1.5-beta.4` - if exporting notebook works fine, syncing to directory repo should too now.

**Comment by cnshijin** [comment]
> Can you try the latest v1.5-beta.4 - if exporting notebook works fine, syncing to directory repo should too now.

I tried exporting and syncing, orgzly worked fine. Thank you for your greate app.

**Comment by nevenz** [comment]
Great, thanks.
