### ISSUE TITLE
i.note search (or some way to include/exclude items w/o TODO/DONE status)

### ISSUE THREAD

**Issue by claiire** [orgzly/orgzly-android#128]
It would be useful to have a way to explicitly include/exclude notes (as in, items without TODO/NEXT/DONE/ETC.) in searches.

**Comment by nevenz** [comment]
We'll probably want a new search operator for state classes/types. `ic` has been [suggested](https://github.com/orgzly/documentation/blob/master/searching-proposal.org), though more readable one might be better. Anyway, something like:

- `ic.todo` - any TODO-type state
- `ic.done` - any DONE-type state
- `ic.note` - no state. Perhaps `ic.none` would be better, to be consistent with current `s.none`

**Comment by nevenz** [comment]
Implementing this for agenda, which currently has `.i.done` hardcoded.

**Comment by nevenz** [comment]
`it` for "is type" has been supported. You can do:

- it.todo
- it.done
- it.none
- .it.todo
- .it.done
- .it.none

**Comment by keithcrone** [comment]
Not a particular state, just that it has a state? it.todo and it.next will yield the same results?

**Comment by nevenz** [comment]
> Not a particular state, just that it has a state? it.todo and it.next will yield the same results?

There's no `it.next`, those are literal `todo`, `done` and `none`.

For example, if you use `TODO NEXT WAIT | DONE CNCL`, then `it.todo` is equivalent of `(i.todo or i.next or i.wait)`. See my first comment, I just used `it` instead of `ic`.
