### ISSUE TITLE
Cannot search for tag value like "Q1"

### ISSUE THREAD

**Issue by hajimezhao** [orgzly/orgzly-android#130]
HI orgzly author,
I just installed orgzly and like it. One issue: I have org-mode entries with tag like "Q1", "Q2". By using search query "t.q1" or "t.Q1", it leads to no result. Could you please help investigate it? Thank you so much!

Have a nice day,
Cheers,
Khon

**Comment by nevenz** [comment]
Can you post a screenshot or exported Org file (perhaps a sample). Anything that can help, since this is a pretty basic feature which should be working. Thanks!

**Comment by hajimezhao** [comment]
Sorry. Maybe my mistake. Today, I can see the filter result.  : D
I close this issue.
