### ISSUE TITLE
Import "Getting Started With Orgzly - Beta Version"

### ISSUE THREAD

**Issue by malcolm-mill** [orgzly/orgzly-android#133]
Would be nice to have up to date documentation on Beta features and a quick way to import the notebook. I'm happy to help write the documentation.

**Comment by nevenz** [comment]
That notebook is more a sample for the app, then real documentation. It's there to look good and allow user to umm... get started. I guess it could use a refresh though by mentioning few latest v1.5 features. It can be found here: https://github.com/orgzly/documentation/blob/master/android/getting-started.org

The closest thing to "real documentation" would be http://www.orgzly.com/help (https://github.com/orgzly/documentation/blob/master/miscellaneous.org).

Thanks!
