### ISSUE TITLE
Notebook widget points to app background state

### ISSUE THREAD

**Issue by malcolm-mill** [orgzly/orgzly-android#134]
Notebook widget links are opening the app at its current background state. They aren't going to the appropriate notebook. The links work after the app has been cleared from RAM but if there's an intermediate change in view page state they'll point to that.

**Comment by nevenz** [comment]
Hmm I can't seem to reproduce this. Can you give the exact steps? Thanks!

**Comment by malcolm-mill** [comment]
Will do.

**Comment by malcolm-mill** [comment]
Make widget-links to two notebooks. Open one. Push it to the background using the home button. Open the widget-link to the other notebook. It should still be on the original notebook. Also, if you've gone somewhere else in the app in between it'll be stuck on that. The only way to make it behave is to use the back button to get out of the notebook back through the notebooks menu to the phone's "desktop". 

This is what's happening on my Huawei P9 Lite Android 6.0, 3.10.90 kernel.

**Comment by nevenz** [comment]
Got it, thanks, can reproduce it.
