### ISSUE TITLE
insert new note at beginning of notebook

### ISSUE THREAD

**Issue by swhalemwo** [orgzly/orgzly-android#140]
I'm transitioning from Google Keep, where new notes appear at the top. I often make notes spontaneously, of which some then turn out to be irrelevant, so i don't really bother with cleaning them. In Keep that's no problem because they just slowly "sink" to the bottom as I add new ones, but in orgzly these irrelevant notes fill up the front place of my notebooks. Is it possible to add an option to Orgzly that creates a new note at the top? cheers!

**Comment by lottanbettan** [comment]
+1

I'm also transitioning from another app where this "new note at the top" feature is default - which seems reasonable, since "at the top" is where the user is finding herself when entering a notebook.

What do you think about this nevenz? Will this be implemented in the future?

Love the app, thanks!

**Comment by nevenz** [comment]
> What do you think about this nevenz? Will this be implemented in the future?

Sure, if someone wants to take a shot, it's a matter of adding a new preference under "New note" in Settings and handling `Place.UNSPECIFIED` in `Provider#insertNote` in two places.

I'd eventually get around to it, it's in a long queue of features. Thanks.

**Comment by epchain** [comment]
"Prepend" is a very nice feature, but it doesn't work with "Refile note". Note is put at the bottom when moved to another notepad. If it makes sense, please make "Prepend" preference affect "Refile note".
