### ISSUE TITLE
sync repositories at load and unload

### ISSUE THREAD

**Issue by malcolm-mill** [orgzly/orgzly-android#141]
I keep my org files in dropbox. I use emacs on several different laptops to edit org files. Dropbox on the laptops syncs as soon as the files are touched. Using Orgzly I have to remember to sync when I start and when I finish to avoid conflict. Is automating that sync schedule a feature worth working on? Maybe something to build in to settings?

**Comment by nevenz** [comment]
Yes there's #8. Also #136 which I have yet to check.
