### ISSUE TITLE
Display images

### ISSUE THREAD

**Issue by crocefisso** [orgzly/orgzly-android#147]
In my Orgzly folder, I created a Pic folder to store pictures that I'd like to display for some todos. In order to display picture P on some note, I input [[./Pic/P.jpg]] and [[./Pic/P.jpg][Picture P] in my note but neither make displaying available. Adding this feature would be useful.

**Comment by ookimi** [comment]
This would indeed be great. I'm using org-mode with the org-drill for study notes, and pictures are often needed. In combination with the timestamps and tags, pictures in orgzly would make reviewing a breeze.

**Comment by mrDSide** [comment]
Maybe would be nice to have feature like in desktop version for categories?
https://julien.danjou.info/icon-category-support-in-org-mode/

**Comment by vzaliva** [comment]
One more vote for pictures. I often take pictures of whiteboards during my meeting and refer to them in the notes. Currently, I keep them in the same Dropbox folder as my org-mode meeting minutes and emacs shows them just fine. It would be nice for orgzly to show them as well.

**Comment by Ypot** [comment]
That would be superb. We could take notes fast using even photos.

**Comment by nevenz** [comment]
Was done in #389.
