### ISSUE TITLE
Put move commands at topbar

### ISSUE THREAD

**Issue by danielo515** [orgzly/orgzly-android#151]
Hello,

When you select a node, you have to go to the more options button ,then select move and then move the node. Too many finger movements for my taste. I think it will be better if you put the move commands directly on the topbar when a node is selected. There is plenty of space . Or at least provide an option to select this layout.

Here is an screenshot showing how much space is wasted in my phone 

![screenshot_2017-08-15-15-51-50](https://user-images.githubusercontent.com/2270425/29400885-44d9fc76-832f-11e7-9e59-600f99e0d66c.png)

**Comment by nevenz** [comment]
"Cut" and "Paste" have been moved from the action overflow (if there is room) in #113. There wouldn't be space to display more items, per [android rules](https://developer.android.com/design/patterns/actionbar.html), unless the display is forced, which I don't think is a good idea. Even "Cut" and "Paste" probably won't be displayed when expected, as that space is pretty limited (not larger then 50% of action bar).

I think it's time for implementing the *bottom* action bar.

"Quick menu" (the one opened when note is swiped) should be reconsidered then though, as we'd end up with too many confusing menus all over the place.

**Comment by danielo515** [comment]
Hello @nevenz 
Sorry, but I don't understand what do you mean with 
> have been moved from the action overflow (if there is room) in #113

What is exactly action overflow ? Where were them before?
Why do you see that would't be space to display more? have seen my screenshot? there is room for at least 4 buttons (on my screen). Is not possible to fill the entire bar with buttons and move them to the "extra" menu when there is no more space ? I'm coming from HTML world, and this is quite common, so sorry if this makes no sense on android.

The bottom bar sounds very interesting. Also, if you make the swipe menu configurable it will be a killer feature. I have to admit that sometimes is hard to remember that there is a menu hidden there, but is quite useful when you get used to it.

Regards

**Comment by nevenz** [comment]
Action overflow is what you called "more options button".  Icon with 3 dots.

> Is not possible to fill the entire bar with buttons and move them to the "extra" menu when there is no more space ?

This is done now for most buttons, but it's Android who's deciding if there is space to display them or not. And it's very stingy - from the page I linked:

> Action buttons in the main action bar may not occupy more than 50% of the bar's width. Action buttons on bottom action bars can use the entire width

So I think we should just implement the bottom action bar instead. It shouldn't be too much work, I'll take a look.

**Comment by danielo515** [comment]
Hello again @nevenz
Thanks for your patience and explanations. What you said makes total sense. I'll wait until next release 
I just subscribed to the beta program of your app

**Comment by nevenz** [comment]
I've moved "New note" and "Edit" under overflow instead. New note can be created faster using swipe-menu and actions under "Edit" are directly under overflow, so they are still 2 clicks away.

**Comment by danielo515** [comment]
Nice ! When is the release expected ?

**Comment by nevenz** [comment]
> Nice ! When is the release expected ?

Should be in a week or so.
