### ISSUE TITLE
Add option to runtime toggle (or switch off permanently) the "Screen Brightness Lock"

### ISSUE THREAD

**Issue by mjf** [orgzly/orgzly-android#162]
Hello.

I think an ability to toggle the *Android*'s "Screen Brightness Lock" *on* and *off* would be **very handy**!

Sometimes user would like to stare at her note for a long time and it's really annoying to keep touching the device again and again to keep the screen *on* (i.e. you lay your device on the desk and want to go through some longer note or notebook and write something on your PC at the same time).

If it can't be implemented as runtime toggle option accesible from (for example) menu anytime for some reason then provide at least global *Settings* option for it (as it is implemented i.e. in the *Acrobat Reader*).

**Comment by nevenz** [comment]
> Would an option in the top-right "more" menu work?

Sure, I think it makes more sense to be there, above `Sync`.

Would a dialog with the are-you-sure prompt (explaining what the option does) before it's enabled (after clicking the menu button) be too annoying? I'm worried it would be easy to click it by accident.

> If you don't mind, I could try to implement this feature.

Thanks!

**Comment by oujunhao** [comment]
The are-you-sure prompt seems like a valid solution, maybe I'll try putting that in. We could always change it if people think it's too annoying.
