### ISSUE TITLE
Task and timestamp on same line

### ISSUE THREAD

**Issue by pxsalehi** [orgzly/orgzly-android#164]
If task and timestamp are on the same line, the timestamp does not get processed. In Emacs, however, it works. I have some short task titles which I prefer to have the timestamp on the same line. But in Orgzly they only appear as the title name. E.g.

`* TODO weekly task SCHEDULED: <2007-05-16 Wed +1w>`

**Comment by nevenz** [comment]
That's #76, those are not scheduled in Org mode (i.e. you could drop "SCHEDULED: ").

Reopen if you see a different behaviour.

**Comment by pxsalehi** [comment]
In Emacs Org mode, if I have a task like the example above, it will show up in the agenda as scheduled. like this:

![screenshot from 2017-08-30 17-18-15](https://user-images.githubusercontent.com/3340727/29880153-5952e5a0-8da7-11e7-913c-fd3f172d5a52.png)

**Comment by pxsalehi** [comment]
I think it is different than #76 since I am only talking about already supported timestamps but located on the same line as the task rather than on a new line.

**Comment by nevenz** [comment]
> I think it is different than #76 since I am only talking about already supported timestamps but located on the same line as the task rather than on a new line.

If it should be a scheduled task, I agree. I'd consider it a bug even.

I'm not seeing the same though - what Org mode version is that?

**Comment by pxsalehi** [comment]
8.2.10

**Comment by nevenz** [comment]
> 8.2.10

Ah OK, so it got changed, looks like in 9.0. You wouldn't be seeing it as a scheduled time, if you upgrade.

If it were a straightforward implementation, I wouldn't mind supporting this, there probably wouldn't be any harm.

Parsing wouldn't be a problem, but generating the same org file would be tricky. We'd have to flag a note that it wants a scheduled time in the title, or keep it there and update it on every UI change etc.
