### ISSUE TITLE
Completing recurring dodo with ++ and later hour behaves like .+

### ISSUE THREAD

**Issue by sanosis** [orgzly/orgzly-android#171]
Completing a recurring TODO with ++ and an later hour bumps the date to the next occurrence instead of today.

Example:
Task  yesterday 19:00 ++1d
completed at 8.00 will change the task date to tomorrow 19:00 ++1d instead of today 19:00

**Comment by nevenz** [comment]
I can't reproduce this, it works for me as you wrote it should.

Can you give another example, or perhaps a screenshot? Thanks!

**Comment by sanosis** [comment]
In 1.5.2-beta.2 it works as expected
