### ISSUE TITLE
Support text formatting escaping

### ISSUE THREAD

**Issue by mjf** [orgzly/orgzly-android#178]
Sometimes you need to write things like "foo/bar/baz" (resulting in "foo*bar*baz" now). Please, provide escaping for "foo\\/bar\\/baz" (resulting in "foo\\*bar*\\baz" now) to produce the expectable "foo/bar/baz".

**Comment by nevenz** [comment]
Are we fine with dropping support for formatting in the middle of the word? (Org mode doesn't do that anyway).

/this/is/a/directory seems like something used quite a bit.

**Comment by nevenz** [comment]
> Org mode doesn't do that anyway

Hmm, this is not true for /foo/bar/baz/ though. I'll see to make it work as in Org mode for now.

**Comment by tulth** [comment]
I have issues with it messing up stored pathames too.   This does not happen in emacs in most cases.  I totally agree with matching emacs behavior.

**Comment by mjf** [comment]
Also, the text formatting syntax and **precise** behaviour should be defined in the documentation, I think.

**Comment by nevenz** [comment]
It should work like in Org mode now. Thanks for testing these out.
