### ISSUE TITLE
Allow child notes to inherit parent's deadlines and scheduled dates?

### ISSUE THREAD

**Issue by JayAvery** [orgzly/orgzly-android#179]
Disclaimer: I'm not familiar with org-mode outside of orgzly, which I've only been using for a couple of days.

Would it be possible to allow child notes to inherit the scheduled and deadline dates/times from their parent? There could be a setting to do or not do this by default when creating new child notes. As an example of when I'd want to use this: I have a notebook where I track various things by date. So each day has a single parent note which is 'scheduled' for the day it refers to. Each day then might have several child notes with different tags (say a note for each meal tagged with 'food'). I'd like to be able to search for just notes tagged with 'food', but have those notes display the scheduled date of their parent. So that they are organised by date in the search, without having to manually add the same date to every child note.

Is this possible/planned/unachievable?

**Comment by nevenz** [comment]
It's possible, but kinda specific - would support for copying notes work for you instead (#47)?

Also, as a workaround, you could add a tag to the parent note (`2017-09-17` or similar), which (if setting is enabled) will be displayed in search results for all sub-notes. Not ideal of course, as it's more work and duplicated info.

**Comment by JayAvery** [comment]
Copying would be pretty good. I feel like inheriting dates is a natural progression from inheriting tags, but I understand if it's not a priority!

**Comment by nevenz** [comment]
> I feel like inheriting dates is a natural progression from inheriting tags, but I understand if it's not a priority!

I think the main issue (apart from not being trivial to implement) is where to draw the line. As pretty much everything could be inherited (properties, priorities, state, even content as a template). Which then ends up being copy. :) Tags are inherited as it's a commonly used feature in Org mode.

**Comment by JayAvery** [comment]
I understand! I'll just familiarise myself with copying. :)

**Comment by nevenz** [comment]
Cool. :)
