### ISSUE TITLE
Implementation of Ledger

### ISSUE THREAD

**Issue by XeVile** [orgzly/orgzly-android#183]
I don't think there is an implementation of Ledger. I know it's still early in development, but do you plan on implementing it? Is it even possible?

Would be a huge help for people, especially students who rely on org mode for everything.

**Comment by delexi** [comment]
What exactly do you mean by "ledger"? Could you give a short example org file?

**Comment by XeVile** [comment]
Sadly, I am away from home at the moment and don't have an example file at the moment.

Though, [this link](http://orgmode.org/worg/org-contrib/babel/languages/ob-doc-ledger.html) would probably provide a much better explanation.

**Comment by nevenz** [comment]
This requires ledger program installed, which is used through Babel in Org mode, no?

I don't think it's even available on Android, and it's whole other problem how to do something similar to Babel.

**Comment by XeVile** [comment]
Yes you are correct. There seems to be no implementation of ledger using babel for Android. 

It seems this a pretty stupid feature request from my part.

I guess using customised states would be another extremely simplified alternative.

**Comment by nevenz** [comment]
Hmm it's actually kinda interesting to think about the possibility of making parts of the content dynamic, babel-like, using various *web services* to do the job.

You'd click on the area, confirm you trust whatever is about to happen, request would fire in the background and content would get updated.

You could even setup a [ledger service](https://github.com/slashdotdash/node-ledger-rest) for this.

There's a ton of things you could do probably, using various APIs. Could be a neat feature.

**Comment by XeVile** [comment]
Wouldn't that possibly slow down the application? 

Though a making the application content dynamic could open the application to a lot more usage. Currently I use it to log my guitar practice. Each time I have to import and export to carry over common notes.

If I understand your idea correctly, i could make a practice schedule instead and automate it to make a schedule everyday carrying over properties of last schedule.

Again, if something like Tasker support is implemented, the same can probably be done, albeit with more effort.

**Comment by nevenz** [comment]
> Wouldn't that possibly slow down the application?

Nothing would happen automatically, you'd click and wait.

It would be very similar to babel in Org mode, but a web-service would be used instead.

Anyway, just throwing the idea, it's probably out of scope for this app.

**Comment by nevenz** [comment]
Going to close this for now.
