### ISSUE TITLE
Org mode's definition of 'Scheduled' is considered

### ISSUE THREAD

**Issue by wiredone** [orgzly/orgzly-android#185]
In Orgzly one can see 'Scheduled time' asan attribute of an item, as per the common understanding of 'schedule'.  However in Org mode itself it apparently works slightly differently and it perhaps worth considering.

"Important: Scheduling an item in Org mode should not be understood in the same way that we understand scheduling a meeting. Setting a date for a meeting is just a simple appointment, you should mark this entry with a simple plain timestamp, to get this item shown on the date where it applies. This is a frequent misunderstanding by Org users. In Org mode, scheduling means setting a date when you want to start working on an action item."
http://orgmode.org/manual/Deadlines-and-scheduling.html#Deadlines-and-scheduling

**Comment by nevenz** [comment]
What *behaviour* in the app related to scheduled times are you referring to?

BTW, support for plain timestamps is planned (#76).

**Comment by wiredone** [comment]
I imagine that to have congruent behaviour with Org-Mode then one would have a 'Scheduled date' (for starting a task) rather than 'Scheduled time', *as well* as the ability to create time specific timestamps for appointments.  (However I imagine that this may be tricky if syncing due to cal-dav limitations.)

**Comment by nevenz** [comment]
You can have a scheduled date too - time part is optional and not used by default. And Org mode can also have both types.

I'm not yet familiar with cal-dav, so I'm not sure which limitations are that.

**Comment by wiredone** [comment]
I didn't try specifying a schedule to an item without a time since I assumed that 'Scheduled time' necessitated a time. : )  In that case a small change in UI wording would make it obvious and congruent.

**Comment by delexi** [comment]
What would you change the wording to?

**Comment by davidpiano** [comment]
Org mode uses "scheduled" to mean "this is when I plan to do some work on Task X".

Org mode does *not* use the word "scheduled" for meetings or appointments or deadlines.

That's the difference.

**Comment by tumashu** [comment]
```
Important: Scheduling an item in Org mode should not be understood in the
same way that we understand scheduling a meeting. Setting a date for a meet
ing is just a simple appointment, you should mark this entry with a simple
plain timestamp, to get this item shown on the date where it applies. This
is a frequent misunderstanding by Org users. In Org mode, scheduling means
setting a date when you want to start working on an action item.
```

**Comment by davidpiano** [comment]
Therefore, I might like to change Orgzly's wording "scheduled time" in those cases to something like "event time" - or perhaps simply "time" if that isn't too ambiguous.

**Comment by tumashu** [comment]
What about add a custom format, for example:

* This is a appointment
APPOINTMENT: <2017-01-01>

**Comment by davidpiano** [comment]
Yes, perhaps including a specific time or perhaps not - but the point is that "scheduled" is for starting your own work actions, and not for meetings or appointments or deadlines.

Think of it this way: a deadline is when you must finish your work; scheduled is when you mean to start that work.

A deadline is a day, and maybe also a time.

Similarly, scheduled is a day, and maybe also a time.

**Comment by tumashu** [comment]
In my opinion, the most different is that time notification method.

**Comment by davidpiano** [comment]
Why have a custom appointment format? Appointments don't need any format, they just need a time stamp and that's all.

**Comment by tumashu** [comment]
```
Why have a custom appointment format? Appointments don't need any format, they just need a time stamp and that's all.
```
For org-mode, this may very simple, because it is build on a editor,  but for orgzily, a simple appointment  format may easy coding and write, it just my thought :-)

**Comment by tumashu** [comment]
But, iff we can full support plain timestamp, It will so great :-)

**Comment by wiredone** [comment]
Thank you both for your comments on this.  I hope it is not 'bike shed'.

On 27/10/17 07:42, davidpiano wrote:
>
> A deadline is a day, and maybe also a time.
>
> Similarly, scheduled is a day, and maybe also a time.
>
I find this an illuminating and useful definition. 

Perhaps it deviates from an org-mode ' philosophy', as documented (since
a scheduled item should not have a time).  Not scheduling a time is
perhaps a strange/novel idea, which may not be obvious to new users
seeking to learn to manage their tasks with orgzly/org-mode.   Perhaps
there might be some breadcrumb in docs or indication in the UI to alert
them to this?  It was not obvious to me that it was not necessary to
schedule a time along with the date.

**Comment by f1rstperson** [comment]
May i revive this thread?
This is pretty much the only really annoying thing about orgzly to me, since i now have to choose between either gimping my desktop-experience or the mobile one. Would this be possible to implement in the parser and the ui?

An appointment would look like this:
* Some appointment heading
<2022-03-02 Wed>
Body of note

**Comment by nevenz** [comment]
I'll close this one as we have #76.
