### ISSUE TITLE
Notebook names are being reset (widget)

### ISSUE THREAD

**Issue by keithcrone** [orgzly/orgzly-android#187]
If you link directly to specific notebooks on the home screen from the widget, the notebook names are being reset to 'Orgzly' after every update. 

I'll add that I'm not using a stock launcher, in case this isn't a very common problem.

**Comment by nevenz** [comment]
Can't reproduce it, which launcher is that?

**Comment by keithcrone** [comment]
Nova (Prime)
I've only linked to specific notebooks over the last few weeks so I don't know when it really started.

**Comment by nevenz** [comment]
> Nova (Prime)

Yeah, I can reproduce it, I'll take a look, thanks.
