### ISSUE TITLE
Custom filter for org files

### ISSUE THREAD

**Issue by IvanMalison** [orgzly/orgzly-android#188]
I have a massive repository of org files in the git repository I use to store the ones I would like in orgzly, but I don't necessarily want all of those org files to appear in orgzly. There should be a way to specify which org files should be synchornized.

**Comment by keithcrone** [comment]
Would it be hard to create a folder structure in Orgzly? Rather than a single list of org files have a folder for Business files or Journal or anything with an Archive tag is sorted into an Archive folder?

**Comment by IvanMalison** [comment]
> Would it be hard to create a folder structure in Orgzly? Rather than a single list of org files have a folder for Business files or Journal or anything with an Archive tag is sorted into an Archive folder?

Having looked at the code, I would say that it would be a non trivial amount of work

**Comment by keithcrone** [comment]
I had originally put in a request for internal linking to kinda combat this (with CUSTOM_ID but [[link]] & <<target>> would probably be easier). I have a number of really large documents that I navigate through with some internal links. Since they don't work in Orgzly, I started to break them up into a number of smaller files. But now I have a large number of files on the main Orgzly screen that are a headache to navigate through.

**Comment by nevenz** [comment]
There's #92.

You can open a new issue for folder-like structure (which will be required for recursive sync one day for example).

**Comment by timoc** [comment]
If you are using git to manage these files, then you can create a mobile branch that just contains the files you want (a branch tracking the master obviously), then check the mobile branch out somewhere and sync from it (be sure to pull/fast forward from master!)
If you have mobile changes you can easily identify them, and merge them back into master.

**Comment by IvanMalison** [comment]
@nevenz I actually sort of added support for this in #173 . We look for a file called .orgzlyignore and use gitignore parsing to ignore patterns specified in that file.
