### ISSUE TITLE
I think syncthing is a very good tool for orgzly

### ISSUE THREAD

**Issue by tumashu** [orgzly/orgzly-android#193]
https://syncthing.net/
```
Syncthing replaces proprietary sync and cloud services with something open, trustworthy and 
decentralized. Your data is your data alone and you deserve to choose where it is stored, 
if it is shared with some third party and how it's transmitted over the Internet.
```

**Comment by licaon-kter** [comment]
/close this

You can already use syncthing with the orgzly folder.

**Comment by tumashu** [comment]
What about add a tip in documents?

**Comment by nevenz** [comment]
There's #94 already, so closing this one as a duplicate.

You can open an issue or PR for documentation in https://github.com/orgzly/documentation, thanks!
