### ISSUE TITLE
Handling of Unicode Characters Broken

### ISSUE THREAD

**Issue by haimivan** [orgzly/orgzly-android#195]
Hi,

I edit my orgzly notes on a Android 6 smarphone (Sony Xperia Z2) and on a Ubuntu 14.04 system with Atom.

Since the last update:
Detected behaviour:
I save the text "ließen" in the Android app in the contents field. 
It appears on my Ubuntu 14.04 this way:
6C 69 65 EF BF BD 65 6E

Remark: When I save this text with the atom editor in Ubuntu, it appears in Ubuntu as:
6C 69 65 C3 9F 65 6E 

My expected behaviour is that the Android app saves the text like Atom does.

Thanks!

**Comment by nevenz** [comment]
What are the used and detected encodings in the app? You can see them by enabling the option in `Settings -> (Notebooks) Details -> Detected/Used encoding`.

Also, what do you use to get files from your phone to that Ubuntu system?

**Comment by haimivan** [comment]
Detected/Used: Windows-1252

I use the dropbox sync

**Comment by nevenz** [comment]
> Detected/Used: Windows-1252

Yeah, I can reproduce this by loading Windows-1252-encoded `ß` (which would be created by Orgzly) in Atom as UTF-8 (which I assume you're using, judging from C3 9F). It's saved back as EF BF BD.

You could either switch to using Windows-1252 in Atom, or try modifying the file in such way that it ends up being detected as UTF-8 by Orgzly (juniversalchardet is being used). I'm not sure which option is worse.

> How could I force the encoding to something different?

You can't yet, it's on a to-do list.  I'll see to bump the priority of this, as I don't see another solution. One should be able to do this per notebook, but perhaps short-term, a global option could be added to always import as UTF-8?

**Comment by haimivan** [comment]
>  a global option could be added to always import as UTF-8?
That would be fine for me!
