### ISSUE TITLE
Any plans on supporting taskpaper files format?

### ISSUE THREAD

**Issue by zot24** [orgzly/orgzly-android#196]
Official web site https://www.taskpaper.com

And TaskPaper open source model layer 👉  http://support.hogbaysoftware.com/t/what-is-taskpapers-open-source-model-layer

**Comment by nevenz** [comment]
Support for another format would be great. Orgzly was started with that in mind, and I think it would be very beneficial for the code health.

Java parser/generator would be a good start.

**Comment by dstrelnikov** [comment]
I'm also thinking about swith to taskpaper markup from org. But there is still no android app.
