### ISSUE TITLE
Orgzly should not use timestamps to check whether or not files have been modified

### ISSUE THREAD

**Issue by IvanMalison** [orgzly/orgzly-android#198]
This is a well known anti-pattern, as doing this sort of check is very brittle and susceptible to all sorts of bugs.

As an example suppose that timezone is set incorrectly, but local time is set correctly, while everything is set correctly server side. With the right combination of settings this could mean that lower since epoch timestamps are produced locally on the phone AFTER higher stamps are produced server side.

Depending on the current time being actually correct to ensure the correctness of a program is just a bad idea, and in this case, all that we really need is a modified since last sync property.

**Comment by louwers** [comment]
Why even bother re-implement sync? Check out [Unison](https://www.cis.upenn.edu/~bcpierce/unison/). Android binaries and build instructions are available: https://github.com/vovcacik/unison-build-scripts

**Comment by nevenz** [comment]
Related to #172.

If this is about `isModifiedAfterLastSync`, then just a flag would be enough, which I think:

> all that we really need is a modified since last sync property

suggests?

**Comment by IvanMalison** [comment]
> If this is about isModifiedAfterLastSync, then just a flag would be enough,

Yep. Not sure its related to #172 though.

**Comment by nevenz** [comment]
`Book` entity now has:

```
        val isModified: Boolean = false
```
