### ISSUE TITLE
Improve conflict status visibility

### ISSUE THREAD

**Issue by memeplex** [orgzly/orgzly-android#2]
Please add some indication that the current notebook has sync conflicts, not only the notification at the global notebook list but a local one for the current file. Currently it's too easy to miss the fact that the current file is in conflict and carry on with editing.

Also show some toast indicating a sync action was successful or not.

These are easy changes that will improve sync user experience.

**Comment by nevenz** [comment]
Action bar's subtitle could be used for status. It now contains filename (if notebooks has title defined, otherwise it's empty), which is probably not very useful.

**Comment by memeplex** [comment]
Something like a small red stock sync icon would be fine, too.

**Comment by alphapapa** [comment]
This is a good idea.  I'd also request an option to prevent editing of conflicted files by default, with a prompt to override.  e.g. if I've got Emacs handy, I'd rather resolve the conflict now, rather than make the conflict worse and realize it later.
