### ISSUE TITLE
customized desktop widget search

### ISSUE THREAD

**Issue by xlzmath** [orgzly/orgzly-android#200]
The current version only provide two option for the desktop list widget:
- s.today .i.done
- i.todo

It will be much more convenient to allow user to define their own search keywords, e.g. some people has a different TODO keyword which return nothing if searched i.todo

**Comment by nevenz** [comment]
Widget lets you select from the list of *saved searches*, which you can define in the app (by clicking "Searches" in navigation drawer).

**Comment by xlzmath** [comment]
Thank you, I didn't notice that there is such function, it now works like charm, maybe one can explain this in the documentations.

**Comment by nevenz** [comment]
TODO-ed now, either to add to docs, or include in the in-app tips (planned in the future). Thanks.
