### ISSUE TITLE
Add date head when "s.7d"

### ISSUE THREAD

**Issue by tumashu** [orgzly/orgzly-android#203]
I use s.7d to search a week's schedule. but the results is hardly to read. is it possible add a date head or a seperate-line between the day result?

**Comment by nevenz** [comment]
I think you're referring to Agenda (#55 & #106), which was implemented and is available in the latest beta version:

![Agenda](https://user-images.githubusercontent.com/10671476/32145007-10567b88-bcc2-11e7-9770-592cdf20a5cf.png)

Or not?

**Comment by tumashu** [comment]
wow, good job

**Comment by tumashu** [comment]
I have tested the beta2， but fail to show，how to enable this feature?

**Comment by tumashu** [comment]
![q](https://user-images.githubusercontent.com/67725/32150753-c3586770-bd51-11e7-8969-357fe4838339.jpg)

**Comment by nevenz** [comment]
> I have tested the beta2， but fail to show，how to enable this feature?

It's only available in the *Agenda* view (selectable from the drawer). You can't modify its search though, it's hardcoded currently.

The original idea was to improve search allowing agenda features (expanding times with repeater and separating days, which you suggest). Then we decided on having a separate Agenda view. Now again I think search and agenda are too closely related. So perhaps search query can be expanded with two instructions for splitting days and expanding times.

You could have saved searches such as:
- **Projects** - i.todo
- **Next actions** - i.next
- **Next 7 days** - .it.done ( s.7d or d.7d) ag.repeat ag.per-day

**Comment by tumashu** [comment]
I am too stupid，I find agenda first, thanks very much
