### ISSUE TITLE
When you have several reminders and click on one, the behavior is not as expected.

### ISSUE THREAD

**Issue by godofr** [orgzly/orgzly-android#214]
I'm using version 1.5.3 on Android. When several reminders have appeared: A, B, C ... and you click on A, the "node" corresponding to A does not appear, instead the "node" corresponding to B or C appears (I think the one corresponding to the last reminder that showed up). This is very annoying, because you can not edit the "node" A immediately. I think this behavior occurs since version 1.5.1 and it did not happen in 1.5. Thanks.

**Comment by licaon-kter** [comment]
Seeing this too on 1.5.3.

A B C, marked C as done, touched B, the app opened A.

**Comment by godofr** [comment]
Wow!! Thanks!!
