### ISSUE TITLE
The reminders need a LED light flashing 

### ISSUE THREAD

**Issue by NiceFeather** [orgzly/orgzly-android#216]
Orgzly all works perfect, but the reminders need a LED light flashing for the sound notifications, this function is important because nobody could know an issue happened while return back the phone left on the desktop, actually the notification is done. Look forwards to this feature later, thanks in advance!

**Comment by rieje** [comment]
Agreed--this is essential. It also doesn't vibrate for me even though that option is checked. I thought it was a bug but I'm glad to find out this is an issue that's submitted recently so hopefully it gets added soon.
