### ISSUE TITLE
In Search: Setting PRIORITY to `p.b' does not filter #B items

### ISSUE THREAD

**Issue by srustamo** [orgzly/orgzly-android#217]
Setting `PRIORITY` to `p.a` or `c`, `d` works as expected. But `p.b` returns all entries from all files (no filtering whatsoever).

**Comment by srustamo** [comment]
Actually, `p.b` seems to include #B items and all items without any priority, but excludes items with any other set priorities.

**Comment by nevenz** [comment]
Yes, `B` is a default priority which all items without a specific priority set implicitly have.

Should `p.b` display only those items with priority explicitly set? In that case there would be a need to be able to search for those without priority set. Perhaps `p.none`?

**Comment by srustamo** [comment]
@nevenz 

> Perhaps p.none?

This might be a good option. However, this will overload the search, make it more complex than needed. It looks like the 'default' priority should be used for creating a new task. Why not make any search by default include all priorities, including no priority?

**Comment by nevenz** [comment]
> It looks like the 'default' priority should be used for creating a new task.

"Default" might not be the best name to describe what it is, it's actually implicit priority.

From http://orgmode.org/manual/Priorities.html:

"By default, Org mode supports three priorities: ‘A’, ‘B’, and ‘C’. ‘A’ is the highest priority. An entry without a cookie is treated just like priority ‘B’."

> Why not make any search by default include all priorities, including no priority?

Isn't that how it works now? Or am I misunderstanding something?

**Comment by srustamo** [comment]
I see two activities, which seem to depend on ' implicit' priority: search
and task creation.

I suggest keeping task creation as is (as far as priorities are concerned).

Search however, could be updated to exclude any implicit priority as
default.

**Comment by srustamo** [comment]
I think task creation makes the 'ipliicit' priority explicit, really. So,
it is more a 'default' priority for new tasks. Implicit priority should be
none, it looks, globally.

**Comment by nevenz** [comment]
> Search however, could be updated to exclude any implicit priority as
default.

Yeah that makes sense. If people start complaining, then `p.none` could be added.

There's also ordering by priority BTW (`o.p`), but I think that should remain as it is, using default priority for notes without it.

**Comment by Ampli-fier** [comment]
I was always wondering where the _Default priority_ is used, as it is not shown (in UI) when I open a note with this priority. Is it supposed to be like this?

**Comment by nevenz** [comment]
> Search however, could be updated to exclude any implicit priority as default.

Actually, Org mode returns all notes without priority set when you search for the default one (`PRIORITY="B"` for example).

So one (or more) of these need to happen:
- Add a new option to control what `p` returns
- Support `p.none`
- Add a new operator to search only for *set* priorities

I think I prefer this last one. There's a similar thing for tags now - `t.tag` includes inherited tags, `tn.tag` looks only notes' own tags.

`pn.b` (for example) would return what you need - only notes with priority B set.

> I was always wondering where the Default priority is used, as it is not shown (in UI) when I open a note with this priority. Is it supposed to be like this?

It should be shown if the note has a priority set (even to the default value).
