### ISSUE TITLE
Remember last used 'notebook' when creating a new note from drawer

### ISSUE THREAD

**Issue by srustamo** [orgzly/orgzly-android#218]
Currently the first 'notebook', sorted alphabetically, is used by default. It seems that it may be useful to 'remember' the last used 'notebook'.

**Comment by NiceFeather** [comment]
In latest version, Option->Notebooks sort order->Modified time, and "Default notebook" can be set also.

**Comment by srustamo** [comment]
@NiceFeather Thanks.
