### ISSUE TITLE
Dropbox Synchronization broken on new installations

### ISSUE THREAD

**Issue by BubblesToTheLimit** [orgzly/orgzly-android#220]
When newly installing orgzly version 1.5.3 or greater i cannot select a repository of type dropbox for synchronization, only the type "directory".

For recreating this bug one just needs to remove orgzly, install it again and attempt to add a dropbox repository.

I can however attempt to add the repository "dropbox:/my/file/link/" to the repositories. Then a link will appear which says "link to drobpox". Upon clicking this link orgzly then crashes.

Importing single org-files however works.

**Comment by nevenz** [comment]
> When newly installing orgzly version 1.5.3 or greater i cannot select a repository of type dropbox for synchronization, only the type "directory".

Where are you installing Orgzly from? Dropbox is not available on [F-Droid version](https://github.com/orgzly/orgzly-android/issues/5#issuecomment-280654017).

> I can however attempt to add the repository "dropbox:/my/file/link/" to the repositories. Then a link will appear which says "link to drobpox". Upon clicking this link orgzly then crashes.

Heh, that's a nice hack. 😄   Fixed now, thanks. Removing the code completely by moving it to a separate module should be done eventually for F-Droid build.
