### ISSUE TITLE
Support repeated tasks

### ISSUE THREAD

**Issue by neomodern** [orgzly/orgzly-android#227]
Ideally with the same implementation as org-mode http://orgmode.org/manual/Repeated-tasks.html

**Comment by keithcrone** [comment]
Orgzly already uses repeaters

**Comment by nevenz** [comment]
@neomodern If you have some specific feature related to repeaters in mind, you can open a new issue, thanks!

**Comment by neomodern** [comment]
Ah how do you create a repeating task then within Orgzly? It would also be useful to be in the 'Getting Started' notebook.

**Comment by nevenz** [comment]
> Ah how do you create a repeating task then within Orgzly?

It's the last one on timestamp dialog (`.+1w` by default with checkbox on the right side). You can click the value to change it.

> It would also be useful to be in the 'Getting Started' notebook.

Mentioned now. Dialog could probably use some icons too (for time and repeater).

**Comment by neomodern** [comment]
Ah found it :) yeah the 'time' check box could do with a timer icon next to it and the repeater could use some sort of repeating icon next to it also.

**Comment by Asalle** [comment]
Is there any kind of logging for the event being done for the day (in case of daily occuring events), like [here](https://orgmode.org/manual/Repeated-tasks.html#FOOT70): "A timestamp is added under the deadline, to keep a record that you actually acted on the previous instance of this deadline. "?

**Comment by nevenz** [comment]
> Is there any kind of logging for the event being done for the day (in case of daily occuring events)

@Asalle Perhaps "Settings / Notes & Notebook / Log to drawer on time shift" ?

**Comment by Asalle** [comment]
Thanks, you are a life saver!
