### ISSUE TITLE
Support file globbing or recursive search for notebooks

### ISSUE THREAD

**Issue by srustamo** [orgzly/orgzly-android#230]
It seems that only top level org files are found when Dropbox dir is set. For instance, I have ~/Dropbox/Apps/MobileOrg/DB, which has some org files, as does the App dir, which is what is set in the Orgzly "repository" setting. 

I suppose (did not try, perhaps not supported) I could manually enter the subdir as an additional "repository", but I have several subdirs with org files, which makes the process tedious.

**Comment by nevenz** [comment]
There's #225, recently created.

( Yes, you could enter any number of repositories, even different types. )
