### ISSUE TITLE
Sync button on homescreen widget

### ISSUE THREAD

**Issue by jethrokuan** [orgzly/orgzly-android#232]
Adding a sync button in the homescreen widget to trigger a sync and refresh the filter view would be great.

**Comment by nevenz** [comment]
This was suggested before in #85, but was decided against.

You could enable the ongoing notification which has a sync button. Also, there's #143, so you can have the app icon next to a widget. Would those work for you?

**Comment by jethrokuan** [comment]
Yes, the suggestion in #85 would be great!! Thanks
