### ISSUE TITLE
[Feature request] Sync parsed data to 3rd party cloud services like Google Calendar, Keep

### ISSUE THREAD

**Issue by hyiltiz** [orgzly/orgzly-android#235]
This is not strictly the minimalist approach, I know. As a minimalist myself, I am ditching many other programs for Orgzly which I found recently, and am currently porting my schedules, to-dos to it. However, it would also be great if it could sync up the todo lists, (recurrent or one time) events to Google Calendar, so many things will be easier. An example: we have Google for Organizations in where I work and Google Calendar supports scheduling meetings etc., so people can look up when I am available. Porting all my notes back into Google Calendar manually isn't really minimalist, and we should be able to write a parser to create events to push to Google Calender. 

Maybe also pulling events from some specific calendar in Google Calendar would also be a very appealing feature, but that really can wait; I don't mind manually doing the migration to Orgzly myself, but generally it is helpful to gain more new users.

**Comment by mkaito** [comment]
This may or may not be relevant to you, but there's a way to sync between org-mode on Emacs and Google Calendar.

El 26 de noviembre de 2017 15:45:27 GMT+00:00, "Hörmet Yiltiz" <notifications@github.com> escribió:
>This is not strictly the minimalist approach, I know. As a minimalist
>myself, I am ditching many other programs for Orgzly which I found
>recently, and am currently porting my schedules, to-dos to it. However,
>it would also be great if it could sync up the todo lists, (recurrent
>or one time) events to Google Calendar, so many things will be easier.
>An example: we have Google for Organizations in where I work and Google
>Calendar supports scheduling meetings etc., so people can look up when
>I am available. Porting all my notes back into Google Calendar manually
>isn't really minimalist, and we should be able to write a parser to
>create events to push to Google Calender. 
>
>Maybe also pulling events from some specific calendar in Google
>Calendar would also be a very appealing feature, but that really can
>wait; I don't mind manually doing the migration to Orgzly myself, but
>generally it is helpful to gain more new users.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/orgzly/orgzly-android/issues/235

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by jethrokuan** [comment]
Keep doesn't have an open API afaik, so this is pretty much impossible. Calendar sync solutions are still rough on the edges, but they exist for org-mode, and can be run on a chron job. I think this feature is out of the scope of orgzly itself.

**Comment by nevenz** [comment]
There's also #57 already.
