### ISSUE TITLE
[type/feat] Time tracker and event scheduler: clocking and estimating work time

### ISSUE THREAD

**Issue by hyiltiz** [orgzly/orgzly-android#236]
Org-mode seems to support scheduling (recurrent or not) events and estimating work times required for those. In addition, it seems you can track work times (using relative times) for a task. These two features: scheduling task, and tracking task, is often separated into two apps in the mobile app markets. Examples: "A Time Tracker" by @netmackan and Orgzly, or Google Calendar for scheduling (recurrent or not) events and Google Tasks/Keep for keeping notes and tasks (mostly one time) in the native apps.

Adding a time tracking and scheduling (setting a START and END time property for events/tasks) would be very ideal.

**Comment by nevenz** [comment]
Is this #15?

**Comment by hyiltiz** [comment]
time tracking part is duplicate of #15 but scheduling isn't; it is more like you create an event in Google Calendar with clearly defined boundaries to stay organized and plan (not todo-list like events that mostly happens once but more like habit/routine like events).

**Comment by nevenz** [comment]
> it is more like you create an event in Google Calendar with clearly defined boundaries to stay organized and plan (not todo-list like events that mostly happens once but more like habit/routine like events).

Maybe #163 then? Something like that?

Scheduling with repeater is already possible, but ranges are not supported yet.

**Comment by hyiltiz** [comment]
Yes! #163 and #15 it is.
