### ISSUE TITLE
Highlighting all out-of-date task items with different color

### ISSUE THREAD

**Issue by NiceFeather** [orgzly/orgzly-android#240]
Sometimes there were some reminders of tasks scheduled didn't work for a variety of reasons, after that it was difficult to find out these items through the crowded checklist because all items listed color is the same. Highlighting all out-of-date task items with different color should be essential.

**Comment by nevenz** [comment]
Can you simply create a search that would return those, to have them swipe&click away?

I don't think everyone would want coloring *all* tasks with *any* of the times in the past (I know I wouldn't). So user would have be able to define them (what notebook, scheduled or deadline, etc.). Which boils down to using search queries.

**Comment by NiceFeather** [comment]
Thanks for your responding, all out-of-date tasks search condition should be 's.lt.today or d.lt.today' or something? It's not quite sure because I had some searching tries and failed each time, it seems returned everything. Are those terms stay PROPOSAL in the Orgzly Search documentation at present?

**Comment by nevenz** [comment]
>  all out-of-date tasks search condition should be 's.lt.today or d.lt.today' or something?

It's just `s.today or d.today`. That returns notes with scheduled or deadline time set to today or earlier. See http://www.orgzly.com/help#Search

> Are those terms stay PROPOSAL in the Orgzly Search documentation at present?

That page needs updating. Those operators (like `lt`) are not implemented, but some other things are.

**Comment by NiceFeather** [comment]
OK, Maybe it's a more simple alternative to go yet, Thank you, nevenz.
