### ISSUE TITLE
Select Initial View

### ISSUE THREAD

**Issue by tekstrong** [orgzly/orgzly-android#246]
It would be great to have the ability to select what is initially displayed when Orgzly is opened. For example, I prefer to see my Agenda when I open the app instead of the Notebooks view. Someone else may prefer a specific notebook to be what they see every time they open Orgzly. Having this user-selectable could be a large improvement to usability and shave off a little bit of time for the user at every launch.

**Comment by tekstrong** [comment]
Also meant to include adding a search as a possible option for initial view, this could be incredibly handy.

**Comment by NiceFeather** [comment]
I know this app has a shortcuts widget for placing any notebook to android home screen, but except for agenda with calendar view.

**Comment by nevenz** [comment]
> I knew this app has a shortcuts widget for placing any notebook to android home screen, but except for agenda with calendar view.

Yes, shortcuts should be used for this - for saved searches (#78) or agenda (#210).

I think the main app icon needs to remain as it is, for consistent navigation.

> Also meant to include adding a search as a possible option for initial view, this could be incredibly handy.

Yeah, this will be able to cover any view in the future (the plan is to add options to the query to open note if it's the only one in search results, or notebook, if found).

**Comment by tekstrong** [comment]
Thanks for pointing out that Notebooks are accessible via Shortcuts, that is helpful. I've commented in [#210](https://github.com/orgzly/orgzly-android/issues/210) as this issue is closed.
