### ISSUE TITLE
Quit inputting more slowly in long list notebook

### ISSUE THREAD

**Issue by NiceFeather** [orgzly/orgzly-android#249]
This maybe is need to improvement issue.
I found it is quite a while to quit inputting a task, it seems there were some post-processing even though nothing inputted after the cancel button pressed, My device is Galaxy S7 Edge and I'm sure its performance is not bad, Any chance for checking or improving this?

**Comment by nevenz** [comment]
Hmm here's not much going on there. You are referring to the time from when you click on `X` in the note until the notebook is displayed?

You're not seeing anything similar in other apps?

**Comment by NiceFeather** [comment]
>  You are referring to the time when you click on X in the note until the notebook is displayed?

I mean only in the inputting dialog of adding task when clicking on X.

**Comment by NiceFeather** [comment]
> You're not seeing anything similar in other apps?

No, all app works perfect in my phone, actually I'm also a programmer.

**Comment by nevenz** [comment]
> You are referring to the time when you click on X in the note until the notebook is displayed?
> I mean only in the inputting dialog of adding task when clicking on X.

Right, but that brings you back to the notebook view, right? So it's the time between those two events (clicking X in note -> notebook view)?

And it's only for new notes?

Which version of Orgzly is this BTW?

**Comment by NiceFeather** [comment]
So sorry maybe my expression in above isn't clear, I just took an adding task test in a new notebook, all is perfect whether hit the OK or Cancel button in that form, I found there would raise a poor performance for adding any task in an existing long list note, even quit inputting so are. Most of my notebook just has more than 150 lines that the file size of .org file only is 2kb, And, the situation would be even worth worse if once the lines is increased in any notebook.

Maybe org parsing procedure should be optimized, some memory cache tech should be used, it's just a suggestion.

**Comment by nevenz** [comment]
Large **note** could be the cause of something like this, because its hash is calculated to check for changes.

But I don't see how large **notebook** could be. I have notebooks that have ~2000 notes in them.

Anyway, I'll see what else can be done to test this.

**Comment by codemac** [comment]
I have the same problem, where when I click the save or cancel button, it'll sit there for quite a while before the capture dialog goes away. When I click save N times in frustration (lol) it will create N duplicate notes in the notebook. Cancel takes just as long.

I have auto-sync enabled, and very large org files (megabytes).

**Comment by nevenz** [comment]
How large are those notes? Does it even depend on the size of the note?

**Comment by nevenz** [comment]
Also, does disabling "Style text" makes any difference?

**Comment by nevenz** [comment]
> Just did a test for the late v1.6.3 according to the procedure of last time, I thought the performance is also seems improved, but still not perfect. Were these code related optimized?

Cool, thanks for testing. Yes, query used for getting notes was simplified (bf0e256f12b1d6569dd6a256173482261fcaee13). Though main reason was #289, which is when you modify something.

But I'm not seeing anything like described here when you don't modify anything, unless there's a lot of markup in view (which does need optimizing).

So I'm still curious if the size of the note or turning off "Style text" make any difference here.

**Comment by codemac** [comment]
Ok.

Turning off "Style text" made a HUGE difference for me. Went from 5+ seconds to save to 0.

**Comment by nevenz** [comment]
> Turning off "Style text" made a HUGE difference for me. Went from 5+ seconds to save to 0.

Great, thanks. That code needs some major optimization. It uses regexes, starting from the beginning on every find and for every type of markup/link.
