### ISSUE TITLE
Note: Support for forthcoming Keybase encrypted file-sync

### ISSUE THREAD

**Issue by nickgarber** [orgzly/orgzly-android#252]
https://keybase.io/docs/kbfs
https://github.com/keybase/client/issues/9948

As of Dec 17th, 2017 the Keybase Android app doesn't yet support file-sync but it is on their roadmap.

Once encrypted file-sync on mobile is available, it _might_ look just like local storage, requiring no particular effort to use/support in Orgzly.

This issue is not exactly a feature request or question, but more a heads-up that this could turn into a really beneficial feature to support a nice use-case with Orgzly.

**Comment by ryanprior** [comment]
Keybase files just landed in mobile in a recent update, but unless I'm mistaken they aren't exposed as "normal" local storage. However, we might be able to build an integration into Orgzly, and that's a use case that I'm personally quite interested in. I already have a bunch of org-files in my kbfs that I edit and review across my various non-mobile devices, and now I can access them on my mobile tool (but not yet in Orgzly)

**Comment by TinaRussell** [comment]
I just wanted to note that Keybase support is a feature I’d really appreciate! Has there been any progress on this? (Also, support for Keybase’s [encrypted git storage](https://keybase.io/docs/git/index) would be amazing; not sure if that would be easier/harder than supporting Keybase’s regular encrypted file storage, though.)
