### ISSUE TITLE
Sparse Trees?

### ISSUE THREAD

**Issue by keithcrone** [orgzly/orgzly-android#257]
Is there really no open request for sparse trees yet?

I still have a hard time finding things in Orgzly. I don't really get the design choice of always going to the note edit screen in search results or linking, which we talked about before.

If I search for something simple like "Birthday", all I can get is the file it's in, Contacts maybe. I guess I'm just expecting results more like:
Contacts->Personal->Joe->
Birthday
<Scheduled: xx>
I'm hacking my way around this by tagging each headline with the same title and using tag inheritance to display the information I'm looking for. More like:
Birthday                 :Contacts:Personal:Joe:
<Scheduled: xx>
Which seems unnecessary. If I create separate files for each contact, then I could have 100s of files or more if I'm trying to manage a CRM type of thing. For me, I run a sales business where I export products from the US to Asian markets. Each order has a loading date, shipping, paid, etc. If I try to create an order in it's own file, then I have dozens of extra files every month with search results that look like:
Loading
3o42han59x1.org
<Scheduled: xx>
Not only do I still have to rely on a tagging hack, but when I have multiple orders around the same time, I have to follow the swipe menu link to view any other details to know if this is the order I'm looking for...because the only information I can view is the note edit screen.

With that said, I came looking for any discussion about sparse tree like display results but there wasn't an open request, until now. Maybe some form of sparse tree display will work better.

**Comment by nevenz** [comment]
This sounds more like #182 (with clickable ancestors)?

Sparse trees (per Org mode's definition) would be per file, with the possibility to move nodes around etc. Something you can't do with search results (being a virtual view).

**Comment by keithcrone** [comment]
I understand. I'll be honest, I'm reaching for anything.

I know in Org-mode this is a per file basis. But you don't manage each file
individually per se, you perform search and other functions on a database,
and export to the correct format. States, for example, are also global, in
the sense that I can define them per file if I choose in Org-mode but not
Orgzly. Internal linking works per file but globally in Orgzly. I expected
the results would also be global and just sorted or limited to b.notebook.

Hundreds of files aren't manageable in Orgzly. Larger files require a lot
of manual searching anyway.

If you can give me other ideas, I'm all ears. I'm not in front of a
keyboard most of the day like I'm sure most people who use Org-mode. I'm
trying to make it work on mobile, but search results don't display enough
information. If anyone can give me some tips I would be incredibly
appreciative. I'm really trying to avoid pandoc-ing all my files and moving
them to Workflowy or Dynalist as I think Orgzly is a better product.

**Comment by nevenz** [comment]
> I expected the results would also be global and just sorted or limited to b.notebook

Right, I just mentioned "per file" to distinguish this from what "sparse trees" is in Org mode.

So how's #182 for suggestion? Notes in search results would look like:

Birthday
📁  Contacts
📄  Personal 📄  Joe

Ancestors and notebook being clickable. They could be hard to click though, space being very small. Although a new bigger layout is planned for notes in the list, which would help.

Another option is opening a menu on click, where you'd choose any of the notes or notebook the target note is in:

📁  Contacts
📄  Personal
📄  Joe
📄  Birthday

But having to click twice could quickly become annoying.

**Comment by keithcrone** [comment]
That's fine, @Nevenz. Close this one if you need to. I opened a new issue
to try to push better search results (or something similar) to the front of
the line for anyone that may be contributing to the code, rather than get
lost in the 100+ other suggestions that are open.

No worries. I'll figure something out. Thanks for a good product.

**Comment by nevenz** [comment]
I'll close it as a duplicate (even though there's still no issue for actual per-file sparse trees).
