### ISSUE TITLE
Table / monospace font alignment bug

### ISSUE THREAD

**Issue by keithcrone** [orgzly/orgzly-android#259]
This is happening with my tables when I move them into Orgzly. Not with all of them, not all the time, and not much of an issue by any means. But the text still isn't always aligning for whatever reason. Just pointing it out in case it is indicative of some other issue.
![screenshot_2017-12-29-09-09-25](https://user-images.githubusercontent.com/27098012/34441203-c9eb6fda-ec7f-11e7-824b-7015c995804b.png)

**Comment by nevenz** [comment]
It looks like it's due to removed characters for bold? `*text*` being 2 characters longer then `text`.

I don't see what could be done, before support for tables is implemented.

**Comment by nevenz** [comment]
BTW, you could enable "Styled text with marks" option, to have \***text**\* displayed instead of **text**.

**Comment by keithcrone** [comment]
Ah, you're right.
It was happening elsewhere in other situations, but all were due to font styling (which wasn't the purpose). Changing the Styled Text option realigned everything.
Thanks
