### ISSUE TITLE
Add an actual notification for a reminder

### ISSUE THREAD

**Issue by licaon-kter** [orgzly/orgzly-android#26]

**Comment by Endi1** [comment]
I'd like to tackle this. @nevenz any suggestions on where to start?

**Comment by licaon-kter** [comment]
Requirements are:
* Background service.
* Start on boot.
* Notification with _snooze_ (configurable) and _mark as DONE_.
* Notify user to whitelist app in battery settings (on Android 6 and later Doze will suppress notifications)

Plenty of notes apps on GitHub for inspiration:
https://github.com/spacecowboy/NotePad (I use this but it's no longer in development)
https://github.com/SecUSo/privacy-friendly-notes
https://github.com/SecUSo/privacy-friendly-todo-list

**Comment by a13ph** [comment]
I'd pay for this and whoever implements it can message me to hold me responsible
I'm wary of spoiling the FLOSS flow with such statements, but I really really need this

**Comment by nevenz** [comment]
> I'd like to tackle this. @nevenz any suggestions on where to start?

I've actually started on this a while back. I can push that branch and you're welcome to jump in. :)

**Comment by Endi1** [comment]
Awesome :)

**Comment by nevenz** [comment]
I've squashed work so far into a single commit, now in https://github.com/orgzly/orgzly-android/tree/reminders.

**Comment by licaon-kter** [comment]
Status of this?

**Comment by nevenz** [comment]
> Status of this?

I'll be continuing work on this soon, hoping to include it in the next release.

**Comment by nevenz** [comment]
This is merged to master and `reminders` branch is deleted.

Not complete yet, so I've marked "Reminders" in Settings as "beta".

**Comment by licaon-kter** [comment]
Yep, build is live on F-Droid (you'll need to toggle `Unstable builds` to ON in Settings)

First thought: Make default time `current time+1 hour`, now it's `now`, not very useful.

**Comment by nevenz** [comment]
> First thought: Make default time current time+1 hour, now it's now, not very useful. ( I see it will be next minute but I find it too short, by the time I end up saving the note that minute would have passed already)

Very useful currently while testing though. 😄 But yeah, I'll change the default.

> Sound/vibration is not wired yet? Did not hear anything.

Right, still to be done.

> Setting a reminder time in the past should pop up the notification right away (it might be a mistake and I will not notice it otherwise)

Hmm should it? Perhaps it's better to issue a warning (snackbar message)? Good point about catching a possible error in any case.

**Comment by licaon-kter** [comment]
A snackbar might be missed, the actual notification is more poignant, "hey, why did this appear now?"

**Comment by BubblesToTheLimit** [comment]
I love this feature, where do i throw the money?
