### ISSUE TITLE
Dropbox Sync Encrypted?

### ISSUE THREAD

**Issue by haimivan** [orgzly/orgzly-android#263]
I use Orgzly with my Android smartphone.

My question is: do I risk anything, if I do a file sync to Dropbox in an open WLAN?

Thanks in advance!

**Comment by nevenz** [comment]
> I use Orgzly with my Android smartphone.
> My question is: do I risk anything, if I do a file sync to Dropbox in an open WLAN?

Their official SDK is used to access their API, so not more then you do with their app or anything else that goes over SSL.

There are plans for another layer of security with #43 or #202.

**Comment by haimivan** [comment]
Thanks!
