### ISSUE TITLE
Vote for at least s.now from Search proposal

### ISSUE THREAD

**Issue by zentiggr** [orgzly/orgzly-android#265]
My optimal filtering and structure for a master todo list would be

s.now o.state o.sched o.dead

Since o.state support is already committed, I would love to have s.now even if the entire search proposal doesn't make it in yet.

Barely familiar with Kotlin or I would consider working up the PR myself... or give me a little while...

**Comment by nevenz** [comment]
Just to be clear - you want to get rid of entries that have scheduled time between now and midnight? (Otherwise you could be using `s.today`.)

**Comment by zentiggr** [comment]
Yes - I am using "s.today o.sched o.dead" right now... but with s.now I could use "s.now o.state o.sched" and have only up to the minute items in the list.  
(I have some focus issues, and have a suite of +1d and ++12h repeaters that I would like to only see when the current instance is relevant, instead of having all night's repetitions as well.)

**Comment by nevenz** [comment]
I've implemented this for next version (current beta), as it uncovered a bug with `s.0h` (which I was going to suggest you use).

**Comment by zentiggr** [comment]
I think s.Nh is undocumented... it is live in 1.6.1 though?  I could easily use s.1h or s.2h, as just that much lookahead could be very helpful and I was assuming s.today and s.now were the closest I could get.

**Comment by zentiggr** [comment]
Tested and I see s.1h is acting like s.today.

**Comment by nevenz** [comment]
> I think s.Nh is undocumented... it is live in 1.6.1 though?

Yes to both, I'm updating documentation right now.

> Tested and I see s.1h is acting like s.today.

Yeah, this has been fixed.

**Comment by zentiggr** [comment]
Awesome... Grabbing the beta 2 apk!

**Comment by nevenz** [comment]
> Awesome... Grabbing the beta 2 apk!

It's not in beta.2 BTW, it will be in the next one (probably tomorrow).

**Comment by zentiggr** [comment]
Ok... cooling my jets.  Thanks!

**Comment by zentiggr** [comment]
Tested, working just as intended. Thanks so much!
