### ISSUE TITLE
(o.s and o.d) will crash Orgzly

### ISSUE THREAD

**Issue by keithcrone** [orgzly/orgzly-android#266]
I thought
o.s o.d  |  o.s and o.d. |  (o.s and o.d)
would all yield the same results at the end of a search query, but the last one crashes Orgzly. Other nonsensical options like (o.s or o.d) also crash.

**Comment by nevenz** [comment]
I can't reproduce this. Are you able to send a crash report?

BTW, `o`s can be thrown anywhere in the query, they will be picked up in order, but ignored when constructing the *search* query. So there is no need to group them, or use logical operators. I'm guessing you've been just testing, I'm just mentioning for the record if someone stumbles upon this.

Thanks!

**Comment by nevenz** [comment]
Thanks for the report.

I can't reproduce it with `(o.s and o.d)`, but I can with `"(o.s and o.d)"`.

You do get the crash with just `(o.s and o.d)`?

**Comment by keithcrone** [comment]
Correct. No quotes, just (o.s and o.d)

**Comment by nevenz** [comment]
> Correct. No quotes, just (o.s and o.d)

And the original `v1.6.2-beta.2` ? Weird... I'll keep digging and fix the issue with quotes.

**Comment by keithcrone** [comment]
I just upgraded Orgzly to the latest (beta) version on my tablet and it happens there also.

**Comment by nevenz** [comment]
I'm still failing to reproduce this, but I've fixed the issue with `"(o.s and o.d)"` which was giving the exact same exception.

It's in `v1.6.2-beta.3`, now released.

Let me know if it changes anything when you get a chance (though it probably won't). Thanks!

**Comment by keithcrone** [comment]
Still crashes, just FYI

**Comment by nevenz** [comment]
I don't see anything wrong with logic, it's hard to debug this without seeing logs. But that requires installing `adb`, connecting the device with USB, and installing the debug build of APK. If there's any chance you could do that, let me know. If not, we'll just see how it goes in production - perhaps different reports (different queries) would give some clue.

**Comment by keithcrone** [comment]
I already have ADB installed so I'll help you if you need it.

**Comment by keithcrone** [comment]
I'm going to take a guess and say this is the relevant part of the log from my phone after the crash. If you need other parts based on another apk or whatever, let me know.


01-12 16:02:02.301 11623 11936 E SQLiteLog: (1) near ")": syntax error
01-12 16:02:02.301  4768  7579 D RestrictionPolicy: userId: 0, isMicrophoneEnabledAsUser : true
01-12 16:02:02.311 11623 11936 E AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #2
01-12 16:02:02.311 11623 11936 E AndroidRuntime: Process: com.orgzly, PID: 11623
01-12 16:02:02.311 11623 11936 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at android.support.v4.c.n$3.done(ModernAsyncTask.java:161)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteException: near ")": syntax error (code 1): , while compiling: SELECT * FROM notes_view WHERE (is_cut = 0 AND level > 0) AND (()) ORDER BY scheduled_time_timestamp IS NULL, scheduled_time_start_of_day, scheduled_time_hour IS NULL, scheduled_time_timestamp, deadline_time_timestamp IS NULL, deadline_time_start_of_day, deadline_time_hour IS NULL, deadline_time_timestamp, is_visible
01-12 16:02:02.311 11623 11936 E AndroidRuntime: #################################################################
01-12 16:02:02.311 11623 11936 E AndroidRuntime: Error Code : 1 (SQLITE_ERROR)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: Caused By : SQL(query) error or missing database.
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	(near ")": syntax error (code 1): , while compiling: SELECT * FROM notes_view WHERE (is_cut = 0 AND level > 0) AND (()) ORDER BY scheduled_time_timestamp IS NULL, scheduled_time_start_of_day, scheduled_time_hour IS NULL, scheduled_time_timestamp, deadline_time_timestamp IS NULL, deadline_time_start_of_day, deadline_time_hour IS NULL, deadline_time_timestamp, is_visible)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: #################################################################
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1062)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:627)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1454)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1301)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1172)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1340)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at com.orgzly.android.provider.Provider.a(Provider.java:326)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at com.orgzly.android.provider.Provider.query(Provider.java:177)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at android.content.ContentProvider.query(ContentProvider.java:1058)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:245)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:502)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at android.support.v4.c.c.a(ContentResolverCompatJellybean.java:33)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at android.support.v4.c.b$c.a(ContentResolverCompat.java:57)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at android.support.v4.c.b.a(ContentResolverCompat.java:125)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at android.support.v4.c.i.h(CursorLoader.java:59)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at android.support.v4.c.i.d(CursorLoader.java:37)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at android.support.v4.c.a.e(AsyncTaskLoader.java:302)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at android.support.v4.c.a$a.a(AsyncTaskLoader.java:57)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at android.support.v4.c.a$a.a(AsyncTaskLoader.java:45)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at android.support.v4.c.n$2.call(ModernAsyncTask.java:138)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-12 16:02:02.311 11623 11936 E AndroidRuntime: 	... 3 more
01-12 16:02:02.321  4768  4782 D RestrictionPolicy: userId: 0, isMicrophoneEnabledAsUser : true
01-12 16:02:02.321  4768  7215 W ActivityManager:   Force finishing activity com.orgzly/.android.ui.MainActivity
01-12 16:02:02.321  4768  7215 D FocusedStackFrame: Set to : 0
01-12 16:02:02.331  4768  7215 D InputDispatcher: Focused application set to: xxxx
01-12 16:02:02.331  4768  7215 D InputDispatcher: Focus left window: 11623

**Comment by nevenz** [comment]
Great!

I got those logs from Google Play though, debug build has more verbose output:

[orgzly-1.6.2-beta.3+debug.apk.zip](https://github.com/orgzly/orgzly-android/files/1627705/orgzly-1.6.2-beta.3.debug.apk.zip)

This is latest beta, but `premiumDebug` build variant. It's signed too, so you'll be able to just upgrade the current version. Needs unzipping (zipped so it can be attached here).

This is a part of the log when I do a `(o.s and o.d)` search:

```
01-12 23:24:39.144 10855 10855 D com.orgzly.android.ui.fragments.SearchFragment: 2#main: onActivityCreated: Loader #9 for: o.s o.d
01-12 23:24:39.145 10855 10855 D com.orgzly.android.ui.fragments.SearchFragment: 2#main: onCreateLoader: 9 null
01-12 23:24:39.146 10855 10855 D com.orgzly.android.ui.fragments.QueryFragment: 2#main: onResume
01-12 23:24:39.146 10855 10855 D com.orgzly.android.ui.MainActivity: 2#main: announceChanges: com.orgzly.android.ui.fragments.SearchFragment Search o.s o.d 0
01-12 23:24:39.148 10855 10880 D com.orgzly.android.provider.Provider: 28236#ModernAsyncTask #1: query: content://com.orgzly/notes/queried?o.s%20o.d null (is_cut = 0 AND level > 0) null null
01-12 23:24:39.149 10855 10880 D com.orgzly.android.provider.Provider: 28236#ModernAsyncTask #1: runUserQuery: o.s o.d null
01-12 23:24:39.158 10855 10880 D com.orgzly.android.provider.Provider: 28236#ModernAsyncTask #1: runUserQuery: Query(condition=And(operands=[]), sortOrders=[Scheduled(desc=false), Deadline(desc=false)], options=Options(agendaDays=0)) And(operands=[]) scheduled_time_timestamp IS NULL, scheduled_time_start_of_day, scheduled_time_hour IS NULL, scheduled_time_timestamp, deadline_time_timestamp IS NULL, deadline_time_start_of_day, deadline_time_hour IS NULL, deadline_time_timestamp, is_visible (is_cut = 0 AND level > 0)  scheduled_time_timestamp IS NULL, scheduled_time_start_of_day, scheduled_time_hour IS NULL, scheduled_time_timestamp, deadline_time_timestamp IS NULL, deadline_time_start_of_day, deadline_time_hour IS NULL, deadline_time_timestamp, is_visible
01-12 23:24:39.183 10855 10855 D com.orgzly.android.ui.MainActivity: 2#main: onCreateOptionsMenu: android.support.v7.view.menu.MenuBuilder@33cafa5
01-12 23:24:39.186 10855 10880 D com.orgzly.android.provider.Provider: 28236#ModernAsyncTask #1: query: Cursor count: 29 for null (is_cut = 0 AND level > 0) 
```

Depending on a crash, I might have to add or modify some logging and send a new APK.

**Comment by nevenz** [comment]
Thanks for the sent log and again for helping out debug this.

Got it now - I was checking the logic only when the search is entered from the action bar, completely ignoring the other two ways one can start it - using a saved search from the drawer or a widget. 😓 

Bug is that the query is normalized *only* when it's entered from the action bar (so that it can be immediately displayed clean to the user). This should be done always, before it's processed.
