### ISSUE TITLE
Do not add unneeded witespace

### ISSUE THREAD

**Issue by nikty** [orgzly/orgzly-android#272]
Orgzly breaks org-crypt'ed entries by inserting unnecessary empty line under heading before **-----BEGIN PGP MESSAGE-----** line on file save, while (org-decrypt-entry) looks for that line right after the heading:
`       (when (looking-at "-----BEGIN PGP MESSAGE-----")
	 (org-crypt-check-auto-save)
                     ...)
`

While it's possible to work around this behavior by tweaking org-crypt functions, wouldn't it be better to not add extra newlines?

**Comment by nevenz** [comment]
See #190, you can control that empty line in Settings.

**Comment by nikty** [comment]
Aha, thank you!
