### ISSUE TITLE
Directory selecting option for Import and export saved searches

### ISSUE THREAD

**Issue by NiceFeather** [orgzly/orgzly-android#274]
Currently all of Importing&Exporting saved searches is put in local path 'Download' as default, and so does the file named 'orgzly.filters.json', Any chance to select/set the directory and the file name?

btw, the file name seems not appropriate, I think. Not all people are developers. :)

**Comment by nevenz** [comment]
> Currently all of Importing&Exporting saved searches is put in local path 'Download' as default, and the file name 'orgzly.filters.json', Any chance to select/set the directory and the file name?

Yes, this was more like a quick hack, now that the queries can be rather complicated. The plan is to be able to sync those using the same user-configured repositories eventually.

> btw, the file name seems not appropriate, I think. Not all people are developers. 

Well actually - it was added mostly for developers. 😄  That is - people who would clear database or uninstall app often for testing.

I agree of course - you need to be able to choose the directory and specify the name for exporting, and pick a file when importing.

> the file name seems not appropriate

Though I'm curious - do you mean the actual name of the file, or the the fact that it's JSON?

What would you use?  (I do want to set a user-friendly name as a default.)

Thanks!

**Comment by NiceFeather** [comment]
> Though I'm curious - do you mean the actual name of the file, or the the fact that it's JSON?
> What would you use? (I do want to set a user-friendly name as a default.)

The file contents does well, and I propose the default extension renaming to 'MyFilters.OSQ' (Orgzly Search Queries) maybe more directly, it can also act in coordination with another ORG file extension.

**Comment by nevenz** [comment]
I think the extension needs to match the type of the file, we shouldn't invent new ones. I changed the file to "Orgzly Search Queries.json", but of course, this will be all be configurable in the future.

**Comment by nevenz** [comment]
Done in ef074609.
