### ISSUE TITLE
Full Calendar when selecting date or ability to edit date in plaintext

### ISSUE THREAD

**Issue by mtekman** [orgzly/orgzly-android#276]
Hi I searched for related issues but could not find anything, though please close if duplicate.

When I wish to set a date (schedule or deadline) I get presented with a limited set of options (+/- 3 days, 1 week).

Is it possible to see a full calendar, or at least an option to set date plain-text?

**Comment by nevenz** [comment]
Displayed date, time and repeater in that dialog are all buttons.

**Comment by mtekman** [comment]
Indeed, but they are limited in their scope.

I was hoping for a textbox for more custom dates, possibly?

Or a native or lightweight calendar dialog? Zenity for android, or something similar.

**Comment by nevenz** [comment]
Do you mean possibility to enter `next Friday`, `every Sunday`, etc. ?

What do you mean by "calendar dialog" that's different from the calendar you get when you click on the actual date?

**Comment by mtekman** [comment]
Apologies if I'm being dense.

![unknown](https://user-images.githubusercontent.com/20641402/35185063-e1f4b62c-fdf5-11e7-8313-9f82cd6f88ea.jpg)

The icons only give an option of 3 days, the current time, and a repeat of 1w.

How are custom days set?

**Comment by mtekman** [comment]
Sorry I have just now understood what you meant by "Displayed date, time and repeater in that dialog are all buttons."

Clicking on the text opens the appropriate dialogs.

sorry to trouble you, and thanks for this wonderful app!
