### ISSUE TITLE
Allow editing of Agenda query parameters

### ISSUE THREAD

**Issue by namdnguyen** [orgzly/orgzly-android#283]
It would be nice if we could change the Agenda search query from the default. In particular, I would like to be able to exclude certain notebooks, but you could customize any other parts according to your need.

**Comment by nevenz** [comment]
This is done and in beta now (you can [join beta here](https://play.google.com/apps/testing/com.orgzly)).

See https://github.com/orgzly/orgzly-android/issues/219#issuecomment-351827332

You'll be able to use "ad.DAYS" in *any* query.

**Comment by nevenz** [comment]
I'll tag this as a feature, since I don't think there was ever an issue for this specific change, just few issues that talk about it (#203 being another one).
