### ISSUE TITLE
ADB command to trigger Orgzly notebooks sync

### ISSUE THREAD

**Issue by sokolgeo** [orgzly/orgzly-android#284]
I am using ADB to put my org-mode files to and from my Android tablet for Orgzly. 
This works fine with ADB push/pull commands.

If only I could make Orgzly to sync its database with external storage from ADB console.

My understanding is that it should be something like 
`adb shell am start -n com.package.name/com.package.name.ActivityName`

https://stackoverflow.com/questions/4567904/how-to-start-an-application-using-android-adb-tools#4567928

But what exactly should I specify to make Orgzly sync all its Notebooks?
Can you please help?

**Comment by nevenz** [comment]
From https://github.com/orgzly/orgzly-android/issues/8#issuecomment-288946032 it's:

```
adb shell am startservice -a com.orgzly.intent.action.SYNC_START com.orgzly/com.orgzly.android.sync.SyncService
```

**Comment by sokolgeo** [comment]
Thank you, it works nice.
Any easy way to make my .sh file to pause until execution of this command completes?
Or I should somehow use Orgzly autosync feature to keep orgly always in sync with external notebook file?

**Comment by nevenz** [comment]
That command just sends a signal to Orgzly to start the sync, it doesn't block.

It looks like `adb shell dumpsys activity services orgzly` might be useful to detect if `SyncService` is running.

You could try auto-sync - there's more work to be be done there (make it smarter, not block some actions before if finishes etc.).
