### ISSUE TITLE
Import&Output all of configuration feature

### ISSUE THREAD

**Issue by NiceFeather** [orgzly/orgzly-android#285]
I have two devices which running the app, and hope they have the same configuration, so I set all options in which one, but how can I carry them to the another? Current app options is growing day by day and the setup is more detailed and complicated, We need an Import&Output all of configuration feature, this is essential. Maybe at first these app configurations can be consider to place on the local as files, the next step is remote database server used for sync.

**Comment by nevenz** [comment]
#156
