### ISSUE TITLE
Do not show notebook name under search results if search narrows to exactly one notebook

### ISSUE THREAD

**Issue by delexi** [orgzly/orgzly-android#294]
If I have a search that includes exactly one `b.` clause, I find the notebook name displayed under each search result to be redundant. In that specific case it might make sense to not display the notebook name. See below screenshot for further illustration.
![](https://i.imgur.com/gj0IOWo.png)

**Comment by keithcrone** [comment]
Geez. And I'm trying to get him to include more information in search results, like this:
![screenshot from 2018-02-09 14-16-02](https://user-images.githubusercontent.com/27098012/36048168-e5200456-0da3-11e8-83c3-35d76a327450.png)

**Comment by nevenz** [comment]
> If I have a search that includes exactly one b. clause, I find the notebook name displayed under each search result to be redundant.

I feel this can be said for more then a notebook. You could search for priority, specific state etc. and those are all displayed. They might not occupy as much space as notebook does, but I think it wouldn't be consistent to do this just for the book search. And doing it for possible search criteria would be mess.

**Comment by nevenz** [comment]
I also think it would be too easy to forget which notebook is used in search, especially if the query is long and `b` is at the end.
