### ISSUE TITLE
s.today includes node from yesterday

### ISSUE THREAD

**Issue by SanskritFritz** [orgzly/orgzly-android#296]
I have searched for existing issues that may be the same as or related to mine. 👼 ✔️ 
I'm submitting a **bug report** for version 1.6.2.

My notebook includes the following elements:
```
* Event A :calendar:
DEADLINE: <2018-02-14 Wed 12:30> SCHEDULED: <2018-02-14 Wed 09:30>
:PROPERTIES:
:CREATED:  [2018-02-04 Sun 22:00]
:END:

* Event B :calendar:
SCHEDULED: <2018-02-15 Thu 21:00 +1w>
:PROPERTIES:
:CREATED:  [2018-02-13 Tue 23:14]
:END:
```

Both elements are included into the search "s.today".

**Comment by nevenz** [comment]
You probably want `s.eq.today`.

Default operator for `s` is `le` (less or equal to). So you're actually doing `s.le.today`.

Check out http://www.orgzly.com/help#search for more.

**Comment by SanskritFritz** [comment]
Oh, thanks and sorry for the noise.
