### ISSUE TITLE
Too easy to delete a note and no way back

### ISSUE THREAD

**Issue by memeplex** [orgzly/orgzly-android#3]
Currently deleting a note is made very easy while offering no undo ability.

There are two ways out of this:

1. The easy one: ask for confirmation.
2. The hard one: implement an undo action or an archive mechanism.

It's true that dropbox keeps many past versions of the notebook but it will be convenient to recover from an accidental delete inside the app.

**Comment by nevenz** [comment]
You are referring to deleting from notes' list I assume? I agree - the same dialog as when deleting from the note itself should be displayed.

You can open a separate issue for undoing delete. Shouldn't be too hard (marking & unmarking note as deleted in db).
