### ISSUE TITLE
German Umlaute after Sync

### ISSUE THREAD

**Issue by mourningsun75** [orgzly/orgzly-android#30]
I have nothing changed on my smartphone or computer, so i think it is because the last update of orgzly. when i changed entries with orgzly and sync to file i have damage "german umlaute".

Good: Datei löschen
Now: Datei l\303\266schen

Please check this.

**Comment by nevenz** [comment]
Which sync method are you using, local directory or Dropbox?

**Comment by mourningsun75** [comment]
Local Directory.
In orgzly everything seems ok. When i open the  files with emacs i see the broken  umlaute

**Comment by mourningsun75** [comment]
hmm.... just tried it again with another file.... no problem.... don't know... perhaps it was a beta version meanwhile or a problem with my config. sorry.
