### ISSUE TITLE
Attempt to invoke virtual method on a null object reference

### ISSUE THREAD

**Issue by clasick** [orgzly/orgzly-android#300]
I have a local directory as a link to a new note. When I sync my note (to presumably save the new note to the local directory), I get an error saying 

`Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference`

The error just appears inside the note in the notebook view. 

> I have searched for existing issues that may be the same as or related to mine. 👼
> 
> I'm submitting a **bug report** for version 1.6.2.
>

**Comment by nevenz** [comment]
> The error just appears inside the note in the notebook view.

Inside the note? You mean app doesn't crash?

**Comment by clasick** [comment]
82@Sg2%L@*IoG4A^KFTB2Pc$zEGQId

**Comment by nevenz** [comment]
> I hope this image makes it clear.

Great, thanks.
