### ISSUE TITLE
sort not working with nested paranthesis

### ISSUE THREAD

**Issue by iexos** [orgzly/orgzly-android#304]
I have searched for existing issues that may be the same as or related to mine. 👼

I'm submitting a **bug report** for version 1.6.2 (fdroid).

Sorting does not work in the following search query:

`((i.todo s.no) or i.later) o.state`

It also does not work with:

`((i.todo) or i.later) o.state`

However it DOES work with:

`((i.todo or i.later)) o.state`

**Comment by nevenz** [comment]
Thanks, repeating parentheses were being converted to a single one when tokenizing, messing up query parsing later.
