### ISSUE TITLE
Build fails: cannot find symbol OrgRange.doParse(string)

### ISSUE THREAD

**Issue by adamfaryna** [orgzly/orgzly-android#306]
I'm submitting a **bug report** for version 1.6.2, version code 95.

OS X 10.10.4.

When trying to build which `./gradlew build` got:

> Task :app:compileFdroidDebugJavaWithJavac
/Users/devil/Development/gpg/orgzly-android/app/src/main/java/com/orgzly/android/provider/models/DbNote.java:201: error: cannot find symbol
        OrgRange range = OrgRange.doParse(value);
                                 ^
  symbol:   method doParse(String)
  location: class OrgRange
/Users/devil/Development/gpg/orgzly-android/app/src/main/java/com/orgzly/android/Shelf.java:954: error: cannot find symbol
                    OrgDateTime dbPropertyValue = OrgDateTime.doParse(dbPropValue);
                                                             ^
  symbol:   method doParse(String)
  location: class OrgDateTime
2 errors

**Comment by nevenz** [comment]
Thanks, it seems that `org-java` hasn't been deployed to the repository lately (I've been using `../org-java/` and forgetting to do it).  [It is now](https://oss.sonatype.org/content/repositories/snapshots/com/orgzly/org-java/1.2-SNAPSHOT/) - you might need to do `./gradlew build --refresh-dependencies` if you try this within next 24h.

**Comment by adamfaryna** [comment]
@nevenz thanks, works as a charm!
