### ISSUE TITLE
Properties stored as content somehow

### ISSUE THREAD

**Issue by dancruzsc** [orgzly/orgzly-android#309]
App Version: 1.6.2
Emacs version: 25.3.1 win10 x64
Org version: 8.2.10 (builtin)

Hello! 

Yesterday I was creating a habit on Emacs for one of my headings following [these instructions.](https://orgmode.org/manual/Tracking-your-habits.html)

In my Emacs, the `- State` lines are automatically inserted between `SCHEDULED` and `:PROPERTIES:`. The thing is, when i load the file from Dropbox to my app, the `- State` lines _and_ the `:PROPERTIES:` entries were stored on content field as plain text. 

I removed all the `- State` lines from the note on Emacs and sync again; on app, the properties were stored as expected;
Again, on Emacs, I put the `- State` lines after the `:PROPERTIES:` and i got the behaviour I first expected on app: properties as properties and the lines stored on the content field. 

I searched on documentation to check if this behavior is the default, or at least known, but I only found content about unsupported metadata.

I'm very noob on org and Emacs, i don't know if the `:PROPERTIES:`'s place must be before the content. Could someone confirm this information, please?

Thanks in advance.

**Comment by nevenz** [comment]
> I'm very noob on org and Emacs, i don't know if the :PROPERTIES:'s place must be before the content. Could someone confirm this information, please?

Yes, see "Version 8.3" on https://orgmode.org/Changes_old.html.

Orgzly relies on that so it thinks `- State` lines are starting the content.

**Comment by dancruzsc** [comment]
Oh. I totally forgot to check the org changelog/documentation.

Sorry for such a stupid question and thank you for the answer.
