### ISSUE TITLE
2nd notebook name in new beta?

### ISSUE THREAD

**Issue by keithcrone** [orgzly/orgzly-android#310]
I have searched for existing issues that may be the same as or related to mine. 👼
I'm submitting a **bug report** for version 1.6.3-beta.

It may not be a bug, but just in case...
Does the new notebook name in the note view do anything? It's not clickable so it seems redundant. Just wanted to check that was on purpose, maybe for a continued redesign you didn't get to, rather than a bug.

Thanks.

**Comment by nevenz** [comment]
> Just wanted to check that was on purpose, maybe for a continued redesign you didn't get to, rather than a bug.

Yes, it's temporary (since next version is long overdue), plan is to:

- Move note title to the toolbar
- Append path to the note (each ancestor) to notebook name, or add them below it
- Make notebook name and each note's ancestor a link
- Add UI (additional button probably) for refiling the note

**Comment by nevenz** [comment]
BTW, it's clickable when sharing to Orgzly - it replaces the large notebook button that was on the top.

**Comment by keithcrone** [comment]
Based on some of the other comments regarding the next couple of versions, you won't be getting to this any time soon, will you?

**Comment by nevenz** [comment]
> Based on some of the other comments regarding the next couple of versions, you won't be getting to this any time soon, will you?

I'll probably continue working on note fragment design changes, so I might squeeze in displaying ancestors and making them clickable, but no promises, I don't have a strict plan of next to-work-on items.

BTW, you might want to open an issue for jumping to the book instead of the note on link click, which you were mentioned as being very important to you. That should be trivial to add as an option (it's what that button in search results do, so the code already exists).

**Comment by keithcrone** [comment]
> BTW, you might want to open an issue for jumping to the book instead of
the note on link click, which you were mentioned as being very important to
you.


Nah. I was only looking for alternatives to Orgzly's non-standard
implementation of internal linking. If it worked like Org-mode, great. If
it worked like Workflowy or Dynalist, also great. But it has done neither
for the last six months and I can't really hold out, so don't make your
continued redesign a priority if you don't need to.

>

**Comment by nevenz** [comment]
Closing after #343 and #459.
