### ISSUE TITLE
Widget does not respect auto-sync

### ISSUE THREAD

**Issue by NJBS** [orgzly/orgzly-android#313]
I'm submitting a **feature request**.

I'd be nice if the widget respected your auto-sync settings; e.g when a task is added via the agenda widget it's auto-synced.

**Comment by nevenz** [comment]
I can't reproduce this with `v1.6.3-beta.2` - I get a note displayed in the widget and sync started. Which version are you using?

**Comment by NJBS** [comment]
I'm on `1.6.2` using Dropbox sync.

**Comment by nevenz** [comment]
> I'm on 1.6.2 using Dropbox sync.

Ah, auto-sync is only enabled for local repositories. (This is mentioned in the summary on Settings/Sync screen. Perhaps it should be made more clear.)

It is done to prevent hitting Dropbox API too often. It was too easy to exceed per user limits.

So yet to be done as part of #8.

**Comment by NJBS** [comment]
Ah, I see.

Thanks for the clarification!
