### ISSUE TITLE
Deleting linked remote notebook

### ISSUE THREAD

**Issue by karlicoss** [orgzly/orgzly-android#325]
I'm synchronising orgzly notebooks with a directory on my phone. I've observed that if you delete a notebook file form file manager, and then open orglzy, it's reconstrucing this notebook again, and it's appearing on filesystem. Right now I'm getting around it by removing the notebook from the app (and ticking in 'removel linked remote notebook), but it's not super convenient. Was that intended? Wonder if we can prompt user for notebook deletion when the remote notebook is deleted or something like that? 

(using orzly 1.6.5).

**Comment by nevenz** [comment]
It's #287.

**Comment by karlicoss** [comment]
oh, sorry, was pretty sure I had checked open issues first..
