### ISSUE TITLE
Draggable scroll bar in notebooks

### ISSUE THREAD

**Issue by omarabdelsalam** [orgzly/orgzly-android#328]
Scrolling down/up in a notebook or search result view that contains many many items is painful. It needs swiping up/down finger many many times till I reach what I want.
It will be really more efficient if the **scroll bar is draggable**.

-----
I have searched for existing issues that may be the same as or related to mine. 👼

I'm submitting a **feature request**.

**Comment by nevenz** [comment]
> It has been disabled for notebooks because of the folding buttons being too close.

It doesn't seem the scroll bar reacts to clicks (anymore?), only dragging of the thumb drawable, so this shouldn't be an issue now.

There's an issue with tiny thumb drawable with many entries: https://issuetracker.google.com/issues/64729576.

And this is enabled only for API levels 21 and greater.
