### ISSUE TITLE
Feature Request: Selectable font size for widget

### ISSUE THREAD

**Issue by tekstrong** [orgzly/orgzly-android#333]
It would be very beneficial to have an adjustable font size for the widget (just like is available within the app itself).

**Comment by tekstrong** [comment]
I can't express just how indispensable Orgzly has become for me - thank you for all your work!

**Comment by nevenz** [comment]
Only two sets of fixed sizes are available. More can be added if even smaller or larger font size is needed. Custom font size is not supported as it's hard to scale everything (like padding, margins, etc.) around arbitrary values to look good.
