### ISSUE TITLE
FR: Open outliner view from Agenda

### ISSUE THREAD

**Issue by Korogodin** [orgzly/orgzly-android#334]
I'm submitting a **feature request**.

The Agenda view contains a list of outliner items. If I tap on any item, I can modify this item. It's cool, but often I want to add/remove related tasks in the tree instead of modifying of the item (below or under)

So, FR: add possibility to open outliner view for the certain item from the agenda view, please

**Comment by nevenz** [comment]
> add possibility to open outliner view for the certain item from the agenda view,

This is already possible from the menu which is opened by swiping the note left.

There's a menu with different set of actions when you swipe the note right too BTW.

**Comment by Korogodin** [comment]
>  when you swipe the note right too BTW.
Wow, it works! It will save huge amount of my time, thank you! FR may be closed.
