### ISSUE TITLE
Orgzly app gets crashed.

### ISSUE THREAD

**Issue by Sammaz2** [orgzly/orgzly-android#335]
### Actual behavior
I opened the orgzly opensource android app and then I added a note. After that I went to the settings and then clicked on the sync option. After that I clicked on org file format option and then on tags indentation. After that I increased the tags coloum and indentation per level. After that I got back to the notebooks. And then I long pressed on a note. And clicked on export option. Suddenly the app gets crashed.

### How to reproduce

* First you need to download the app from fdroid and then install it. After that open the app.

* Click on the plus icon and add a notebook.

* After that click on the options present on the top left corner and then click on the settings option.

* Then after that click on the sync option. Open the org file format.

* Click on the tags indentation option.

* After that click on the tags coloum and then put some numbers.

* After that click on the indentation per level option. There also put some numbers.

* Get back to the main screen.

* Long press on any note. Click on export option.
Suddenly the app will get crashed.

https://youtu.be/tHuhcXHWXLg

* Browser: Orgzly

* Version:1.6.6

* Operating system:7.1.2

* Device model: Redmi 4.

**Comment by nevenz** [comment]
Thanks for the detailed report.

> After that click on the tags coloum and then put some numbers.
> After that click on the indentation per level option. There also put some numbers.

Which numbers did you enter? I can reproduce this only with large numbers, which will be fixed.
