### ISSUE TITLE
Refile Targets

### ISSUE THREAD

**Issue by falematte** [orgzly/orgzly-android#339]
I have searched for existing issues that may be the same as or related to mine. 👼

I'm submitting a **feature request**.

I really love the new "refile" feature. I think it will be a huge improvement to let the user choose some headers (or sub headers) as additional targets...

**Comment by falematte** [comment]
Is this pushed to the version of the app on the play store? I still cannot refile to headers in a file.

**Comment by nevenz** [comment]
> Is this pushed to the version of the app on the play store? I still cannot refile to headers in a file.

@falematte No, it's in v1.7.4 (next version).

**Comment by kshenoy** [comment]
Hi, this might be a dumb question, but how do I refile stuff? I looked at the [doc](www.orgzly.com/help) but couldn't find anything related to refile there. Is there a more comprehensive documentation?

**Comment by nevenz** [comment]
@kshenoy,

> how do I refile stuff

You can either:
* Select a note by long-clicking it -> Open the overflow menu (⋮) -> Click Refile
* Open the left quick-menu (swipe note left) -> Click the last icon

> Is there a more comprehensive documentation?

There's "Getting Started with Orgzly" notebook, but those left and right "quick-menus" definitely need to be documented better. A lot of users are not aware of them.

**Comment by kshenoy** [comment]
Thanks, found it. Also, thanks for all your work on this :)
