### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by nevenz** [orgzly/orgzly-android#34]

**Comment by Grahack** [comment]
Hi (again), I once worked on Android apps. Is it a matter of a new `strings.xml` file? Would you create it for me in a branch with English content? Then I could PR.
Or maybe you want to set up some kind of Transifex or Translatewiki?

**Comment by nevenz** [comment]
Yes, but it's a matter of creating a new file - `res/values-fr/strings.xml`. So you can fork the project and create PR that would do that.

Check out the current [Chinese translation](https://github.com/orgzly/orgzly-android/blob/master/app/src/main/res/values-zh-rCN/strings.xml) as an example.

**Comment by nevenz** [comment]
BTW, I was eyeing https://weblate.org. If you think that would be better, I can look into it.

**Comment by nevenz** [comment]
Set up https://crowdin.com/project/orgzly
