### ISSUE TITLE
Show inherited tags in searches and widgets

### ISSUE THREAD

**Issue by mrDSide** [orgzly/orgzly-android#340]
Version: 1.6.6(fdroid)
No inherited tags in widgets. And not in every note in search (in app). I'd like to make pull request if somebody help with code (where to start).

**Comment by nevenz** [comment]
Good catch, but I only see the issue in the widget, not search results in the app.

Check where [title is generated](https://github.com/orgzly/orgzly-android/blob/master/app/src/main/java/com/orgzly/android/ui/util/TitleGenerator.java#L88). It looks like inherited tags [are not loaded](https://github.com/orgzly/orgzly-android/blob/master/app/src/main/java/com/orgzly/android/provider/clients/NotesClient.java#L170) for widget. Thanks!
