### ISSUE TITLE
Getting past a link

### ISSUE THREAD

**Issue by RonnyD123** [orgzly/orgzly-android#343]
If I follow a UUID link in Org-mode, i go to a heading in the outline. In Orgzly I seem to go to a single note. Can I break out of that somehow to the outline? A button I'm missing or something?

**Comment by nevenz** [comment]
Not yet, notebook below title will become clickable and will return to notebook with the note in view.

Optionally, behaviour could be changed with new Settings preference, to open the notebook instead (suggested in the past).
