### ISSUE TITLE
Refresh the widget manually feature

### ISSUE THREAD

**Issue by NiceFeather** [orgzly/orgzly-android#346]
Currently the widget is need refresh manually through switching the searched lists, A swipe Up/Down gesture will can get any recent update quickly, could we do this?

**Comment by nevenz** [comment]
Refresh for what exactly? Time changing or notes?

Widget is refreshed on every modification, as well as every hour (which you can change to be every 5min).

**Comment by NiceFeather** [comment]
Obviously, Although widget is refreshed automatically, I think that it is a necessary worth adding a manually refresh function via a gesture or built-in button/menu. thanks!

**Comment by nevenz** [comment]
> I think that it is a necessary worth adding a manually refresh function via a gesture or built-in button/menu

Yes, but why?

Is there an issue you're seeing? Is it not updated when you expect? Is 5 min too long?

**Comment by NiceFeather** [comment]
I got this answer! so sorry I have been using this widget within a popup widget container app named 'Popup Widget', it seems that UI didn't sync immediately with any update of notes, Also I did a test placed straight a widget on the desktop, all is perfect.
