### ISSUE TITLE
New logo proposal for Orgzly app

### ISSUE THREAD

**Issue by ammarraisafti** [orgzly/orgzly-android#347]
Hi admin, I want to offer a simple new logo design for Orgzly application. This logo is my special design for you. If you are willing to accept it, you simply reply to this proposal. I will send you a new logo of this file. And if you want other color variations or some additional icon in it. you can tell me. I will update it soon

![logo](https://user-images.githubusercontent.com/37721970/41492277-467197dc-7128-11e8-8a4f-51a7803ba4a9.png)

**Comment by nevenz** [comment]
Thanks a lot, but as I mentioned [here](https://github.com/orgzly/orgzly-android/issues/329#issuecomment-389772213), I do prefer the current logo and want to keep it as simple as possible.

**Comment by ammarraisafti** [comment]
Do you allow me to do that, I will design a very simple logo for you. Maybe
you will be interested. Give me some days, I'll send you a very simple
logo. thank you

Pada tanggal Min, 17 Jun 2018 21:52, Neven <notifications@github.com>
menulis:

**Comment by nevenz** [comment]
> Do you allow me to do that, I will design a very simple logo for you.

I don't think it can get any simpler then it is now 😄, keeping the current shape which is used from the beginning. I happy with the current logo for now, thanks again!
