### ISSUE TITLE
Broken UI actions after settings

### ISSUE THREAD

**Issue by fairplay** [orgzly/orgzly-android#348]
I'm submitting a **bug report** for version 1.6.7
After visiting settings and changing something (still not sure if it is a necessary condition, but I could reproduce the behaviour clicking "Force UTF-8" setting), then returning to the notebook via back key I've encountered the next problems:
- Back button is not working anymore
- Drawer can be displayed, but "Notebooks", "Settings" e.t.c. actions are not working anymore

**Comment by nevenz** [comment]
I've seen it once too few versions ago, but haven't been able to reproduce it since. I suspect it's due to activity restart after leaving Settings.

If someone can reliably reproduce it, let me know.

**Comment by aancel** [comment]
I am able to reproduce this issue with my setup in PR: #389 
We've managed to identify a potential cause in this comment: https://github.com/orgzly/orgzly-android/pull/389#issuecomment-428735893

@nevenz I did try the solution you proposed in https://github.com/orgzly/orgzly-android/pull/389#issuecomment-428737081, but this does not solve the issue. I still end up having 8 actions available instead of 14.
Could it be that a wrong instance of LocalBroadcastManager is updated instead ?

**Comment by nevenz** [comment]
> Could it be that a wrong instance of LocalBroadcastManager is updated instead ?

No, it's a singleton.

Might be the issue of restarting the activity from `onResume` [here](https://github.com/orgzly/orgzly-android/blob/master/app/src/main/java/com/orgzly/android/ui/CommonActivity.kt#L216) maybe. You could try calling that from `Handler().postDelayed`, just to see what happens.

Also, I'd look for logs (or add some) and monitor `onResumeFragments|onReceive|onPause|onBookClicked` for example. When I return from settings, I see:
```
10-11 00:14:58.414 21865-21865/com.orgzly D/com.orgzly.android.ui.MainActivity: 2#main: onResumeFragments
10-11 00:14:58.493 21865-21865/com.orgzly D/com.orgzly.android.ui.MainActivity: 2#main: onPause
10-11 00:14:58.494 21865-21865/com.orgzly D/com.orgzly.android.ui.fragments.BookFragment: 2#main: onPause
10-11 00:14:58.575 21865-21865/com.orgzly D/com.orgzly.android.ui.MainActivity: 2#main: onResumeFragments
```

If you see `onPause` after `onResumeFragments`, it's a problem.

**Comment by aancel** [comment]
I've first tried the logs solution.
When starting the app, I go through onResume and onResumeFragments.
Then I go in the settings, it triggers the onPause method.

If I immediately go back to the notebooks section, it triggers onResume then onResumeFragments.
If I go in a setting menu without toggling anything, then go back to the notebooks section, it triggers onResume then onResumeFragments.
But if I toggle a setting, then go back to the notebooks section, it triggers: onResume, onResumeFragments, onPause, onResume, onResumeFragments and onPause.

Each call is repeated.

**Comment by aancel** [comment]
Commenting out this `if` section https://github.com/orgzly/orgzly-android/blob/18eeb46c8db2cc66b0e8c03446a2e8cfac117759/app/src/main/java/com/orgzly/android/ui/CommonActivity.kt#L213
seems to fix the issue and go back to a traditional: onResume then onResumeFragments.

But I don't see the bigger picture and you must have done this for a reason. There might be issues with the preferences that I don't see.
Maybe this if section shouldn't be done in all activities inheriting from CommonActivity ?

**Comment by nevenz** [comment]
> But if I toggle a setting, then go back to the notebooks section, it triggers: onResume, onResumeFragments, onPause, onResume, onResumeFragments and onPause, then UI is blocked.

Seeing `onPause` last is pretty weird. But definitely the cause of this issue. Recreating the activity from `onResume` is most likely the cause.

Try replacing `recreate()` with commented-out:
```
// Handler().post(this@CommonActivity::recreate)
```

Also you can try replacing it with:
```
finish()
startActivity(intent)
```

You could also try moving `super.onResume()` below the `if` block and see what happens.

I'd have to check Android code to actually understand what's happening, these are just 

> But I don't see the bigger picture and you must have done this for a reason. There might be issues with the preferences that I don't see.

Changing some preferences require activity restart. Such as color scheme, font size or "Use English language". Other need loaders restarted like for example changing the sort order of notebooks.

**Comment by aancel** [comment]
Following your comment:

> Try replacing `recreate()` with commented-out:
> 
> ```
> // Handler().post(this@CommonActivity::recreate)
> ```

This leads to the following sequence on returning to the notebooks (after having changed a setting): onResume, onResumeFragments, onPause, onResume then onResumeFragments. So this solves the issue.

> Also you can try replacing it with:
> 
> ```
> finish()
> startActivity(intent)
> ```

This also solves the issue with the following sequence: onResume, onResumeFragments, onPause, onResume then onResumeFragments.

> You could also try moving `super.onResume()` below the `if` block and see what happens

This does not seem to fix the issue. I still get onResume, onResumeFragments, onPause, onResume, onResumeFragments and onPause and the UI is blocked.

So this leaves 2 candidates for a fix. 
If you prefer going through a PR, I probably won't have time until tomorrow on my side.
