### ISSUE TITLE
"New note" form called from widget on blocked screen does not call Android keyboard

### ISSUE THREAD

**Issue by sokolgeo** [orgzly/orgzly-android#350]
I found no report on this behavior, so here is bug report:

I use Orgzly 1.6.6 built by fdroid: https://f-droid.org/en/packages/com.orgzly/
My OS is Android 6.0.1 built by replicant project: https://redmine.replicant.us/projects/replicant/wiki/GalaxyTab270P31xx
I use pin code screen lock. I enabled "randomize location of numbers on pin keyboard".
I have Orgzly "New note. Tap create new note" widget on my locked screen.

When I click I am asked for my Android unlock PIN code and then is taken to Orzly "new note" form.
The cursor is in 'Title' field, Android keyboard does not pop up. So I have to click on 'Title' field to get Android keyboard and actually type then name of new issue.

Can this please be fixed and Android keyboard just popup when 'new note' form is called from locked screen through PIN entering? Like it appears when you call "New note" from notification drawer on unlocked home screen?

Thank you

**Comment by nevenz** [comment]
For me it doesn't even appear when phone is unlocked, thanks.
