### ISSUE TITLE
Failed to receive access code to Dropbox API from Fennec and Jello browsers

### ISSUE THREAD

**Issue by hyiltiz** [orgzly/orgzly-android#365]
In Orgzly (1.6.8), when the system default browser is Fennec (a FOSS build of Firefox) or Jello (default in some ROMs) browsers, clicking "Link to Dropbox" the dropbox login page with the specified browser, and after logging in and clicking "Allow" in the next page, the secret key is simply discarded (Fennec) or used as a search string and performed a search within the browser using the default search engine (Jello), instead of sending that string back to Orgzly.

Using Firefox Focus instead worked. I recall Chrome worked as well. So this really is not orgzly's bug, rather the browsers are doing something unexpected. If it is even possible in Orgzly to detect what is the default browser or detect failure to link several times, then it might make sense to prompt the user that some browser behaves badly and suggest what to do.

**Comment by nevenz** [comment]
Might be related to #22.

I can't reproduce this with the latest version of Fennec, so there's probably more involved.

**Comment by nevenz** [comment]
> I was using Fennec 61.0 from F-Droid

I tested with this version, by downloading APK from F-Droid and installing it on emulator.

What about sharing page URL from the browser for example? Does it work ok?

**Comment by hyiltiz** [comment]
Oh, that didn't work either! I tried to Share a page URL to Google Translate, but what actually happened is "Page saved in Fennec" "Open in Fennec" overlay. Then Google Translate web page is opened instead of the local app, and the url is put inside the translation bar. I enabled the overlay feature for it, so it will open links as new tabs in the background.  Might have interaction there.

**Comment by hyiltiz** [comment]
Agreed. This is definitely not unexpected behavior on Orgzly's part. If anything, you might want to notify the user to disable that feature temporarily or use some other browser.
