### ISSUE TITLE
simplify "edit content"

### ISSUE THREAD

**Issue by voxspox** [orgzly/orgzly-android#374]
Currently in a note the content can be edited by pressing on "edit content". After that I have to scroll the view a bit up to see more content which was overlapped by the keyboard. I want to suggest to make this action more comfortable

- press on the content starts editing (instead "button" above)
- scroll (note) view up such that the content starts at the top of the screen

**Comment by memeplex** [comment]
Maybe the second point is not as trivial to implement but the first one surely is and would make a difference. Can we split this issue?
