### ISSUE TITLE
Orgzly crashes when clicking on a title created as a checkbox

### ISSUE THREAD

**Issue by arachide** [orgzly/orgzly-android#375]
I don't know if it wasn't intended to work like that, but when I try to create a title as a checkbox, by starting it with "- [ ] whatever", once I try to click on the checkbox, from the main view, it crashes (it doesn't if I click beside it to edit the note)

Maybe you could try to add an option to add checkboxes as main threads, by adding, for example, an option in the "State" menu, like 
TODO
DONE
CHECKBOX

It would make it easier to create subtrees of checkboxes that automatically reflect their result to the parent checkbox, that is in this case in the title of the note. The same could be applied for subtrees of checkboxes below a TODO thread, that automatically reflects to "DONE" once all checkboxes are completed

**Comment by nevenz** [comment]
This has been fixed in 452c05c971bfcc548e42701b8aeb52ba02c99c6b. They are not supposed to be supported in title.
