### ISSUE TITLE
Wrong "Getting started with orgzly" - Spanish version 

### ISSUE THREAD

**Issue by Ypot** [orgzly/orgzly-android#380]
I think this is wrong:
![screenshot_20180822-111843 2](https://user-images.githubusercontent.com/30699014/44455030-566b9480-a5fd-11e8-9bc8-cc3d410bbfd1.png)

I tried to download the English version, but it didn't work (I chose English version in the settings).

**Comment by nevenz** [comment]
Yeah, spacing in https://crowdin.com/translate/orgzly/8/en-es looks wrong.

For importing the English version (from Settings / App), you'd have to switch the language on your device.  Ideally "Use English language" option should be honored.

**Comment by Ypot** [comment]
Ok
Corrected the translation.

**Comment by Ypot** [comment]
Original English is ok?

"Note can have tags :tag1:tag2: "

**Comment by nevenz** [comment]
> Corrected the translation

Great, thanks!
