### ISSUE TITLE
List widget not available

### ISSUE THREAD

**Issue by ramos** [orgzly/orgzly-android#383]
I'm submitting a **bug report** for version 1.6.9

When adding a widget only a size 1x1 appears as option. In the widget only the orgzly icon appears.

**Comment by nevenz** [comment]
What widget are you referring to? There is "Orgzly notebook", which looks like you describe, but that's just a link to a notebook within Orgzly. There is also "Orgzly notes", which displays results of a saved search.

There's no way to select a notebook and display its content in a widget yet. Current "Orgzly notes" needs to be improved to allow selecting notebooks too. Is that what you were expecting? I don't think there is an issue for that. You can open one, or rename this one perhaps.

You could create a saved search for `b.notebook-name` BTW, and display that, but it's not ideal as you won't get indentation etc.

**Comment by ramos** [comment]
Hi Nevenz,

As you describe it, the problem seems to be that I obly have the "orgzly notebook" in the widgets section. There is no "orgzly notes" for me.

Many thanks for your help,

A.

**Comment by nevenz** [comment]
Hmm that's strange. Do you know if it was there with v1.6.8? Did you install app on external storage perhaps? Also, what device is this and are you using some custom launcher?

**Comment by nevenz** [comment]
Which LineageOS version is this? I tried 15.1 (with Android 8.1.0), but I see both widgets:

![widgets](https://user-images.githubusercontent.com/10671476/45378248-3710c780-b5fd-11e8-9613-cdef4d9fd55e.png)

It wasn't possible to install app on SD card on 1.6.8 (http://www.orgzly.com/changelog#2f7114a), so that's not it then.

There could be some useful clues in the log, but you'd need `adb` installed for that.

**Comment by nevenz** [comment]
Is this still an issue?

**Comment by dustinpaluch** [comment]
I have this issue on a stock Moto G (3rd gen) with Android 6.0, Orgzly 1.7.5.

I only have the "New note 1 x 1" and "Notebook 1 x 1" widgets available.

**Comment by nevenz** [comment]
Hmm, weird one, I'm not sure what the problem is.

I could remove min/max values from [widget's metadata](https://github.com/orgzly/orgzly-android/blob/683d482c63021a12fccbbef5fe683cdd2c710ad2/app/src/main/res/xml/list_widget_info.xml) and generate APK is someone can try it out.

**Comment by dustinpaluch** [comment]
I'd try it if it doesn't mess with my existing orgzly/data.

**Comment by ramos** [comment]
I think that the issue is related with the fact that you:

1) Have a SD card

2) Orgzly get's installed in the SD card.

After I removed my sd card and reinstalled orgzly, the widget appeared again.

**Comment by dustinpaluch** [comment]
Correct! I have an SD card configured as `internal storage`.

http://motorola-global-en-roe.custhelp.com/app/answers/detail/a_id/105644/~/using-an-sd-card---moto-g-3rd-generation

My phone decided to install Orgzly on the SD card. I went into Settings > Storage & USB > SD Card > Apps > Orgzly and clicked "Change" under "Storage used" to move Orgzly and its data to internal storage. Now I see the orgzly search widget.

**Comment by nevenz** [comment]
Cool, I think this is [Applications that should NOT install on external storage]( https://developer.android.com/guide/topics/data/install-location#ShouldNot):

> **App Widgets**
> Your App Widget will be removed from the home screen. When external storage is remounted, your App Widget will not be available for the user to select until the system resets the home application (usually not until a system reboot).
