### ISSUE TITLE
Plus button on widget should default to the notebook used by the widget

### ISSUE THREAD

**Issue by rieje** [orgzly/orgzly-android#387]
I'm submitting a **feature request**.

The plus button on widget should default to the notebook used by the widget when the search expression `b` for "notebook" is used. For example, I have two widgets: one with the query `b.todo` and another with `b.PNW`. When pressing the plus button for both widgets, the state defaults to the "PNW" notebook for whatever reason (seems like it defaults to the most recent notebook created?). Instead, it should default to the respective notebook used (for the former, default to the state "todo" and for the latter, state "PNW".

This makes more sense.

**Comment by nevenz** [comment]
It's #154.
