### ISSUE TITLE
Note disappears when changing its level

### ISSUE THREAD

**Issue by robert-samal** [orgzly/orgzly-android#390]
I'm submitting a **bug report** for version 1.6.9. 

Situation: I use Orgzly for an org-file produced using emacs -- one which starts with an item of second level. I long-press this note and try to change it's level to the first. I would expect it to behave as the org-mode in emacs, that is to change its level to first. Instead, the note simply disappears. 

Minimal file (notebook) where this occurs has the following two lines

```
** Second level with no predecessor
* Normal first level ...
```                          

I admit it is an edge case (and one cannot create such bad note in Orgzly itself). On the other hand, losing your data is not nice. And it happened to me accidentally while trying to learn how to use the app, now while trying to break it :-)

**Comment by nevenz** [comment]
I remember testing cases like that long time ago, but apparently not enough. And there are no actual tests for them. Thanks!
