### ISSUE TITLE
Refile multiple items

### ISSUE THREAD

**Issue by adbenitez** [orgzly/orgzly-android#391]
Refile of multiple notes aren't currently supported, so users have to refile several items manually one by one.

I have searched for existing issues that may be the same as or related to mine. 👼

I'm submitting a **feature request**.

**Comment by nevenz** [comment]
It's #67 + #339 I guess.

**Comment by adbenitez** [comment]
Yeah! I realized it, after reading more carefully the issues, that is why I closed it, thanks!
