### ISSUE TITLE
Hide TODOs which aren't scheduled yet

### ISSUE THREAD

**Issue by cryptosimon** [orgzly/orgzly-android#396]
Is this possible? It is not helpful that orgzly tells me to water my plants every day if I want to water them once a week and it just clutters up my widget.

**Comment by nevenz** [comment]
It should be. How does your note's time look like? What is its repeater? Is it something like `.+1w`?

**Comment by cryptosimon** [comment]
@nevenz So in detail I have an item with state TODO and schedule time repeater of ++1w on Sunday evening at 9. When I mark this item as DONE it will switch back to TODO but with a new scheduled time one week later. That part works fine. What bothers me is that I can't really go ahead and water the plants again already on Monday, so it would be great if the agenda for Monday didn't display this as a TODO.

**Comment by nevenz** [comment]
What search query are you using? You are using `ad.N`, right?

**Comment by cryptosimon** [comment]
I had not. That solves it! Thank you!
