### ISSUE TITLE
orgzly sync removes executable permission from non-org files in the local repository

### ISSUE THREAD

**Issue by neiljerram** [orgzly/orgzly-android#401]
I have searched for existing issues that may be the same as or related to mine. 👼

I'm submitting a **bug report** for version 1.6.9.

My setup involves keeping lots of Org files and other things - config, scripts etc. - in a Git repo on bitbucket.  On my laptops I push/pull between local clones and bitbucket.  On my phone I use Termux to push/pull between bitbucket and a git clone on the phone; then I tell Orgzly to treat the git clone on the phone as its local repository.

Some of my scripts are executable and so have 755 permissions.  After an Orgzly sync, those permissions have changed to 644.  (Even though this is on files that Orgzly doesn't display at all, because they aren't Org files.)

(Things then get worse because my git machinery interprets that as an intended change and pushes the 644 permissions to bitbucket.  Then when my laptops pick that up, things stop working :smile: )

**Comment by neiljerram** [comment]
However, after a few minutes further investigation, it turns out there is a very easy workaround: in the repository on the phone, `git config core.fileMode false`.

**Comment by nevenz** [comment]
> Some of my scripts are executable and so have 755 permissions. After an Orgzly sync, those permissions have changed to 644. (Even though this is on files that Orgzly doesn't display at all, because they aren't Org files.)

Hmm Orgzly doesn't touch files unless they end in `.org` or `.org.txt`. Are you sure this isn't just a filesystem issue?

**Comment by neiljerram** [comment]
Yes, pretty sure.

I ran my push/pull script in Termux on the phone, then checked the file permissions: still 755.

Then I switched to Orgzly and did a sync, switched back to Termux and checked the file permissions again: 644.

Still, I could check again to really make sure...

**Comment by neiljerram** [comment]
OK, maybe you're right.  I just tried this:
```
$ touch fish
$ chmod 755 fish
$ ls -l fish
-rw-rw----     1 root       everybod             0 Oct 16 18:32 fish
```
Perhaps I was confused before by some git cleverness masking the problem.
