### ISSUE TITLE
[Auto-sync (experimental)] Option "Sync after creating note" disregarded when creating a "QICK NOTE" via pull down menu

### ISSUE THREAD

**Issue by schmendrik** [orgzly/orgzly-android#405]
Hi, 

as the title says, when I create a note via the Quick Note in the drop down menu, it does not sync to the local repository. I'm talking about this Quick Note here: 

<img width="283" alt="bug" src="https://user-images.githubusercontent.com/15148632/47260682-8251ac00-d4c0-11e8-8801-193bb072a671.PNG">

After finishing writing the note and tapping on that (Send) arrow button, it does not sync. 

I am using Android 8.0.0 on an LG V20.

**Comment by nevenz** [comment]
Thanks! Also fixed missing scheduled time (if configured to be added for new notes).
