### ISSUE TITLE
Reset to notebook overview after (re-)opening app

### ISSUE THREAD

**Issue by heinzelotto** [orgzly/orgzly-android#410]
I'm submitting a **bug report** for version 1.6.10.

When opening orgzly, also after switching to another app and back to orgzly, it opens the notebook overview. This happens even when you were editing a note at the time of switching apps. When switching back, the progress is then lost.

I liked the behaviour of orgzly returning to the state where you left it after reopening the app. This original behaviour let orgzly integrate nicely into a multi-app workflow.

**Comment by nevenz** [comment]
Did you start to notice this in v1.6.10, not before? I can't reproduce it, activity should be kept and resumed. Do you get anything similar with some other apps? Is it possible that the system is killing the activity due to low memory?

**Comment by heinzelotto** [comment]
Thank you for your response. After experimenting it suddenly started working as expected. Experimenting more showed the following likely cause that I was able to reproduce:

This behaviour happens during the first run of the app after installing (or after installing the update, as in my case). Stopping (not just putting it to the background) and reopening the app once causes this behaviour to disappear in the future.

Description of the erroneous behaviour:
1. Open app for the first time after installing (e. g. from google play).
2. start creating note in the Getting Started notebook, or do anything that leaves the notebook overview.
3. Press home button to move the app to background.
4. Use the app icon in app drawer to reopen the app. (important; using the app overview screen to switch back works correctly).
5. App now shows Notebook overview again.

I am glad it is only a minor problem that is easily worked around (even though it is mysterious)! The phone is running stock Android O.

**Comment by nevenz** [comment]
Thanks for a detailed report.

It seems to be a known issue: https://issuetracker.google.com/issues/64108432

Found from https://stackoverflow.com/q/17000097.

**Comment by nevenz** [comment]
Nothing we can do, but it looks like it's finally fixed.
