### ISSUE TITLE
org-tags-column doesn't count full-width chars as 2

### ISSUE THREAD

**Issue by Ekleog** [orgzly/orgzly-android#411]
Hello,

When using Orgzly's `org-tags-column` set to `-77` (to emulate default org-mode behavior), I noticed a discrepancy in the way the tags were indented (thank you gitting my org-mode files and noticing all diffs :p)

Basically, emacs' org-mode counts full-width chars (eg. CJK chars like 漢字) as 2-chars-wide, while Orgzly appears to count them as only 1-char-wide.

I'm not sure whether this should be opened here or to org-java, but it looks like this bug went out too fast anyway and so it is open here now. Feel free to move it there if it belongs to there :)

Anyway, thank you for Orgzly, I'm only a day in using it and it's really great!

**Comment by nevenz** [comment]
Thanks!
