### ISSUE TITLE
Support `not` modifier for `s`

### ISSUE THREAD

**Issue by Ekleog** [orgzly/orgzly-android#412]
Trying to not display todo items that are scheduled for later than now (but to do display todo items that are not scheduled at all), I came upon what appears to me as a limitation of the search functionality: `.s.gt.today` isn't supported.

Is there a reason for this? An alternative wording would be `(.s or s.le.today)`, but `.s` for “not scheduled at all” appears not to be supported either.

Would it be possible to support this syntax?

**Comment by nevenz** [comment]
There's:

> PERIOD can be none or no which matches notes without the property.

So it would be `s.le.now or s.no`.

**Comment by Ekleog** [comment]
Oh indeed I didn't find it in the manual. Can I suggest moving the sentence up to go with `PERIOD is in the format of OP.TIME `, something like `PERIOD is either in the format OP.TIME, or is none or no, which matches notes without the property`? I got tricked by the statement that it had to be `OP.TIME` and didn't read any further :)

Thank you!
