### ISSUE TITLE
Suggestion: Multi-line saved search query field

### ISSUE THREAD

**Issue by Ekleog** [orgzly/orgzly-android#413]
My current search for the “work” agenda looks like this:
```
(s.le.today or (s.no d.le.2m)) .it.done (t.@WORK or t.@OTHER or (t.@ANYWHERE (t.PHONE or .t.COMPUTER))) o.pri o.dead o.sched
```

It's getting really hard to edit and fix when I note an issue, especially on a phone (eg. recently not noticing I missed the items tagged both `COMPUTER` and `PHONE`).

I think it'd be great to just have it be a multi-line text field that I could arrange however I want. (well, ideally the negation dot would also be possible to apply to parenthesis to make reasoning about the query easier, but I guess that's a separate issue that'd be much harder to change)

What do you think about this? :)

Thank you again for this great app!
Leo

**Comment by nevenz** [comment]
Sounds very useful, thanks.
