### ISSUE TITLE
Is it possible to link a note and access its subnotes?

### ISSUE THREAD

**Issue by Ypot** [orgzly/orgzly-android#421]
If not possible, here my feature request through an example:

1 Ebook title
 1.1 note 1
 1.2 note 2

2 Personal essay
 2.1 
 2.2 link to "1 Ebook title" ;(I would like to click on this link and to be able to read the 1.1 and 1.2 notes. Usually I go to an empty note with just the title of the book, and no shortcuts to its contents)

**Comment by nevenz** [comment]
Displaying descendants (as well as ancestors) in note view is planned.

Also, a new option could be added to open a notebook and center on the note instead.

**Comment by Ypot** [comment]
> Displaying descendants (as well as ancestors) in note view is planned.
> 
> Also, a new option could be added to open a notebook and center on the note instead.
Yes, an option like the one we find when using the search inside the notes would be helpful too.

**Comment by nevenz** [comment]
>> Also, a new option could be added to open a notebook and center on the note instead.

> Yes, an option like the one we find when using the search inside the notes would be helpful too.

This was added in v1.7.7 (Settings / Notes & Notesbooks / Link target).
