### ISSUE TITLE
Large Orgzly widget not available to add to home screen

### ISSUE THREAD

**Issue by seylerius** [orgzly/orgzly-android#422]
I have searched for existing issues that may be the same as or related to mine. 👼

I'm submitting a **bug report** for version `1.6.12`. I am using LineageOS version `15.1-20181201-NIGHTLY-klte`, Android version `8.1.0`. I have tested this with both Trebuchet and Nova Launcher. 

When I attempt to add the large list-view widget to my home screen, it is not listed in the selection of available widgets. This is what's listed:

![screenshot_20181207-104326_nova_launcher](https://user-images.githubusercontent.com/1145981/49666158-c40cc680-fa1c-11e8-8e73-6d66aa86be80.png)

I would very much like to use this widget, and have used it in the past on different phones. Please advise me of any tests I can do to identify why it's not available. 

Thanks.

**Comment by nevenz** [comment]
Is this #383? Looks like something LineageOS-related?

**Comment by seylerius** [comment]
Yep, that looks right. I'll dig in the `adb` log, then. Thanks! I'll post here (or in #383 if you'd prefer) with my findings.

**Comment by nevenz** [comment]
Thanks, let's move it to #383 then, I'll close this as a duplicate.
