### ISSUE TITLE
Unpredictable behaviour when switching timezones

### ISSUE THREAD

**Issue by iexos** [orgzly/orgzly-android#426]
Hi,

When switching time zones, recurring notes with daytime set seem to be behaving inconsistent.

I did not find out the pattern, but one entry with ++12h for example changed from 20:00 to 19:00 when traveling from +1 to +0. But then when traveling back, it stayed at 19:00. In the time picker menu it seems to be calculating wrong, selecting 20:00 to correct it yields 19:00 in the note. I had to select 21:00 to get 20:00 in the note.

**Comment by iexos** [comment]
Update: now it seems my daily tasks are jumping forward one hour every day, even though i do not change my timezone

**Comment by nevenz** [comment]
> now it seems my daily tasks are jumping forward one hour every day, even though i do not change my timezone

I've seen this too, I'll take a look for the next version.
