### ISSUE TITLE
%2F in repository path misinterpreted as /

### ISSUE THREAD

**Issue by fengshaun** [orgzly/orgzly-android#431]
I have searched for existing issues that may be the same as or related to mine. 👼

I'm submitting a **bug report** for version 1.6.12.

When setting a repository to a path that has %2F in it, orgzly incorrectly interprets it as the forward slash character "/" which leads to the error "No such file or directory". This case is evident when trying to sync orgzly with nextcloud local files.

Workaround: replace %2F with %252F

**Comment by nevenz** [comment]
Do you have an example of the path you're adding?

Are you entering it manually or choosing it from the browser?

See if https://github.com/orgzly/orgzly-android/issues/28#issuecomment-436553465 helps.

**Comment by fengshaun** [comment]
`file:/storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/user@domain%2Fserverpath/path/to/subdir` where nextcloud is located at domain/serverpath. Here, `%2F` is replaced by `/`, creating `Android/media/com.nextcloud.client/nextcloud/user@domain/serverpath/path/to/subdir` directory which is not where nextcloud places its files.

This doesn't happen when selecting the directory with file browser.

**Comment by nevenz** [comment]
Ah, so the thing is that the input is actually a URI.  It's not a "file:" followed by a path. So whatever you enter there is considered URL-encoded.

For example, it can also be `content://com.android.externalstorage.documents/tree/primary...`, as on devices with Lollipop or later, DocumentsProvider is used.

I didn't want to add another repository type to separate the two, as it would probably have made most users confused.

So the only "fix" I see is adding another field for a directory.

**Comment by fengshaun** [comment]
That makes sense. I don't think the added complexity of the "fix" is worth it at this point. Thanks for responding so rapidly and thanks for orgzly!
