### ISSUE TITLE
Question: How to activated CREATED property in note ?

### ISSUE THREAD

**Issue by azzamsa** [orgzly/orgzly-android#432]
I have searched for existing issues that may be the same as or related to mine. 👼

I've searched it in setting, but I couldn't find.  

Since manual timestamp still waiting to be implemented, I want to activate CREATED properties with corresponding time automatically each time I create note

Thanks for orgzly :)

**Comment by nevenz** [comment]
See Settings / Sync / Notebook files. Property will be added when note is *saved* (not while still being edited).

**Comment by azzamsa** [comment]
> Property will be added when note is saved (not while still being edited).

I don't find any :CREATED: value in exported file.

**Comment by nevenz** [comment]
> I don't find any :CREATED: value in exported file.

And the property exists in the note (with "Use property for created-at time" enabled) ?

**Comment by azzamsa** [comment]
> Use property for created-at time

Sorry but where I can find this setting ? I've tried to search since 2 days ago, I don't find it. I've enabled it in older version, it works. but I can't recall how I did that. Sorry.

**Comment by nevenz** [comment]
In app's Settings inside "Sync". It's the first option in "Notebooks files" section.

Yes, preference was moved and behavior is a bit different (property is not created immediately for a new note, but after you save it).

**Comment by azzamsa** [comment]
Wow, thanks it works. I never open "sync" setting. Cause I never sync my note to any external device.

1) I never sync my notes. So I trick using directory in internal storage to act like sync folder. I sync it. Then CREATED value appear.
2) But When I don't sync my note. My changes are not saved automatically. I need to use "force save" to make any changes "saved". 

May I know why orgzly didn't auto-save notes ? and what about people that never sync their notes ?

**Comment by nevenz** [comment]
Saving notebooks to a file on internal storage is also called "syncing" in Orgzly, as data is kept in the database.

If you setup a Repository (directory on your device), you can enable "Auto-sync" (it's all on the same Settings' "Sync" screen).

If you don't enable auto-sync (which needs to be improved for various reasons), you have to click "Sync" (in the bottom of the navigation drawer) to sync everything with the Repository.

**Comment by azzamsa** [comment]
> Saving notebooks to a file on internal storage is also called "syncing" in Orgzly, as data is kept in the database.

Oh, I see. that's why I don't find where the original "org" file stored.

> If you setup a Repository (directory on your device), you can enable "Auto-sync" (it's all on the same Settings' "Sync" screen).

Great. thanks for suggestion.

I just know that orgzly did't store all info in orignal org files. the reason might be database format is easier to parse.
