### ISSUE TITLE
file exports don't show up on MTP

### ISSUE THREAD

**Issue by QJKX** [orgzly/orgzly-android#44]
Files exported by orgzly don't show up on a computer connected to the phone via MTP.

Play Store Version. Android 6.0.1.

**Comment by QJKX** [comment]
Seems to be https://code.google.com/p/android/issues/detail?id=38282 . The files appear after a reboot.

(found through https://android.stackexchange.com/questions/46315/not-all-files-are-visible-over-mtp)

**Comment by nevenz** [comment]
Anything we can do about this, or can we close it?

**Comment by QJKX** [comment]
Work around:
https://code.google.com/p/android/issues/detail?id=38282#c139
