### ISSUE TITLE
open *.org file in android by orgzly

### ISSUE THREAD

**Issue by pochtadlay** [orgzly/orgzly-android#441]
Add the possibility of automatically opening files *.org in the orgzly application. Now the *.org files are opened with text editors by default. Android does not allow you to choose orgzly program to open *.org.

I have searched for existing issues that may be the same as or related to mine. 👼

**Comment by nevenz** [comment]
I think this is #148?

**Comment by pochtadlay** [comment]
Yes, that's it.

and when can we expect the realization of this feature?

Thanks!


пт, 1 февр. 2019 г., 20:16 Neven notifications@github.com:

**Comment by nevenz** [comment]
Give #148 a thumbs-up - someone might get to it before I do.
