### ISSUE TITLE
Tag inheritance in agenda view

### ISSUE THREAD

**Issue by SnarkBoojum** [orgzly/orgzly-android#443]
I have really searched for existing issues that may be the same as or related to mine : I found people reporting inheriting a tag multiple times, a feature request for sorting them, but not about them not working.

I'm using version 1.6.12, which I checked was the latest available.

I have an file family.org (shared with a computer using syncthing), looking like:
> * Diana                   :Diana:
 > ** whatever
>   SCHEDULED: <something>
and the "whatever" shows up correctly in the agenda, but without any tag.

I checked it only gets displayed when I add it directly at the "whatever" level, so I'm pretty sure tags work, but inheritance doesn't.

**Comment by nevenz** [comment]
Do you have "Inherited tags in search results" enabled (in Settings / Notes & Notebooks) ?

**Comment by SnarkBoojum** [comment]
Rrrrraaaaahhhh... problem solved! Thanks! And sorry for the noise...
