### ISSUE TITLE
Crash wenn clicking on the settings Reminders->Notifications

### ISSUE THREAD

**Issue by WeissP** [orgzly/orgzly-android#446]
I can only receive notifications without sound now. Wenn I want to change the settings "Reminders->Notifications", orgzly will crash or back to Homepage.

**Comment by nevenz** [comment]
Which Android version are you on?

On Android 8.0 and later that button should just open system's notification settings.

**Comment by WeissP** [comment]
> Which Android version are you on?
> 
> On Android 8.0 and later that button should just open system's notification settings.

On Android 8.1 but for Chineses custom androidsystem. 
And I should like to ask: User recived notifications in default settings with or without sounds?

**Comment by nevenz** [comment]
Default should be with sound.

You can try to open settings manually: "System Settings / Apps / Orgzly / App notifications / Reminders" (or equivalent) and see if that works.

Orgzly does that [here](https://github.com/orgzly/orgzly-android/blob/5182b517390708ebc9a377f5748acb929c127dff/app/src/main/res/xml-v26/prefs_screen_reminders.xml#L25) which would be same as running:

```
adb shell am start -a android.settings.CHANNEL_NOTIFICATION_SETTINGS -e android.provider.extra.APP_PACKAGE com.orgzly -e android.provider.extra.CHANNEL_ID reminders
```

(if you have `adb` and can try it).

**Comment by nevenz** [comment]
Please re-open if you're still seeing this issue. `adb logcat` output would be useful too. Thanks!
