### ISSUE TITLE
Show number patterns as phone links

### ISSUE THREAD

**Issue by memeplex** [orgzly/orgzly-android#447]
I'm submitting a **feature request**.

The trello android app shows patterns like 6378873 or 76-8777-8889 as links that open the phone app .

It's not perfect in the sense that sometimes numbers that aren't phone numbers are nevertheless recognized as such but it's nevertheless incredibly useful.

**Comment by ehahn** [comment]
FYI: Orgzly already recognizes links like tel://6378873 and tel://76-8777-8889

**Comment by memeplex** [comment]
Oh cool, then I think this can be closed.

**Comment by memeplex** [comment]
FYI `tel:32132131` is also supported.
