### ISSUE TITLE
Simplify "view in context" in search results

### ISSUE THREAD

**Issue by memeplex** [orgzly/orgzly-android#450]
I'm submitting a **feature request**.

In search results you have to swipe left and then tap the square "view in context icon" which is the only option in the toolbar. Maybe this toolbar is intended as a placeholder for future actions, but at this point it's just an annoying step. Why not simply open the context after swiping left?

This request can be seen as a poor's man subsitute to both:
* https://github.com/orgzly/orgzly-android/issues/182 (show children in search)
* https://github.com/orgzly/orgzly-android/issues/449 (sparse trees)

I mean, the simpler you get an "in context" view the closer you are to a properly sparse view.

**Comment by nevenz** [comment]
Quick/swipe menus are no more. One bottom menu is now opened on click.

Swiping left opens a note from the book, I've modified it for search results to open the book and scrolls to the note.

**Comment by memeplex** [comment]
Thanks!
