### ISSUE TITLE
Search query to match any date field not only scheduled/deadline

### ISSUE THREAD

**Issue by RGNagel** [orgzly/orgzly-android#451]
I have searched for existing issues that may be the same as or related to mine. 👼

I'm submitting a **bug report** for version REPLACE-WITH-APP-VERSION.
I'm submitting a **feature request**.

Hello,

When we see entries in agenda by org-mode, the agenda matches *all entries containing the date field*. For example, the following entry would match: * TODO blablabla <2019-02-14 thu 13:30-15:20 +1w>

However I am not being able to match the same entry by Orgzly. I tried the queries listed [here](http://www.orgzly.com/help#search) but none seems to work for me. Am I overlooking something or indeed it is not implemented?

Thank you very much in advance

**Comment by nevenz** [comment]
It's not implemented yet, it's #76.
