### ISSUE TITLE
FR: maybe use a different icon than the checkmark when saving a note

### ISSUE THREAD

**Issue by bbigras** [orgzly/orgzly-android#452]
When editing a note, the checkmark icon is used to save modifications while the same icon is used to mark the note as done in the app and the widget.

![image](https://user-images.githubusercontent.com/24027/52894012-e0418800-3170-11e9-9c06-aedfb7eeeaaa.png)

**Comment by bbigras** [comment]
Thank you very much. :+1:

**Comment by bbigras** [comment]
Was this change reverted?

I currently see this:
![image](https://user-images.githubusercontent.com/24027/54224837-b9a51180-44d0-11e9-9a0d-cf933a179bc0.png)

**Comment by nevenz** [comment]
Yes, closed/mark-as-done button has been changed instead. See screenshot in [this comment](https://github.com/orgzly/orgzly-android/issues/475#issuecomment-470885155).

**Comment by bbigras** [comment]
In my case I mostly use the widget and the done icon is not the one with the circle. If it was up to me I would use a "floppy" icon to "save" the note.

**Comment by nevenz** [comment]
> In my case I mostly use the widget and the done icon is not the one with the circle.

Ah, I forgot about that one. Current circled checkmark might not look good there (not that it looks too good anywhere). I'll see about that.

> If it was up to me I would use a "floppy" icon to "save" the note.

Yeah, I really dislike that icon. It looks kinda old to me. Being a floppy does that I guess. 😄
