### ISSUE TITLE
CREATED propertie is not removed from the synced repository

### ISSUE THREAD

**Issue by 532910** [orgzly/orgzly-android#453]
- [x] I have searched for existing issues that may be the same as or related to mine.

I have `Use property for create-at time` set to `ON` with `Created-at property` set to `CREATED`.
When I create `test` notebook with `test` note I got
```
* test
:PROPERTIES:
:CREATED:  [2019-02-18 Mon 03:27]
:END:
```
in the repository `test.org` file. All is fine here. But when I delete the `CREATED` property it ramains in the repository file.

**Comment by nevenz** [comment]
This is intended - with the preference enabled property is added on sync too if it's missing.

Note has internal created-at value and Org mode property is used as a way to preserve this value.

Additional preference would need to be added to change this behavior, if you need it.

**Comment by 532910** [comment]
Really I expect the property will be removed, when I remove it from the note.

**Comment by nevenz** [comment]
Yeah, that makes sense.

**Comment by 532910** [comment]
It's not fixed in 1.7, and will be fixed in 1.7.1 that is not released yes, right?

**Comment by nevenz** [comment]
> It's not fixed in 1.7, and will be fixed in 1.7.1 that is not released yes, right?

Yes, issues are closed when code is pushed.

v1.7.1 is in beta currently, you can [join it](https://play.google.com/apps/testing/com.orgzly) if you want.

**Comment by 532910** [comment]
I'm joined, but using f-droid version.
I've asked f-droid to include betas: https://forum.f-droid.org/t/orgzlry-betas/5517
(Note, that f-droid has the `recommended` tag, so you can include unstable versions and recommend last stable)

**Comment by 532910** [comment]
Hans replied on f-droid forum. Could you add betas to f-droid please.

**Comment by nevenz** [comment]
Project doesn't use Travis and for managing betas it sounds like `CurrentVersionCode` would have to be updated after every release? I don't have any experience with F-Droid, it wasn't setup by me, it was done in #5.

Perhaps you can open a new issue here first, so someone can take a look what's needed.

**Comment by 532910** [comment]
Works fine, thank you!
