### ISSUE TITLE
"No connection" when syncing from Tasker on battery saving mode

### ISSUE THREAD

**Issue by memeplex** [orgzly/orgzly-android#457]
I've configured a tasker action as:

```
Tasker -> Send Intent
Action: com.orgzly.intent.action.SYNC_START
Package: com.orgzly
Class: com.orgzly.android.ActionReceiver
```

Usually this works just fine, triggering Orgzly sync action. But once my phone enters Battery Saving mode I immediately get "No conection" when I play the Tasker action, even if Orgzly performs a complete sync when invoked from its UI.

**Comment by nevenz** [comment]
I can't reproduce this on my device or emulator.

Where do you get that "No connection"? Orgzly's "sync failure" notification?

What Android version is this on?

**Comment by memeplex** [comment]
I'm now unable to reproduce it. I'm closing this issue and will reopen it in case I see the reported problem happening again. Thanks!
