### ISSUE TITLE
Add the center_focus button to the note edit screen

### ISSUE THREAD

**Issue by keithcrone** [orgzly/orgzly-android#459]
This is still a HUGE missing piece in Orgzly. The entire premise of the app (and org-mode) is that of a heirarchy structure, yet there is no way to view that heirarchy from inside the note. In search results, we can jump to the outline (which is working GREAT finally) and then into editing the note, but jumping straight to the note offers no context. And internal linking (by UUID), which jumps directly to a note content, is still of zero value.

I'm sure the center_focus code is reusable and you already have the icon...sticking the button next to the notebook name, for example, would be a simple fix to many context related problems. That may even be a good temporary alternative to zooming into bullets (moving in and out of the current outline is pretty close) allowing you to focus on other requests like visibility or encryption.

**Comment by Ypot** [comment]
I think it's planned

https://github.com/orgzly/orgzly-android/issues/421

**Comment by keithcrone** [comment]
I've been asking for context in linking and search results for 18 months. I've resorted to all kinds of ridiculous work arounds to make sure and linking more relevant. The center_focus button just seemed like a simple quick solution to fix a glaring hole.

**Comment by Ypot** [comment]
I'd love to see your workarounds. Don't hesitate to show us of you are in the mood ;D

**Comment by keithcrone** [comment]
They aren't anything exotic or exciting.
1. Many tags and headlines are virtually the same. Customer A and customerA or order numbers like 9633728 tagged with 9633728. Then I can at least see the context of search results through the inherited tags. But doing that borders on silly. 
2.  Since [[file:9633728.org]] also works, I've started breaking files into really small pieces and linking them in hierarchies. Search results then at least give me more relevant notebook name...but now I have a ridiculously long list of notebook names which has become hard to sift through.

Org-mode is a great CRM on Emacs. But in Orgzly, you can't search through :PROPERTIES:. I tried turning more properties into headlines, but then I have the same multi-level search problem.

**Comment by Ypot** [comment]
Thanks. I think I can't get well what you mean, although orgzly developers maybe got it, a video would be helpful (ie using mobizen app).

Best regards

**Comment by keithcrone** [comment]
Nah, @nevenz isn't interested in my whining. In the time I've been asking to get some of these things fixed I should have just learned Java/Kotlin myself. I only keep bringing up ideas in the hopes some other programmer will create a pull request with some changes.

It' s a great program and @nevenz seems to take a lot of pride in its development. I certainly hope he continues. I think the problem is I use Orgzly different than he does so he doesn't see the need for the stuff I ask for.
