### ISSUE TITLE
Extend URI Parse with Intent.putExtra

### ISSUE THREAD

**Issue by TroyFletcher** [orgzly/orgzly-android#460]
Allow extension of SYSTEM_LINK_SCHEMES URI to check for extended data in order to Intent.putExtra.

Current scheme:
`sms:1-800-555-0199`

Proposed scheme:
`sms:1-800-555-0199;sms_body:Here you can set the SMS text to be sent;`

Would open the ability to build complex custom links for supported system Intents.

It's been a bit since I've been in an Android project, but if you can point me generally in the right direction to make the Parser function change myself, I can try to make and merge.

Thanks for the great work! This app only gets better!

**Comment by nevenz** [comment]
It seems Android already supports this. Try:

```
sms:1-800-555-0199?body=Hello+World
sms:1-800-555-0199?body=Hello%20World
```

**Comment by TroyFletcher** [comment]
Brilliant. After seeing the GPS example I had tried something similar with "sms_body", but it looks like "body" works with %20 for spaces.

Consider it closed, but recommend adding this to the doc.
