### ISSUE TITLE
Restore LongPress to open a note 

### ISSUE THREAD

**Issue by timjefferies** [orgzly/orgzly-android#468]
The new interface seems to be coming along nicely. 
One thing I'm missing since the update though is the ability to open a note with a long press. 

This is way more efficient than highlighting or swiping on a note and then clicking the open icon. 

Is it possible to restore this feature?

**Comment by nevenz** [comment]
You can open the note now by swiping it left.

Swipe actions (left and right) will become configurable in the future.

Long-click is now unused to reserve it for drag and drop (though I guess that action could become configurable too).

**Comment by nevenz** [comment]
Restored click/long-click preference in ced713cb.
