### ISSUE TITLE
Is it possible to use list in contents?

### ISSUE THREAD

**Issue by atbest** [orgzly/orgzly-android#469]
I tried to use lists in `content` but they are displayed as raw characters but not rendered as lists.

**Comment by nevenz** [comment]
Only checkbox list is supported. Though it doesn't look much different, it's just clickable.

See "Checkbox list is available" in "Getting Started" notebook (you might need to re-import the notebook from Settings / App).

**Comment by nevenz** [comment]
Please re-open if there's anything else unclear.
