### ISSUE TITLE
Can't install from Google Play (or by downloading the APK).

### ISSUE THREAD

**Issue by ivanperez-keera** [orgzly/orgzly-android#470]
- [X] I have searched for existing issues that may be the same as or related to mine.

I'm trying to install this app on an Android phone with Android 5.0. The model is NU-2S. Google Play is up to date. I did not have orgzly previously installed.

I've tried, unsuccessfully, to install it both from the store, and using the APK directly, 

- When using Google Play, I get error 910. I've seen this linked to having an SDCard as default storage, but I have none. Some mention this is fixed by clearing Google Play's cache/data. That didn't work either.

- When using the APK directly, it won't install (either by downloading it or via USB with ADB).

I don't see much in the logcat, but if you tell me what to search for, I can try. Here's some stuff I see:
```
V/ActivityManager(  665): Broadcast: Intent { act=android.intent.action.PACKAGE_VERIFIED dat=file:///data/local/tmp/com.orgzly_117.apk typ=application/vnd.and
roid.package-archive flg=0x11 (has extras) } ordered=false userid=-1 callerApp=ProcessRecord{22c7a62a 665:system/1000}
...
D/DefContainer(24392): Copying /data/local/tmp/com.orgzly_117.apk to base.apk
...
D/PackageManager(  665): manifestDigest was not present, but parser got: ManifestDigest {mDigest=de,ee,cb,c8,00,09,8e,de,6e,53,94,96,b9,65,08,0d,c5,5f,a9,76,9
4,f7,20,a1,d5,cd,20,bb,86,cc,22,4a,}
D/PackageManager(  665): Renaming /data/app/vmdl64168922.tmp to /data/app/com.orgzly-1
I/PackageManager(  665): Start installation for package: null
D/PackageManager(  665): installNewPackageLI: Package{3ae04302 com.orgzly}
...
I/PackageManager(  665): Linking native library dir for /data/app/com.orgzly-1
I/PackageManager(  665): Perform pre-dex opt for package: com.orgzly
I/PackageManager(  665): Running dexopt on: /data/app/com.orgzly-1/base.apk pkg=com.orgzly isa=arm vmSafeMode=false
E/installd(  226): DexInv: --- END '/data/app/com.orgzly-1/base.apk' --- status=0x0100, process failed
I/PackageManager(  665): Dexopt done on: com.orgzly
D/installd(  226): do_remove : com.orgzly 0
D/installd(  226): uninstall : com.orgzly
W/PackageManager(  665): Package couldn't be installed in /data/app/com.orgzly-1
W/ADB_SERVICES(24975): create_local_service_socket() name=shell:rm -f '/data/local/tmp/com.orgzly_117.apk'
W/ADB_SERVICES(24975): service_to_fd() name=shell:rm -f '/data/local/tmp/com.orgzly_117.apk'
W/ADB_SERVICES(24975): LS(12): bound to 'shell:rm -f '/data/local/tmp/com.orgzly_117.apk'' via 17
```

(EDIT: Added error message printed on the logcat)

**Comment by nevenz** [comment]
Is that all from `PackageManager` in logs? No stack trace?

What about [latest beta](https://github.com/orgzly/orgzly-android/releases/tag/v1.7-beta.6), any difference?

**Comment by ivanperez-keera** [comment]
That worked. Thanks. I'd be interested in seeing if it also works straight from Google Play.

**Comment by nevenz** [comment]
> That worked. Thanks. I'd be interested in seeing if it also works straight from Google Play.

Cool. You can try it by joining the [Beta program](https://play.google.com/apps/testing/com.orgzly), though I'd be surprised if it didn't, as it's the same APK.

**Comment by ivanperez-keera** [comment]
Thanks! I just tried it and I could install the beta from the store, so this can be closed. I don't know why the current version does not work, but, presumably, that'll be automatically fixed when the next version is released.
