### ISSUE TITLE
Is it possible to directly open Content Editor in Edit mode on any note?

### ISSUE THREAD

**Issue by 573** [orgzly/orgzly-android#473]
- [X] I have searched for existing issues that may be the same as or related to mine.

**Comment by memeplex** [comment]
I don't think this is posible but it's a nice suggestion. Given that you're already in "item edit mode" opening the text box also in "edit mode" will spare you one tap. I don't see a compelling reason to do it otherwise, indeed.

**Comment by nevenz** [comment]
Some improvements are needed here to be able to edit note more quickly. Issue has been raised in the past.

I do have a to-do for starting in edit note, with a new view mode button (perhaps in action bar). This view mode work for both title and content, as title can contain markup/links too.

Perhaps it can be global too, i.e. remembered across notes. Like metadata folding is now.

**Comment by NiceFeather** [comment]
More extend to whole notebook, please reference to issues #404, #226, #393, ...
