### ISSUE TITLE
Reduce the swipe left to open animation time

### ISSUE THREAD

**Issue by memeplex** [orgzly/orgzly-android#474]
I think the usability changes in the latest release are quite cool but the Open animation is both weird and slow. It's weird because it looks like the entry is being removed or archived, not opened. And this confusing animation takes some time, which makes things worse. Why don't you suppress the animation altogether?

**Comment by nevenz** [comment]
I was trying to make label go *over* the note, which might make more sense (though current behavior is standard and not only used for removing notes). I didn't manage to do that quickly, I'll check it out again and how it looks like.

Most of the time is used by swipe action itself. But there *is* a difference if you were to disable animations on your device (if you can, let me know if that makes swiping faster). I'll check how to disable it for just this action.

**Comment by memeplex** [comment]
>I was trying to make label go over the note, which might make more sense

It would make more sense, indeed. But anyway having the note editor immediately open is enough feedback for the swipe action (it's not like in archive or remove in which cases you might swipe by accident and never become aware of the loss). My preference is for removing the animation altogether and opening the note editor ASAP. Even if you managed to get the cool animation the way you intended it (label sliding over item) I believe I still would prefer no animation at all. But that's a matter of opinion and I surely prefer any of those solutions over the current one by far.

**Comment by nevenz** [comment]
There is no reason for not having an animation while swiping, as that swipe gesture needs to happen, backed by animation or not.

I tried drawing a label on top, but it doesn't seem to be as easy as I though. I'm not going to try again before figuring what to do with #475, so I'll close this.

Animation duration is now 0 and you need to only swipe 1/3 of width (vs previous 1/2).
