### ISSUE TITLE
New icons on edit screen look out of place and somehow confusing

### ISSUE THREAD

**Issue by memeplex** [orgzly/orgzly-android#475]
I know somebody requested to change the save icon to distinguish it from the DONE one, but the new one is quite weird also, looks like send or share... What about a check inside a white circle to match the also circled x?

Anyway the new icons are much more "solid" than most other icons in orgzly, maybe a couple of more outlined close/save ones are in order. If you tell me the icon set you are using maybe I could take a look for suggestions. I use Nerd Fonts a lot, is it possible for you to use their glyphs?

**Comment by memeplex** [comment]
Here you have a couple of solid checks that matches the current solid x.

![image](https://user-images.githubusercontent.com/2845433/53846854-4742a780-3f8d-11e9-89eb-c1401d4c2182.png)

Another possibilities:

![image](https://user-images.githubusercontent.com/2845433/53846922-8bce4300-3f8d-11e9-9595-c0674a932dd6.png)

![image](https://user-images.githubusercontent.com/2845433/53846939-9e487c80-3f8d-11e9-8646-e049de571350.png)

![image](https://user-images.githubusercontent.com/2845433/53846997-d64fbf80-3f8d-11e9-993e-acd4e0fc5976.png)

![image](https://user-images.githubusercontent.com/2845433/53847028-f7181500-3f8d-11e9-888e-4912ba9a4204.png)


Everything was taken from Nerd Font cheat sheet (https://nerdfonts.com/).

**Comment by memeplex** [comment]
For example, look how ugly the transition from notebook view to note edit looks like:

![screenshot_20190305-230325 2](https://user-images.githubusercontent.com/2845433/53850995-e40c4180-3f9b-11e9-965a-93ff6ca497d5.png)

![screenshot_20190305-230709 2](https://user-images.githubusercontent.com/2845433/53851011-f1c1c700-3f9b-11e9-8a85-251adc9f8d0d.png)
 
The first pair is outlined, the second one is solid, plus the meaning of the arrow is unclear. The suggested diskette icon is both outlined and standard.

**Comment by nevenz** [comment]
Yeah, I'm not too crazy about those icons either. Send icon is used for leaving detail view in some apps, but cancel one is pretty bad.  Perhaps it should be removed completely, since back button does the same.

I'll try the save icon, though icon collection used by Orgzly doesn't have the outline version. Icons are from [google/material-design-icons](https://github.com/google/material-design-icons).

Another option is to switch back to simple checkmark, but use a different icon for marking note as done. Like [this one](https://github.com/google/material-design-icons/blob/224895a86501195e7a7ff3dde18e39f00b8e3d5a/av/drawable-xxxhdpi/ic_playlist_add_check_black_48dp.png).

**Comment by memeplex** [comment]
The second outlined diskette, the next to last one, is nd_mdi, which means that it's in nerd fonts and it's taken from material design icons. Nerd fonts is just an aggregate of other font sets, including mdi. Here you have it in material design icon searcher: https://material.io/tools/icons/?search=save&style=outline. Maybe you're using an old version?

**Comment by memeplex** [comment]
The checkmark you suggested is not bad, it's a bit confusing because it looks like a list but, indeed, a note is kinda a list: both a list of different properties at the top and a list of text lines at the bottom; I think I still prefer the diskette but at that point it's not clear cut to me. Wrt the cancel icon: removing it is fine, although the outlined cross you were using is fine too as long as you combine it with an outlined save icon

**Comment by memeplex** [comment]
This may be worth opening another issue but came up when thinking about icons. There may be a use case not only for one single icon (removing the x one) but also for three icons:

1. The original outlined x for exiting.
2. The outlined diskette for saving.
3. The outlined check (probably the one you suggested) for saving and exit.

The use case is this: you're writing a long note and you want to save a checkpoint in order not to accidentally lose everything. It often happens to me and, specially when coming from a share action or having opened orgzly from the home screen shortcut, it's painful having to open orgzly again, relocate the notebook, relocate the note, open it and resume editing.

Note that once autosync is fully implemented this checkpoint also means: sync to remote store, which adds a layer of additional backup.

Here I'm mixing up aesthetics and function to some extent. If you prefer I may file a new issue, but since this seems simple enough (at least at first sight) I'm just taking note here for the time being.

**Comment by nevenz** [comment]
I was using icons from the GitHub repository, but that seems to be only a subset of what's available on the website.

I was suggesting the new icon to replace *done state and mark-note-done action*, not *done-editing action*. But [this one](https://material.io/tools/icons/?search=check_circle&icon=check_circle_outline&style=outline) might be even better for that. And then we can just revert the #452 change. Like this:

![note-view](https://user-images.githubusercontent.com/10671476/54023984-b0493b80-4196-11e9-8988-f75bdb1c6dc3.png)

I think a new issue would be better for save vs save&close suggestion. There were more related ideas there, like auto-saving the note (many apps don't even have save/done buttons).

**Comment by memeplex** [comment]
I think yours is a good solution! Just one remark: the square checkbox is more closely associated with DONE but, aesthetically, the icon is surrounded by circular ones (the clock, the info icon) so I don't really know there, the circular check mark looks better indeed.

**Comment by neiljerram** [comment]
I agree that the Send icon is non-intuitive. I think it was a tick before, right?

**Comment by nevenz** [comment]
> the square checkbox is more closely associated with DONE

I agree, but it's too close to lists' checkboxes.

**Comment by 532910** [comment]
![image](https://user-images.githubusercontent.com/14617699/54201180-0e9b5480-44de-11e9-9f1e-a3be86a76734.png)  Is export, extract, or something like this, not open or edit.

@nevenz says it's "[open in new](https://material.io/tools/icons/?search=open&icon=open_in_new&style=baseline)", OK, it may be 'open in new' but the real action is not 'open in new'.

 ![image](https://user-images.githubusercontent.com/14617699/54201535-f1b35100-44de-11e9-9941-600ad707d416.png)

**Comment by memeplex** [comment]
The action is open-in-context, open-in-tree. I believe it's a good choice of icon, it might not conventionally mean that (and what stock icon does?) but it clearly is pointing out of the item, as we can say to its surroundings, and its outlined and good looking.

**Comment by memeplex** [comment]
Ah no, sorry, I was thinking about the other icon. I think you have a point indeed. For editing the "pen and notebook" kind of icon is conventional and available. That said, because of my arguments above, the current edit icon fits better the open-in-context icon than the current open-in-context icon itself. What about using a pen icon for edit and the arrow pointing outside the box for open-in-context?

**Comment by 532910** [comment]
A pen icon is better, but it's not only an edit action, but also show note properties.

Maybe something like this one:

![img](http://icons.iconarchive.com/icons/icons8/windows-8/512/Programming-Edit-Property-icon.png)

**Comment by NiceFeather** [comment]
good look！

**Comment by memeplex** [comment]
True but a pen over an empty notebook may look more armonious aside an empty square with an arrow bent in a similar angle than the pen. Besides it would feel a little more outlined and lightweight as most of orgzly icons. I think it's worth considering that option.

**Comment by nevenz** [comment]
Shouldn't this button be removed now that click (or long-click) open the note again?

**Comment by memeplex** [comment]
I wouldn't mind that you remove it.
