### ISSUE TITLE
Checking an element in a checklist scrolls down to the bottom of notebook

### ISSUE THREAD

**Issue by memeplex** [orgzly/orgzly-android#476]
Just what the long title describes. Wasn't happening before the update. Makes using checklists pretty uncomfortable, since the user has to scroll up to the list again after each check.

**Comment by memeplex** [comment]
I'm closing this because I'm unable to make it happen again. Please try it at least once. If I see it happening again I will reopen it.

**Comment by nevenz** [comment]
I can't reproduce it either. I don't see what would trigger the scrolling in the code.
