### ISSUE TITLE
All notebook shortcuts is unavailable on the desktop

### ISSUE THREAD

**Issue by NiceFeather** [orgzly/orgzly-android#478]
All notebook shortcuts is unavailable on the desktop, there was no response from the tapping.

Version: 1.7
Device: Android 8 on Samsung s7 edge

**Comment by nevenz** [comment]
This is a symptom of database migration - notebook IDs are all different.

Users will have to re-create the shortcuts. 😞

**Comment by NiceFeather** [comment]
> This is a symptom of database migration - notebook IDs are all different.
> Users will have to re-create the shortcuts.

Yes, I have re-created all essential shortcuts, but they are the same for me. :(

**Comment by nevenz** [comment]
> This is a symptom of database migration - notebook IDs are all different.

Ignore this, it's not the case - migration is properly copying all the fields.

> Yes, I have re-created all essential shortcuts, but they are the same for me.

Hmm, I can't reproduce it. Can you try to re-install the app perhaps to see if it makes a difference?

**Comment by NiceFeather** [comment]
Yes, I've got them after renewing an installation, thank you!

**Comment by nevenz** [comment]
> Yes, I've got them after renewing an installation, thank you!

Cool, although strange.
