### ISSUE TITLE
What is the residual icon in the status bar?

### ISSUE THREAD

**Issue by NiceFeather** [orgzly/orgzly-android#482]
I found there will be remained a residual icon after removing any notification in the status bar, what's it? and what does it do?

**Comment by nevenz** [comment]
It's an empty group summary for reminders. Fixed in 8c4bb47a9fd12f7bdbb6c7a07cffca93ad8efca2.

**Comment by NiceFeather** [comment]
This issue have resurfaced in the latest v1.7.3, it seems sometimes, not always, please review the relatived code, thanks!

**Comment by nevenz** [comment]
> This issue have resurfaced in the latest v1.7.3, it seems sometimes, not always, please review the relatived code, thanks!

I'll keep an eye on it, thanks.
