### ISSUE TITLE
New layout is harder to use than before

### ISSUE THREAD

**Issue by neiljerram** [orgzly/orgzly-android#483]
I have to say that I'm not keen on the new layout. Specifically, I find that my finger has to travel much farther than it did before, for common (for me) operations like changing a scheduled date. Could we return to the previous layout?

**Comment by NiceFeather** [comment]
Yes, agree with this. the note item‘s slip-left and slip-right gesture should be reserved, including that In-place toolbar, this is THE MAINLY SPECIALTY OF ORGZLY. Current editting function of slip-left can be add into the toolbar using a button, What do you think?

**Comment by nevenz** [comment]
Swipe menus were a custom implementation for `ListView`, which was replaced with `RecyclerView` in v1.7 as part of switching to Android Architecture Components.

I was thinking if I should re-implement them for v1.7 or release that version sooner. I thought the bottom action bar would be enough, but apparently it's not for a lot of users.

I'll see about re-implementing swipe menus soon.

**Comment by memeplex** [comment]
It's working great again, thanks! Please notify that angry one-star reviewer ;)

**Comment by SanskritFritz** [comment]
Can we have the 1.7 bottom bar functionality back please as an option? I personally loved that change in contrary to others in this thread.

**Comment by memeplex** [comment]
Afaics the bar is there, just one long tap away.

**Comment by SanskritFritz** [comment]
Oh, thanks, that's nice.
