### ISSUE TITLE
Open in-context and unfolded from the search view

### ISSUE THREAD

**Issue by memeplex** [orgzly/orgzly-android#486]
(I'm keeping this comment as context for what follows but I've changed my mind since posting it and my actual request is in the third comment)

I see you have reintroduced the swipe menus in the latest beta which I think it's great! I disliked the need to go to the bottom of my tablet screen, although the bottom bar is fine for multitem actions. Also, you know how I hated the new open animation. I think the current solution fixes all that without losing what was introduced in 1.7. All but...

The new quick swipe left to open in context action from the search result was replaced with a swipe menu having two buttons: open in context and edit. Edit is completely useless since it's already the item tap action. And quickly open in context is very useful since the search results specially lack in context. You added this feature because of a request of mine, but now it was removed (baby and bathwater) with the removal of the swipe to open action. Why not just keeping this other one, without animation at all?

**Comment by memeplex** [comment]
Although I do recognize the interface it's more consistent as it is now, without that handy but ad hoc behavior.

**Comment by nevenz** [comment]
Are you suggesting that the current note view (full details) basically replaces the note in the list? Might be tricky to implement, but it could be a good solution/replacement for several requests and planned features.

**Comment by memeplex** [comment]
I'm not sure what do you mean but I will try to be clearer. Say you open an agenda and you swipe left over an item. Now you have two options: "open in context" and "edit". The first one shows you the item heading surrounded by its context in the notebook:

```
* Some item
* Some other item
    * TODO the item in the agenda
* Yet another item
```

What I'm suggesting is to simply start this view as if the user had unfolded the item of interest:


```
* Some item
* Some other item
    * TODO the item in the agenda
        The contents of the item
* Yet another item
```

**Comment by nevenz** [comment]
Oh OK, I went way too far there.

Content cannot be unfolded alone currently -- all children would have to be displayed too. And I don't think that's what org-sparse-tree does for example, which is what this action basically tries to be.

If the content is all you need from search results, enabling it in Settings (Notes & Notebooks / Display content in search) might be better.

**Comment by memeplex** [comment]
I understand @nevenz but I still belive there is a far too common and simple task that is being made unnecessarily hard to achieve. Consider this simple example: you enter you agenda to get an overview of things to do, pick one of the tasks there according to your context and priority, then want to see the details (checklist, description, etc) in order to start doing it. At this point you have these options:

1. Set the search results to *always* show content. This is too radical, you want to first get an overview and then get the details.

2. Tap and enter the edit view. This is awkward as I've already described, and now you enter the "edit contents" mode by default, so you can't follow links, for example.

3. Swipe left, tap, enter the in-context/spare-tree view, visually locate the task, tap the tiny circle at the right to unfold it.

Neither of these options make justice to the frequency and simplicity of the use case. What I'm proposing is to auto-expand the item to simplify 3 (no need to visually locate, no need to expand). I understand this is not a strict sparse tree but does it really matter? I also understand there currently is no action to unfold just a node implemented, but isn't it just a matter of programmatically triggering  the same handler that is handling the "tap on unfold icon" user action?

It would be great to have the unfold icon in the search view itself but I'm assuming that is harder to implement that my request above.

**Comment by memeplex** [comment]
Btw, in emacs org-mode, when you press `space` over an item in the agenda, it's expanded the same way I'm describing it:

![image](https://user-images.githubusercontent.com/2845433/54226130-e579c480-44db-11e9-8987-8623b0f96702.png)
