### ISSUE TITLE
Extremly bad save and edit icons. 

### ISSUE THREAD

**Issue by 532910** [orgzly/orgzly-android#487]
- [x] I have searched for existing issues that may be the same as or related to mine.

Please don't get my criticism wrong.

![image](https://user-images.githubusercontent.com/14617699/54201157-ffb4a200-44dd-11e9-8d26-5cefdf77a5a3.png)  Is send (for some messenger for exmaple), not save.

![image](https://user-images.githubusercontent.com/14617699/54201180-0e9b5480-44de-11e9-9f1e-a3be86a76734.png)  Is export, extract, or something like this, not open or edit.

![image](https://user-images.githubusercontent.com/14617699/54201306-591cd100-44de-11e9-94a3-83d269e366fa.png)  Is something like delete, not close without saving.

![image](https://user-images.githubusercontent.com/14617699/54201475-c892c080-44de-11e9-9105-3318ec1dd467.png) ![image](https://user-images.githubusercontent.com/14617699/54201535-f1b35100-44de-11e9-9941-600ad707d416.png)

**Comment by nevenz** [comment]
> I have searched for existing issues that may be the same as or related to mine.

#475 

> Is export, extract, or something like this, not open or edit.

It's [open in new](https://material.io/tools/icons/?search=open&icon=open_in_new&style=baseline) and I didn't find any better (though I wasn't looking too hard).

**Comment by 532910** [comment]
Sorry!
