### ISSUE TITLE
Deletion is harder in version 1.7

### ISSUE THREAD

**Issue by anotherboringuser** [orgzly/orgzly-android#488]
Hi, 
I couldn't find find an easy way to delete notes in the new version of orgzly. Now it’s three steps and I have to use the three point menu at the upper right corner.

**Comment by nevenz** [comment]
Swipe menus are back in v1.7.1 (#483), currently in beta.

**Comment by anotherboringuser** [comment]
Ok, thank you, I accidently opened this issue before I was finished typing my text. 
So there are other options I wanted to suggest (JFTR): 
- Add the delete icon to the new bottom action bar or, which would be even better, make the action bar customizable. 
- Use the now unused long press on a note or the right swipe for deletions. The latter would be convenient because it would be fast and similar to other apps (but maybe too easy, which is why a restore option would be great #6 )

**Comment by nevenz** [comment]
The plan is to make all bars customizable.

For swipe bar, some [ground work](https://github.com/orgzly/orgzly-android/blob/4e548c767f3bf6b7aefeaa0ba24e5d3b07fd4b14/app/src/main/java/com/orgzly/android/ui/notes/quickbar/QuickBar.kt#L184) has been laid with the new implementation.

So I'm not going to do any changes before that. Different users want and prioritize different things, and it's hard to make everyone happy. For example, I wouldn't want Delete button so prominent, especially without Undo support.

BTW, long-press is not unused in v1.7.1. Previous functionality is restored. There is an option to swap what press/long-press do (open or select note).
