### ISSUE TITLE
Add betas to F-Droid

### ISSUE THREAD

**Issue by 532910** [orgzly/orgzly-android#490]
- [x] I have searched for existing issues that may be the same as or related to mine.

The F-Droid forum topic about this issue: https://forum.f-droid.org/t/orgzlry-betas/5517
F-Droid has the recommended tag, so unstable versions could be added while last stable will be recommend.

Discussion with @nevenz starts at the end of #453

**Comment by 532910** [comment]
> Project doesn't use Travis

As I understand it doesn't matters.

> and for managing betas it sounds like `CurrentVersionCode` would have to be updated after every release?

Looks so.

**Comment by nevenz** [comment]
> it sounds like CurrentVersionCode would have to be updated after every release?

I don't know if this is worth it. Betas are generally not betas for long. v1.7 was a special case due to tons of internal changes.
