### ISSUE TITLE
Support for plain timestamp recurrence

### ISSUE THREAD

**Issue by Ekleog** [orgzly/orgzly-android#497]
My calendar is full of events defined like `<2019-01-28 Mon 11:30-13:00 +1w>`, that still display for all days in emacs.

It'd be great if Orgzly's support for plain timestamps also supported recurrent timestamps!

Anyway, thank you once again for Orgzly, it's great and always growing better by the day ! :1st_place_medal: 

(note: this is close to https://github.com/orgzly/orgzly-android/issues/397 ; though I'm not sure how close exactly it is and whether it's worth closing this issue in favor of #397)

**Comment by thejona** [comment]
It is supported.

It doesn't play well with TODO flag though. If you mark a timestamp with repeater as DONE it stops the sequence. I'd expected the same behaviour as SCHEDULED - that the status would revert to TODO and the timestamp would be integrated.

Maybe that's not doable because of possible multiple timestamps per entry?

**Comment by nevenz** [comment]
> If you mark a timestamp with repeater as DONE it stops the sequence. I'd expected the same behaviour as SCHEDULED 

I forgot about this. I'll see to do it for the next version.

**Comment by Ekleog** [comment]
@thejona I think we're not speaking of the same issue: I've just created a test notebook, added a task containing `<2019-01-01 +1d>` and searched for `b.test e.eq.today` and nothing came up, while in org-mode it'd display an item for today.

Is my “issue” more clear now?

**Comment by vit1-irk** [comment]
Also options with plain timestamps appear in agenda widget without any time&date mark (SCHEDULED entries do have this mark)

In Emacs it looks like

`<2019-03-19 Tue 08:30 +1w>`

Please make plain timestamps fully usable

**Comment by memeplex** [comment]
@nevenz  I see you're fixing issues with plain timestamps for 1.7.2. I also see there is a commit referencing this issue, which is still open anyway. Are you planning to include this one in the next beta too?

**Comment by Ekleog** [comment]
@nevenz Reading the commit message makes me think you solved the issue @thejona mentioned in https://github.com/orgzly/orgzly-android/issues/497#issuecomment-473558029 and not the one I was speaking about, which I tried to make more explicit with https://github.com/orgzly/orgzly-android/issues/497#issuecomment-473574443.

Then, maybe I'm misunderstanding?

**Comment by memeplex** [comment]
Indeed, after today's update e.today is matching <2019-03-21> but not <2019-03-20 +1d>.

**Comment by nevenz** [comment]
> I've just created a test notebook, added a task containing <2019-01-01 +1d> and searched for b.test e.eq.today and nothing came up (today = 2019-03-19), while in org-mode it'd display an item for today.

This is not specific to plain timestamps, that's how searching currently works for scheduled and deadline times too. Only the base time is used when searching, not repeated instances.

It's planned, perhaps as a new query option (a la `ad`), as searching might be much slower. It's related to https://github.com/orgzly/orgzly-android/issues/408#issuecomment-433725694, though this ticket asks for the (more or less) opposite thing. So perhaps a new ticket could be opened.

**Comment by nevenz** [comment]
> So perhaps a new ticket could be opened.

Hm, I guess this ticket was supposed to be it, but since it's an issue in general (for any type of time), a new one might still be better.

**Comment by memeplex** [comment]
Here https://github.com/orgzly/orgzly-android/issues/506
