### ISSUE TITLE
Sorting by plain timestamp: specifying which timestamp is used

### ISSUE THREAD

**Issue by Ekleog** [orgzly/orgzly-android#498]
It would be great to have an `o.e` sorting mode, similar to `o.s`. However, it might be more complex, as there can be multiple timestamps in a single note. Ideally the note would be duplicated in the output at each plain timestamp it contains, similar to org-mode, but I'm not sure how complex that would be to do.

As usual, thank you a lot for org-mode, you're great :100:

**Comment by nevenz** [comment]
This is done in 2d2a2a0d, it will be in the next version.

But it might not sort properly search results which contain notes with multiple timestamps. It's not defined which timestamp is used for sorting in that case.

Perhaps oldest timestamps should be picked when `o.e` is used, latest for `.o.e`.

I don't think multiple notes should be displayed, unless it's agenda.

**Comment by Ekleog** [comment]
Wow great!

You're right, I was thinking of using searches as agendas. If agendas are somewhere on the schedule then it's even better!

Leaving this open for tracking the picking of the “right” timestamp for `o.e`, then, I guess :)

(it's fun to see orgzly adding features faster than I can request them :p)
