### ISSUE TITLE
Did we lost some menu options from long press over a Notebook?

### ISSUE THREAD

**Issue by bjacquet** [orgzly/orgzly-android#499]
Greetings!

Recently updated to v1.7.1 (from… don't know which version I had before) and I can't get the options for resolving a sync conflict. 

When a sync conflict existed, I think I used to do a long press (on the Notebooks view) over the notebook. This would make the notebook selected and then in the "three dots menu" options _Force Load_ and _Force Save_ would show up.
Now I only have _Rename_, _Set Link_, Export, and _Delete_.

Thanks for this wonderful software. :-)

**Comment by nevenz** [comment]
First two, before overflow-menu are Force Load and Force Save.

![force-save-load](https://user-images.githubusercontent.com/10671476/54482632-f2354a00-4846-11e9-9e86-e51fa1120985.png)

**Comment by bjacquet** [comment]
Wow!!! 😮  I thought that was for sorting. 🤦‍♂️ 

Thanks for the info. 😃

**Comment by NiceFeather** [comment]
These icons really need to re-design, they will led to more confusion, even reduce the professionalism of this application.

**Comment by nevenz** [comment]
Existing icons are used from https://material.io/tools/icons/?style=baseline. I've changed these in the latest beta to outlined `cloud_upload` and `cloud_download`. It's probably going to be confusing to someone using a local directory as a repo, but oh well.

**Comment by bjacquet** [comment]
O looked into material's icon and I agree `cloud_upload` and `cloud_download` will work better.
For someone who is using a local directory, maybe these icons could be hidden from them? Since they wouldn't do anything. (I guess.) (I'm out of my depth here.)
