### ISSUE TITLE
- [ ] Checklist on titles

### ISSUE THREAD

**Issue by Ypot** [orgzly/orgzly-android#502]
* - [ ] Checklist on titles.
** If checklists worked on titles, it would be possible to create checklists with nested notes.

**Comment by nevenz** [comment]
This looks very hackish. It's a state (single and the only possible checklist item) within state (note's).

Why not just use note's state? It's only right swipe & click (✔️) away?

**Comment by Ypot** [comment]
I will try like you say.
Thanks
