### ISSUE TITLE
Edge lighting notification not working on the S10?

### ISSUE THREAD

**Issue by rieje** [orgzly/orgzly-android#508]
I set the appropriate settings for notification via edge backlighting on the Galaxy S10 but it refuses to show the edge light and only vibrates. Can anyone with an S10/S10+/S10e confirm this?

-------------------

P.S. An unrelated question, but what's the design decision for syncing notebooks to local storage? If Orgzly reads org files and writes to them, why is syncing necessary--shouldn't Orgzly write to the actual org file? E.g. if I have a folder of org files that I have Orgzly tracked and I use Orgzly to edit those files, I need to sync them before they are written back to the org files if I want the updated org files. Also, would it be possible to access/see the updated org files that weren't synced to the local repo yet?

**Comment by nevenz** [comment]
> what's the design decision for syncing notebooks to local storage?
> would it be possible to access/see the updated org files that weren't synced to the local repo yet?

Orgzly stores the data in the database. So regardless of where the files came from, app needs to export the data from DB and generate the Org file. Which is the main part of syncing. You could try enabling auto-sync. And there's a plan to try and keep the Org files updated after every change.

**Comment by rieje** [comment]
Good to know. I assume builtin support for Dropbox involve syncing to local device (i.e. generating org file) and then syncing that via Dropbox. Kind of weird there is builtin support for Dropbox as the only advantage I see that it brings is not needing the Dropbox app, but if you're a Dropbox user anyway, you will have the Dropbox app installed anyway.

IMO if there is to be any builtin support for other apps, then Syncthing should be a priority being open-source anse self-hostable (I see the open feature request for that).

**Comment by nevenz** [comment]
> Kind of weird there is builtin support for Dropbox as the only advantage I see that it brings is not needing the Dropbox app, but if you're a Dropbox user anyway, you will have the Dropbox app installed anyway.

I don't think it's possible to have a directory on the device synced using their app. It's why there's [Dropsync](https://play.google.com/store/apps/details?id=com.ttxapps.dropsync&hl=en) for example:

```
Two-way automatic synchronization should be an essential feature of the official Dropbox app itself since the beginning. For whatever reason it is not the case. Dropsync is here to fill the gap.
```

> IMO if there is to be any builtin support for other apps, then Syncthing should be a priority being open-source anse self-hostable (I see the open feature request for that).

Yeah, I was using Dropbox at the time and just did a quick implementation for myself.
