### ISSUE TITLE
Disable notification icon on status bar if persistent notification for quick note is used

### ISSUE THREAD

**Issue by rieje** [orgzly/orgzly-android#509]
The "New note and sync" feature for Orgzly shows the persistent notification panel for quickly creating notes. If you go to notification settings for this on Android Pie (it is categorized as `Ongoing (new note)`), the option of `Silent and minimized` will hide the notification icon on the status bar and minimize the notification panel for new notes.

However, there is no option to simply hide the notification icon. the alternative option `Silent` does not hide the notification icon. I'd rather not minimize the notification panel as that requires more clicks to create quick notes.

There should be an option to simply hide the notification icon--otherwise, it just clutters the status bar. For the purpose of a persistent notification panel, the status bar icon isn't needed anyway.

P.S. An unrelated question: I see that the widget for showing your TODOs relies on syncing periodically (e.g. every 1 hour, 2 hours, etc.). Would it be possible to "update" immediately whenever a note is added/removed/changed? Or at least update the widget after any actions performed through the widget?

**Comment by nevenz** [comment]
Icon display is controlled by Android, using importance for "Ongoing (new note)" channel. So you have to keep that "Low" (which is default) if you don't want icon displayed.

Notification could be displayed unfolded (with actions shown) by changing the priority it seems. I've tested it now using:

```
        if (true) {
            // Unfolded, actions are displayed
            builder.setPriority(NotificationCompat.PRIORITY_HIGH);
        } else {
            builder.setPriority(NotificationCompat.PRIORITY_MIN);
        }
```
I'm not sure if that should be the only option, especially now that some users are perhaps used to the current folded notification. So perhaps a new option should be added to the app for this (below "New note and sync").

> I see that the widget for showing your TODOs relies on syncing periodically (e.g. every 1 hour, 2 hours, etc.). Would it be possible to "update" immediately whenever a note is added/removed/changed

This is done already. Periodic sync is done on top of that (for when the current hour changes, as search results might depend on it). Are you seeing widget not being updated after some actions?

**Comment by nevenz** [comment]
I've set `PRIORITY_MAX` for it, but this doesn't guarantee that notification will be displayed expanded. There's no way to explicitly control this. There's https://issuetracker.google.com/issues/128470208 for example.

**Comment by Toad-Racer** [comment]
I'm running version 1.7.4 on Android 6.0.1 and until a recent update my "New note" notification was low priority and didn't put an icon on the status bar. However, now it always shows an icon on the status bar and on the lock screen, which I find a bit annoying. I haven't found a setting for this, but is there a way to make the notification low priority again?

**Comment by nevenz** [comment]
It could be made configurable.

**Comment by Arkanosis** [comment]
Please, that would be awesome :-)
