### ISSUE TITLE
Opening .org files with orgzly

### ISSUE THREAD

**Issue by leezu** [orgzly/orgzly-android#512]
- [X] I have searched for existing issues that may be the same as or related to mine.

Browsing to a `.org` file via the Android Files app, clicking the file should allow opening it with Orgzly. This should at least be supported for files which are in a synced directory.

In case this is already supposed to work, it does not work on Android Q.

**Comment by leezu** [comment]
This may help workaround https://github.com/orgzly/orgzly-android/issues/225 in some cases

**Comment by nevenz** [comment]
> In case this is already supposed to work, it does not work on Android Q.

No, it's not supported yet. It's #148.
