### ISSUE TITLE
change week start day in calendar for date selection

### ISSUE THREAD

**Issue by klausmcm** [orgzly/orgzly-android#519]
- [x] I have searched for existing issues that may be the same as or related to mine.

This might be something that needs to be changed on a system level but I would like to have the option to change the first day of the week in the calendar when I select a date. In google calendar, I have changed this from Sunday to Monday. In *orgzly*, the current day is Sunday but I also would like to change this to Monday

![Screenshot_20190405-185216](https://user-images.githubusercontent.com/14914359/55663680-54de8d80-57d6-11e9-9261-53d240240519.png)

**Comment by NiceFeather** [comment]
See issue #423

**Comment by klausmcm** [comment]
> See issue #423

Thank you. Please close this issue.

**Comment by klausmcm** [comment]
> See issue #423

Thanks.
