### ISSUE TITLE
issue with spaces in file paths

### ISSUE THREAD

**Issue by klausmcm** [orgzly/orgzly-android#522]
- [x] I have searched for existing issues that may be the same as or related to mine.

Is there any way to get file links working for files that have space(s) in the name?

Currently, any link to such file does not work. orgzly does not find the file.

**Comment by nevenz** [comment]
> Is there any way to get file links working for files that have space(s) in the name?

Try surrounding the entire link with double square brackets (e.g.`[[file:Getting Started with Orgzly.org]]`).

**Comment by klausmcm** [comment]
Thank you for the suggestion.

I think your suggestion works only in certain cases. Mainly if one does the link creation in orgzly.
Here is where I run into problems.

I edit the org file in emacs and then sync in orgzly.
The syncing process converts certain characters and ultimately the links are broken.

ex.
1. I enter in emacs
`- [[file:Documents/orgmode/assets/The Beltline Fitness Park - Circuit 1 Quotation.pdf ][quote (orgzly)]]`

2. After syncing in orgzly, I see (and link no longer works)
`- [[%5B%5Bfile:Documents/orgmode/assets/The%20Beltline%20Fitness%20Park%20-%20Circuit%201%20Quotation.pdf%5D%5D][quote (orgzly)]]`

3. In emacs I still see what I entered in step 1

**Comment by NiceFeather** [comment]
You can also refer to issue #312

**Comment by nevenz** [comment]
> The syncing process converts certain characters and ultimately the links are broken.

Hmm, I can't reproduce this. Nothing should be modified by syncing. What syncing method are you using? Is there something in between if you're using Directory repo type?

**Comment by klausmcm** [comment]
> > The syncing process converts certain characters and ultimately the links are broken.
> 
> Hmm, I can't reproduce this. Nothing should be modified by syncing. What syncing method are you using? Is there something in between if you're using Directory repo type?

You're right. I don't remember what I did so I can't reproduce the issue at the moment...

**Comment by nevenz** [comment]
Cool, you can reopen the issue if you see this again, thanks.
