### ISSUE TITLE
Notebook widget "App isn't installed."

### ISSUE THREAD

**Issue by GuiltyDolphin** [orgzly/orgzly-android#527]
Orgzly version: 1.7.3 (via F-Droid)

With Nova Launcher Prime version: 6.1.6 (if that's relevant)

As of a couple of updates back, my notebook widget's have no longer been working (the 1x1 ones).

I'm able to create them, and select which notebook to jump to, but when I actually click on the widget, it displays "App isn't installed.".

The 'Orgzly notes' widget works fine.

**Comment by NiceFeather** [comment]
See issue #478

**Comment by GuiltyDolphin** [comment]
Reinstalling fixed, thanks.
