### ISSUE TITLE
Also show event time in the widget

### ISSUE THREAD

**Issue by x-ji** [orgzly/orgzly-android#528]
- [ x ] I have searched for existing issues that may be the same as or related to mine.

I have looked at the options and searched a bit but haven't found the relevant option. I think it would be a relatively trivial feature to implement.

Currently the widget shows deadline time and schedule time, but doesn't seem to show the event time (plain timestamp). If I open the the search in Orgzly itself, then the event time is actually displayed.

This is useful when I want to use event time to schedule my day and check my schedule directly via the widget. Another way would be sync the org-mode files with Google Calendar but that is apparently a complicated a fragile process. It would be great if Orgzly can already do it.

**Comment by x-ji** [comment]
It would be even better if the plain timestamps could be displayed in a linear order, just as we are able to do in Emacs org-mode agenda view, by pressing `L` (show log view).

**Comment by nevenz** [comment]
This was done in 195da30a.
