### ISSUE TITLE
Capture options for bookmarking

### ISSUE THREAD

**Issue by Morgensohn** [orgzly/orgzly-android#53]
When capturing a bookmark in Firefox the result is a title with the webpage title and content with a link. If I highlight something on the webpage, the result is title and content with text, i.e. no link. Would it be possible to have a capture option for this type of uses? Or some other solution that would enable to keep both the link and the highlighted content.

**Comment by Morgensohn** [comment]
It would be great if this would result in an implementation of capture templates, perhaps with the option to edit them.

**Comment by nevenz** [comment]
This is not possible it seems.

From Chrome only EXTRA_TEXT is received, from Firefox EXTRA_SUBJECT, EXTRA_TITLE and EXTRA_TEXT are in the bundle, but none of them contain URL.

Might not be in those apps' control either, since that's systems's select/copy/etc.

My web search on the subject is also a dead end.

Let me know if you find an app that _does_ receive URL and selected text when you share to it.

**Comment by Morgensohn** [comment]
Thanks for the information. I tried to do a search concerning Firefox for Android and it looks as if Firefox for Android did implement this in

https://bugzilla.mozilla.org/show_bug.cgi?id=1171929

and some people didn't like it, so they reverted it in

https://bugzilla.mozilla.org/show_bug.cgi?id=1239503

I have no idea if this is thus unsolvable, or if there is a way for apps to grab the URL themselves.

**Comment by nevenz** [comment]
Ah cool, so apps _can_ decide what and how to share, even when selecting text. Good to know for future feature in Orgzly. :)

Still, I'm pretty sure the receiving app is stuck with whatever is sent in Intent.

Perhaps some Tasker magic would work, to send both selected text and url to Orgzly's Share activity.

**Comment by Morgensohn** [comment]
The mysterious thing is: if there is no text selected, Orgzly does get the URL and puts it into the content.

So my current workaround is to do two captures, one with text selected and another one without selections, which captures the URL, and then manual "merge" in Emacs.
