### ISSUE TITLE
Install downloads from F-Droid broken

### ISSUE THREAD

**Issue by WaterSibilantFalling** [orgzly/orgzly-android#533]
- [x] I have searched for existing issues that may be the same as or related to mine.

No versions of orgzly will update or install from F-Droid.  I am stuck on 1.6.1 and the latest is 7.4

if I can attach an image(my first ticket on a mobile), I will add a screenshot of F-Droid saying it can't find the apk

**Comment by AbsurdMagpieScrutinies** [comment]
![Screenshot_20190427-175301](https://user-images.githubusercontent.com/8019455/56845617-49374000-6918-11e9-957a-f791f8e22e44.png)

**Comment by AbsurdMagpieScrutinies** [comment]
l succesfully side-loaded from https://f-droid.org/repo/com.orgzly_134.apk

**Comment by nevenz** [comment]
126 (v1.7) is kinda old to be tried now. 134 (v1.7.3) is the latest. Not sure what's going on there.

**Comment by licaon-kter** [comment]
@AbsurdMagpieScrutinies Is this still an issue?

**Comment by nevenz** [comment]
It could be due to different signatures (F-Droid signs APK with its own key), or perhaps if you're using multiple users (not sure how, but some people have reported similar issues)?

**Comment by WaterSibilantFalling** [comment]
I tried installing from F-Droid, the Aurora Store (a clone of the google store) and side loading. None work.

If I always install from the same source, shoud I not have any problems?

**Comment by licaon-kter** [comment]
@WaterSibilantFalling not install, you can install from anywhere, but install and update from the same source

So is this a new install or an update?

**Comment by WaterSibilantFalling** [comment]
an update

**Comment by licaon-kter** [comment]
Can you try to install the APK instead? https://f-droid.org/en/packages/com.orgzly/

**Comment by WaterSibilantFalling** [comment]
That worked! I tried downloading orgzly apks before. 

Anyway, now it works. I'll do all my orgzly upgrades/updates via apks from now on. 

Thank you

**Comment by licaon-kter** [comment]
@WaterSibilantFalling Maybe retry on the next update, is that F-Droid 1.7.1?

**Comment by WaterSibilantFalling** [comment]
No, I'm actually runing F-Droid 1.6. I'll update.
