### ISSUE TITLE
sync method: from repo of github.com

### ISSUE THREAD

**Issue by cnglen** [orgzly/orgzly-android#535]
Dropbox is not available in my country. Can orgzly support sync from the repository of github.com?

During sync, if file changed, like on a PC, run:
- git pull
- git commit -m "update @timestamp"
- git push

**Comment by nevenz** [comment]
> Can orgzly support sync from the repository of github.com?

Not yet directly, you can follow #24.

You could use a Directory repo though and  setup some other app to sync it with GitHub.
