### ISSUE TITLE
Ability to filter by category/ other arbitrary properties

### ISSUE THREAD

**Issue by jthomas285** [orgzly/orgzly-android#546]
- [ X ] I have searched for existing issues that may be the same as or related to mine.
With my orgmode workflow I tend to use properties such as CATEGORY as well as others that I define myself. A good feature would be to be able to filter by any property, with CATEGORY being one that I would have thought would have been implemented already. The fact that it hasn't suggests that I'm probably wrong and it in fact has been, so forgive me if this is the case.

**Comment by nevenz** [comment]
It's not implemented, it's #146. It should probably be done generically, so "CATEGORY" wouldn't be special in any way.
