### ISSUE TITLE
When main task is done, all subtasks are removed

### ISSUE THREAD

**Issue by Malmik** [orgzly/orgzly-android#549]
As in title.

**Comment by nevenz** [comment]
Having subtasks is only possible in a notebook view. So in addition to selecting saved searches for a widget, notebooks should be selectable too.

**Comment by Malmik** [comment]
Thanks for implementing widget checkboxes in a update. It made Orgzly personally a lot better for me. I know that we can see subtask while using b."notebookname", but widget don“t show depth of subtask. Even if it is a subtask. 
And there is too small corelation between main task and it's subtasks. When I tick main task as complete, subtasks remain. This is frustrating. 
For example I have shopping list with subs: avocado, banana and mandarine. I put avocado in the basked and I check it. Then I see the fruits near so I grab both and instead of checking them one by one, I just mark whole task as done, but fruits are still in my notebook. 
Please add:
- some mark to subtasks in widget so main task are clearly visible
- code that removes all orphaned subtasks when main is deleted

Thanks for your great work!

**Comment by NiceFeather** [comment]
All widgets just is search result list, I thinks it's some tentative suggestions if adding subtasks/checkboxs in widgets. Think it all out, guys.

**Comment by nevenz** [comment]
Yes, I don't think there's much difference between search results in app and widget. You can't see if task has sub-tasks from within the app ether now I think? This is something that does need to be improved (more context, it has been requested a lot, I think it's #182).

Marking all sub-tasks done by marking their parent done is definitely a separate thing. Sounds useful, but implementation needs to be figured out. Should it be something configurable, should there be a separate button for it, etc.

**Comment by Malmik** [comment]
I think it probably be global switch in settings or even be an application feature. Correct me if I am wrong, but is there any scenario when we want to keep subtask from main task that is marked as done / deleted?

**Comment by nevenz** [comment]
> Correct me if I am wrong, but is there any scenario when we want to keep subtask, when main task is marked as done / deleted?

Probably not, although you might want them marked done with a different state. For example if you couldn't find other fruit and want those sub-tasks marked as `CANCELED`.

I think a new global "Set task's children as done" (needs a better description) preference would work. But there are still some questions:

* Should all task's descendants be marked with the same state, or just children?
* Should they be marked on any done state change (right swipe / flag), or only when "Done" button (right swipe / check-mark) is used? If former, should this be done from within the note view too?
* Should there be a confirmation, warning user that all children (or descendants) will be marked done?
