### ISSUE TITLE
Display check mark for notes in widgets - option to hide

### ISSUE THREAD

**Issue by domOrielton** [orgzly/orgzly-android#551]
Would it be possible to add an option in the widget setting to hide the check mark for notes when displayed as a widget? I know this was only added in v1.7.4 but to me it looked much cleaner/minimalist without the check mark.  I'm sure the check mark is useful to many users so hopefully an option to show/hide would work for everyone.

Thanks and very appreciative of the hard work you've put into the app.

**Comment by nevenz** [comment]
Some ideas from https://play.google.com/store/apps/details?id=com.stuff.todo&hl=en could be taken perhaps, app I was pointed to recently. Thanks.

**Comment by domOrielton** [comment]
Looks good to me, especially as I've actually used (and payed for) that app in the past. This does have more customisation though so might be easier to go the simple route with just adding an option for  Display Check Mark Y/N.   Thanks

**Comment by domOrielton** [comment]
Thanks for the update and getting this added in, really appreciate the work!
