### ISSUE TITLE
Autosync not working

### ISSUE THREAD

**Issue by tbrodbeck** [orgzly/orgzly-android#552]
The most important feature of orgzly IMHO is to be able to sync your notes. And that should optimally happen automatically. I just wanted to mention, that on my phone the automatic sync is not working. It only syncs when I tell it to, even though I checked all the boxes to activate autosync.

I am using a Galaxy s5 with Android 6.0.1 and orgzly 1.7.4.

Still thanks a lot for the app. It is already very awesome!

PS: It would be even more awesome with the ability additionally to sync once a day.

**Comment by nevenz** [comment]
Do you have a Dropbox repository type setup? Auto-sync only works if you only have Directory repositories defined (it's one of two reasons why #8 is still open).

Scheduling sync is also planned as part of #8.

**Comment by tbrodbeck** [comment]
Yes I have my orgfiles inside a directory of my dropbox, trough which I sync to orgzly. The oddity is that it still does not auto-sync, when I start the app or when I modify a note.

**Comment by nevenz** [comment]
By "Directory repositories" I meant "Directory" type of repository, other type being "Dropbox".

So that's normal, auto-sync doesn't work with Dropbox yet.

**Comment by tbrodbeck** [comment]
Oh ok got it now. Yeah pls work on it. Would be awesome
