### ISSUE TITLE
lots of sync conflicts

### ISSUE THREAD

**Issue by pbienst** [orgzly/orgzly-android#555]
I have orgzly set up in combination with SyncThing to an SD card folder. However, it seems I'm getting rather a lot of sync conflicts where the remote and local files have both been modified. This even happens when I'm absolutely sure the other sync partners are turned off. I've tried both with autosync and excessive manual syncing, but that doesn't seem to make a difference. 

If there's a sync conflict, is there a way to see what exactly what this conflict is, to help debug this?

**Comment by nevenz** [comment]
Reasons for sync failure are per notebook in Notebooks view. It should be one of those in http://www.orgzly.com/help#9a103af.

Is it actually "Both local and remote notebook have been modified" ?

If your force load/save the notebook, does it appear again?

**Comment by pbienst** [comment]
Yes, that's the exact message. Yesterday, it kept reappearing from time to time, even after forcing to keep a version.

I have to say however that today, it did not (yet) reappear, but I'll keep looking for a pattern...

**Comment by pbienst** [comment]
I think this can be closed, I've never seen it again. Probably SyncThing was acting weird and this was fixed by a reboot.
