### ISSUE TITLE
Add option to open notes in view mode

### ISSUE THREAD

**Issue by GuiltyDolphin** [orgzly/orgzly-android#556]
I notice that recently the default mode when opening notes was changed to edit mode.

I have a lot of links/checkboxes in notes, and to be able to click on these links/checkboxes I must first click the `View` button to switch to view mode—it would be really handy if there was a global option to toggle the default mode between edit and view.

Other thoughts for this option:

- perhaps the options could be as follows:
  - always start in edit mode
  - always start in view mode
  - start in view mode when the content contains links/checkboxes
  - start in edit mode only if note content is empty

**Comment by nevenz** [comment]
I was planning option with:
* Start in edit mode
* Start in view mode
* Remember state across notes (like metadata folding)

**Comment by GuiltyDolphin** [comment]
@nevenz those sound like a sensible set of choices.
