### ISSUE TITLE
Add search operators help to the "Searches" fragment

### ISSUE THREAD

**Issue by karlicoss** [orgzly/orgzly-android#557]
- [x] I have searched for existing issues that may be the same as or related to mine.

I don't add new searches often so tend to forget the [syntax for search](http://www.orgzly.com/help#search). Perhaps would be good to add a 'Help' entry to the context menu in the "Searches" view, in the simplest implementation just pointing at static html page bundled with the app? It also might be useful to add it in other places in the app, e.g. for links syntax.

I think currently the only way to see help is via "Getting started with Orgzly", and while its a good reference, some people tend not to keep it, and it takes time to switch back and forth between the notebook and search fragment. Although if https://github.com/orgzly/orgzly-android/issues/148 was supported, "Help" could merely open the "getting started" org file bundled with the application, it also would have the benefit of reflecting latest features of the app (don't think the 'Getting started' file is updated as well on app update, right?).

**Comment by nevenz** [comment]
I think help for searches won't be needed after #224.

I don't like adding links in more places in the app, but a single link opening a web page should be useful.

**Comment by nevenz** [comment]
Done in 374070ac.
