### ISSUE TITLE
what is revision in versionedHook?

### ISSUE THREAD

**Issue by rafaelleru** [orgzly/orgzly-android#56]
I'm working on webDAV support #38 and I was looking Dropbox repo, but I can not understand what is revision in:

```
VersionedRook book = new VersionedRook(
                                        repoUri,
                                        uri,
                                        file.getRev(),
                                        file.getServerModified().getTime()); 
```

represented by file.getRev() because this file is from dropbox API.

**Comment by nevenz** [comment]
It's just a unique string representing a specific version (hence _Versioned_ Rook) of the file in time.

If storage doesn't support it, you can just use file's modification time, as it's done for `DirectoryRepo`.
