### ISSUE TITLE
relative path

### ISSUE THREAD

**Issue by pbienst** [orgzly/orgzly-android#562]
I have an inline image [[./foo.png]] which shows up perfectly in Emacs. Both the org file and the image are in the same directory and synced over successfully through SyncThing.

The image does not show, and clicking the link reveals: 

File does not exist: /storage/emulated/0/foo.png.

Orgzly should interpret this relative path as leading to the directory where the original org file is located.

**Comment by nevenz** [comment]
This is #496, thanks.
