### ISSUE TITLE
Support searching for closed, repeating notes

### ISSUE THREAD

**Issue by GuiltyDolphin** [orgzly/orgzly-android#563]
Currently, the `c.today` filter will only show non-repeating notes that were closed today.

It would be really useful if repeating items that have been marked done will also show in either the `c` filter, or a new filter (perhaps `rs` for "rescheduled", or `ts` for "time-shifted").

My main use case: sometimes I accidentally mark the wrong item as done from a widget, and need to find it to shift the time back to the current day.

**Comment by nevenz** [comment]
I think this should be handled by #146 with "Set property on time shift" enabled and searching for `LAST_REPEAT` property. Would that work for you?

**Comment by GuiltyDolphin** [comment]
@nevenz property search could definitely work. Would we be able to search `LAST_REPEAT` using the usual date search format (e.g., `LAST_REPEAT.lt.7d`)?

**Comment by nevenz** [comment]
> Would we be able to search LAST_REPEAT using the usual date search format (e.g., LAST_REPEAT.lt.7d)?

It could be implemented. Having comparison operators and times on the right side could mean the value is a timestamp.

**Comment by nevenz** [comment]
I'll close this as a duplicate.
