### ISSUE TITLE
Add a settings toggle to set default: View / Edit content

### ISSUE THREAD

**Issue by hubertgk** [orgzly/orgzly-android#564]
- [x] I have searched for existing issues that may be the same as or related to mine.

This is possibly related to [#374](https://github.com/orgzly/orgzly-android/issues/374) but was not explicitly mentioned there.

Currently, when a link is followed, a note is always opened in Edit content mode by default. It then makes it easy to quickly type text but rich text, links or images are not rendered in this mode.

It would therefore be nice if there was a toggle in Settings that would make it possible to set a preference to either View or Edit content as the default content setting.

Use case: navigating between notes using internal links, such as in a knowledge base, would make much more sense if we could have the ability to set a preference to View content mode and have all rich text immediately rendered when landing on a link target.

Many thanks

**Comment by nevenz** [comment]
#556 has been recently opened.
