### ISSUE TITLE
Not buildable with current stable version of android-studio

### ISSUE THREAD

**Issue by IvanMalison** [orgzly/orgzly-android#568]
- [x] I have searched for existing issues that may be the same as or related to mine.

This project seems to require the use of android-studio 3.5, which is currently still in beta. Is there a good reason for this?

**Comment by nevenz** [comment]
#534 - I knew it was a bad move, but I got tired of not using instant run when developing.

**Comment by nevenz** [comment]
Closing after Android Studio 3.5 release.
