### ISSUE TITLE
Crashes on launch (Android 4.4.2)

### ISSUE THREAD

**Issue by yurkobb** [orgzly/orgzly-android#569]
- [x] I have searched for existing issues that may be the same as or related to mine.

Installed Orgzly 1.7.5 via f-droid. Every time I launch the app it immediately terminates.

**Comment by nevenz** [comment]
Which Android version and device is this on?

Any chance you can access adb logs?

**Comment by yurkobb** [comment]
@nevenz It's Android 4.4.2, the device is SM-T211, i.e. Samsung Galaxy Tab 3 7.0 (not rooted). Thanks for the hint on using adb. Here's a snippet from the logs that I think might be informative:
```
E/AndroidRuntime( 9577): FATAL EXCEPTION: main
E/AndroidRuntime( 9577): Process: com.orgzly, PID: 9577
E/AndroidRuntime( 9577): java.lang.NoClassDefFoundError: com.evernote.android.job.v21.PlatformJobService
E/AndroidRuntime( 9577):        at com.evernote.android.job.c.b(JobApi.java:1)
E/AndroidRuntime( 9577):        at com.evernote.android.job.c.d(JobApi.java:3)
E/AndroidRuntime( 9577):        at com.evernote.android.job.h.a(JobManager.java:7)
E/AndroidRuntime( 9577):        at com.orgzly.android.App.onCreate(App.java:6)
E/AndroidRuntime( 9577):        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
E/AndroidRuntime( 9577):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4717)
E/AndroidRuntime( 9577):        at android.app.ActivityThread.access$1600(ActivityThread.java:172)
E/AndroidRuntime( 9577):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1365)
E/AndroidRuntime( 9577):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 9577):        at android.os.Looper.loop(Looper.java:146)
E/AndroidRuntime( 9577):        at android.app.ActivityThread.main(ActivityThread.java:5598)
E/AndroidRuntime( 9577):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 9577):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 9577):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
E/AndroidRuntime( 9577):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
E/AndroidRuntime( 9577):        at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager( 1474):   Force finishing activity com.orgzly/.android.ui.main.MainActivity
```

**Comment by nevenz** [comment]
> Here's a snippet from the logs that I think might be informative:

Thanks, it is.

It looks like it's https://issuetracker.google.com/issues/135210786, found in https://github.com/evernote/android-job/issues/586#issuecomment-504919291

**Comment by yurkobb** [comment]
Thank you for following up. So do I understand correctly that it's a bug in the build system? If so, does it mean Orgzly just has to update the build system component when the fix is usable and update the builds?

**Comment by nevenz** [comment]
Yes, in the way F-Droid builds it it seems, as I can easily reproduce the issue by installing the latest APK from F-Droid on the API 19 emulator, but not by installing the latest APK from Google Play or when building it locally. Although I do see one exception that could be related reported by Google too.

Looking into it now, I'll release the next version when I manage to reproduce the build and fix the issue.

**Comment by nevenz** [comment]
Upgrading Gradle plugin seems to fix the issue.

**Comment by funnyflowerpot** [comment]
On my Android 4.4.4 I had Orgzly 1.7.5 installed and experienced a crash on every launch. I just updated to 1.7.7 and can confirm that Orgzly starts properly now. 

Thank you @nevenz (and all other contributors) for supporting older devices!
