### ISSUE TITLE
Handle media paths relative to notebook sync path

### ISSUE THREAD

**Issue by pstn** [orgzly/orgzly-android#579]
- [x] I have searched for existing issues that may be the same as or related to mine.
Scenario: I have an orgmode document `/home/me/notes/anote.org` on my computer synced via syncthing to my phone with orgzly. I have the following entry:
```
#+Caption: Isn't it beautiful?
#+Name: A nice picture
[[./a/relative/path.jpg]]
```

Now emacs looks for a file in `/home/me/notes/a/relative/path.jpg` to render inline.
When I open the note synced to my phone, the picture is interpreted as relative to my sdcard folder, not the place where the note is synced to, so the file can't be found.

It would be nice to have a mode, where the inline images can be synced as part of a folder without relative links breaking.

**Comment by nevenz** [comment]
This should be #496, thanks.
