### ISSUE TITLE
The import dialog and the add repo dialog are differents

### ISSUE THREAD

**Issue by juacq97** [orgzly/orgzly-android#581]
- [x] I have searched for existing issues that may be the same as or related to mine.

When I open the dialog to import an org file the dialog has many options, including opening and searching other apps. However, the dialog for adding a new repository is much emptier. Is it possible to use the same dialog in both options? Or is it an android behavior? Thank you!

Import org dialog:
![girhub](https://user-images.githubusercontent.com/7623047/62010797-86d08280-b12c-11e9-96ed-1f1d86350b43.png)

Add repo dialog
![Screenshot_20190728-113032](https://user-images.githubusercontent.com/7623047/62010803-994abc00-b12c-11e9-89ec-ed07b94eb3c5.png)

**Comment by nevenz** [comment]
It's an Android thing - first chooser is for a single file, second one is for a directory.  See [this comment](https://github.com/orgzly/orgzly-android/issues/25#issuecomment-383872854). Which items are offered depends on other apps and if they support `ACTION_OPEN_DOCUMENT_TREE`.

**Comment by nevenz** [comment]
I'll close this as there's nothing we can do.
