### ISSUE TITLE
After using the "New note" widget, you do not return to the home screen

### ISSUE THREAD

**Issue by ehahn** [orgzly/orgzly-android#586]
- [x] I have searched for existing issues that may be the same as or related to mine.

Create a "New note" widget. Open Orgzly and put it in the background to ensure the back stack is not empty. Now tap the widget and either create a note or press the back button. You return to the Orgzly screen you previously opened rather than the launcher.

This does not apply to the app shortcut.

**Comment by nevenz** [comment]
I can't reproduce this. Which Android version / device is this?

**Comment by ehahn** [comment]
Aquaris U Lite, Android 7.1.1 with Orgzly 1.7.8 (fdroid)

**Comment by ehahn** [comment]
![screencast](https://user-images.githubusercontent.com/22519/63456644-b171da80-c44f-11e9-81e2-a22c57afc6e4.gif)

**Comment by nevenz** [comment]
Ah, never mind, I was using a New note shortcut. Thanks.
