### ISSUE TITLE
"Share type not set"

### ISSUE THREAD

**Issue by kuba-orlik** [orgzly/orgzly-android#59]
I use Orgzly as the "capture" part of the "capture-refile-archive" cycle.

I've created a CyanogenMod Quick Launch shortcut to Orgzly's `android.ui.ShareActivity` so I can create a new entry whenever I want to note something down. Unfortunately, doing it this way prefills the headline with the text 

> Share type not set

I think it would be cool if the headline stayed empty in this scenario, as I have to remove the text each time (which is tedious to do on a touchscreen).

**Comment by nevenz** [comment]
Can you specify options when launching the activity? Like type (expected to be "text/plain")? Although the next thing you'd run into is "No text" in title, as activity also expects some text or URI passed to it.

That logic that checks for type and extra parameters in the activity is pretty confusing, now that I looked at it again. Definitely needs cleaning up.

In worst case, title should be selected and keyboard opened, so you can start typing immediately, overwriting whatever is in there.

**Comment by kuba-orlik** [comment]
> Can you specify options when launching the activity? Like type (expected to be "text/plain")? Although the next thing you'd run into is "No text" in title, as activity also expects some text or URI passed to it.

I don't have any way to pass additional parameters to the activity. So I guess I'm not passing any options when launching the activity.

> In worst case, title should be selected and keyboard opened, so you can start typing immediately, overwriting whatever is in there.

Well, I wonder if there's any use case where putting a message like "Share type not set" would actually be useful to the user. I think it would be better to just leave the input empty and open the keyboard.

**Comment by nevenz** [comment]
> Well, I wonder if there's any use case where putting a message like "Share type not set" would actually be useful to the user.

Depends how activity is started. Apps should be will sending type, so I think it's useful to know that it's sending app's fault that there's no data which was meant to be shared, not user's.

> I think it would be better to just leave the input empty and open the keyboard.

Yeah, title is misused now to display those messages. Snackbar could be used to briefly display the warning.

Would that be too annoying? It would go away as soon as you start typing.

**Comment by kuba-orlik** [comment]
> Would that be too annoying? It would go away as soon as you start typing.

I think it would be less tedious than having to remove the content of the title :) But maybe there could be a designated place in the ui for such warnings?
