### ISSUE TITLE
Tag completion requires 2 characters to trigger

### ISSUE THREAD

**Issue by lolilolicon** [orgzly/orgzly-android#596]
When adding a tag in the note editor, tag completion is not triggered after the first character has been typed, but only appears after the second. In case you wonder why that would matter, let me just point out that in some languages one character takes a while to produce... so the best would be tag completion at zero character.

**Comment by nevenz** [comment]
Minimum for `MultiAutoCompleteTextView` is 1, so some workaround will have to be used.

Drop-down could be opened on focus, but that might be annoying if the user is just going through the fields, perhaps using a D-pad.

Or, a new button could be added to the right, that will open a drop-down. This button could be later used for a tags dialog (with check-boxes etc.).
