### ISSUE TITLE
Creation of new note from lock screen without unlocking the phone

### ISSUE THREAD

**Issue by sokolgeo** [orgzly/orgzly-android#600]
- [X] I have searched for existing issues that may be the same as or related to mine.
Speed is the name of the game with note taking. 
* In Microsoft Parchi note taking app: in https://www.microsoft.com/en-us/garage/profiles/parchi/ You just create note without unblocking your screen. 
* Google Keep apparently has widget for lock screen - swipe left or right from the edge of the lock screen over the Google Keep lock screen widget - and create new item right in the lock screen. (Lockscreen widgets went away after the update to Lollipop AFAIK, so this could no longer apply to new Android versions).
* Relevant thread of Evernote implementing the same kind of feature: https://discussion.evernote.com/topic/81193-android-lock-screen-create-new-note/

Can Orgzly create new note right from Android lock screen without unlocking the phone?

**Comment by nevenz** [comment]
> Lockscreen widgets went away after the update to Lollipop AFAIK, so this could no longer apply to new Android versions

Yeah, this is not possible anymore. From https://developer.android.com/guide/topics/appwidgets:

> The widgetCategory attribute declares whether your App Widget can be displayed on the home screen (home_screen), the lock screen (keyguard), or both. Only Android versions lower than 5.0 support lock-screen widgets. For Android 5.0 and higher, only home_screen is valid.

**Comment by sokolgeo** [comment]
Thank you for feedback and for looking into this!
I just wanted to attach a Bluetooth keyboard to my phone and add notes by simply typing text into device without unlocking it.
If anyone knows a way to create any note without unlocking the device - please share here!

Until then - this topic considered closed on my side. Thank you
