### ISSUE TITLE
+ button on full-screen Agenda view

### ISSUE THREAD

**Issue by neiljerram** [orgzly/orgzly-android#603]
- [x] I have searched for existing issues that may be the same as or related to mine.

Could we have a + button on the full-screen Agenda view, with the same function as on the widget Agenda view (i.e. to add a note to the configured capture file)?

I often prefer to use the full-screen Agenda when reviewing what I have coming up, because it's bigger, and it would be nice if I could directly add new notes from that screen.

I recommend adding the button in the same place as on the views for particular notebooks. (i.e. bottom right corner)

**Comment by nevenz** [comment]
You can comment on #206. Main question there is how to make the FAB button contextual.
