### ISSUE TITLE
Note detail: extra metadata not being shown first time around

### ISSUE THREAD

**Issue by michael-v2vlc** [orgzly/orgzly-android#605]
When I open detail of note, that has some metadata, which is not shown by default, this metadata is not visible at all until the screen/activity is shown/loaded again (e.g. by minimizing app, or switching between apps).

Repro steps:
1) configure some metadata to be hidden in Settings -> Notes & Notebooks -> Note -> Metadata (e.g. properties)
2) create note and save it (title is not important)
3) open detail of this note and display all metadata (Metadata -> Show all)
4) add property and save note
5) display only selected metadata (Metadata -> Show selected) + "Always show set" switch
6) return to note list
7) show note detail again

Note detail is now missing newly created property. It can be displayed (and then edited) by minimizing app and returning back.

I believe this is not how "Show selected" + "Always show set" metadata feature was supposed to work, but feel free to close the issue, if I'm wrong.

**Comment by nevenz** [comment]
Good catch, thanks.

I was considering removing that whole "Metadata" sub-menu and "selected metadata" feature and always showing everything, now that you can easily fold entire metadata. I wasn't sure if anyone still finds it useful. I guess we should keep it then?

**Comment by michael-v2vlc** [comment]
I use mainly tag, state and scheduled time and definitely note content (+ on occasion CREATED property). And the rest of metadata is just bloating the UI for me (for most of the time), because I need to have easy access to note content. So yes, I do need this feature. Please keep it. If someone does not want to use it, they can set Show all metadata (I presume, it's the default, right?)

(eagerly awaiting new release, the bug is annoying :)
