### ISSUE TITLE
jump to heading in search results

### ISSUE THREAD

**Issue by tkossak** [orgzly/orgzly-android#607]
- [x] I have searched for existing issues that may be the same as or related to mine.

Hi,

Thank you for this awesome app. I'd like to point one feature which I miss a lot while using this app: when I have search results on screen I would like to be able to jump to the heading I click, not to display it's direct content. I often use search to find a heading, but this heading is empty and all the content is in sub headings, which I can't see at all (nor jump to) in search results.

What do you think? Is it possible to introduce such feature?

Thank you.

**Comment by nevenz** [comment]
Left-swipe menu has a button for this. Please reopen if this is not what you're looking for.

Displaying sub-notes in note view and/or #21, or a combination of those two is planned.

**Comment by tkossak** [comment]
This is it, thank you very much!
