### ISSUE TITLE
Capture templates

### ISSUE THREAD

**Issue by ashfaqfarooqui** [orgzly/orgzly-android#608]
- [x] I have searched for existing issues that may be the same as or related to mine.

I want to be able to define a template to capture data within the note content. My specific use-case relates to using ledger. I use [ledger](https://www.ledger-cli.org/) to maintain my finances. And, I (usually) need to enter my transactions in a fixed format manually, such as: 
```
2015/10/12 Exxon
    Expenses:Auto:Gas         $10.00
    Liabilities:MasterCard   $-10.00
```

I would like it if, I could define a template and focus on just filling in the details and let Orgzly take care of formating and adding the date. 
An added feature would be the ability to define a lists to help with autofilling.

**Comment by nevenz** [comment]
That's the idea with #80 (started with #466).

I'll close this issue and we should go through all the referenced tickets in #80.
