### ISSUE TITLE
Feature request: import property drawers

### ISSUE THREAD

**Issue by felixplesoianu** [orgzly/orgzly-android#61]
Since Orgzly supports property drawers anyway, it would be very useful if it also parsed them when importing an .org file. Thank you.

**Comment by nevenz** [comment]
That would be a bug if it doesn't. :)

What are you seeing exactly, can you post an `.org` snippet or something?

**Comment by felixplesoianu** [comment]
Never mind, I checked the full Org Mode manual again, and it turns out property drawers are supposed to follow a headline immediately, with not even an intervening blank line. Sorry to bother you, I'd been mostly working off the compact guide, which skips over such "minor" details. For what it's worth, this is my reference file: https://github.com/felixplesoianu/ramus2/blob/master/cloak.org -- it's written by hand. targeting a much looser parser.

**Comment by nevenz** [comment]
Cool, yeah, that's kinda new(-ish).
