### ISSUE TITLE
Set default notebook using a drop-down list

### ISSUE THREAD

**Issue by arkoinad** [orgzly/orgzly-android#612]
- It would be nice to have a setting to set where the notes in quicknote from the widget.
Currently all the notes entered in the quick note widget land in the first notebook. t would be nice if there were a setting to set where those notes went by default.

**Comment by nevenz** [comment]
There's already Settings / Note & Notebooks / Default notebook. Does that work for you?

**Comment by abhixec** [comment]
Ah you are right. That works it turned out that the note name was wrong maybe it would be nice to have drop down of all notebooks as opposed to typing it(since it is error prone)?

**Comment by komali2** [comment]
BTW, I'm not sure if this is perhaps a new bug, but I have my default notebook set as "Inbox," but it appears when I click "+" in the search widget, it opens the "create note" UX with the notebook titled "508" selected, with my "sort order" setting set as "alphabetical," thus, it appears it selected the first notebook in that sort order. If I change "sort order" to "modified," it selects my "projects" notebook by default when trying to create a new note using the widget, which to me lends further evidence to this theory.

I'm happy to investigate, I've added it to my todo, but it will take me time as I'm not at all familiar with android apps.
