### ISSUE TITLE
Graying out issues with ARCHIVE tag the same way as DONE

### ISSUE THREAD

**Issue by sokolgeo** [orgzly/orgzly-android#615]
Right now archived issues (the ones with ARCHIVE tag) are grayed out by default in org-mode, but not in Orgzly.
As a result in all Orgzly list views and reports the archived issues look same as active ones, making it hard to use Orgzly.

Workarounds could be: 
# mark all Archived issues as DONE, so Orgzly nicely greys them out in all reports. 
# Or archive issues into separate archive file, which then store outside of Orgzly repositories to prevent Orgzly from displaying archived issues at all. But this also kills Orgzly search, so no-go.

Could we please have simple switch in settings "Grey our issues with ARCHIVE tag" ?
I understand that this is not the most elegant solution, but it will make use of Orgzly easier for org-mode users.

**Comment by nevenz** [comment]
I think they should be excluded from the search as well.

**Comment by sokolgeo** [comment]
No, no, no! Exclusion of :ARCHIVED: tag notes from search is easy and
already in place: just put .t.ARCHIVED into search criteria and you get
search results without archived items.

I am specifically talking about the situation when I do want to see all
notes, just graying out archived ones in the same manner as DONE to
easier scan through the search results and through normal list views.

**Comment by nevenz** [comment]
> No, no, no! Exclusion of :ARCHIVED: tag notes from search is easy and
already in place: just put .t.ARCHIVED into search criteria and you get
search results without archived items.

Right, but Org mode users might be used to not having search results include archived tasks. It might be easy to include `.t.ARCHIVE`, but I think that should be done implicitly anyway.

> I am specifically talking about the situation when I do want to see all
notes, just graying out archived ones in the same manner as DONE to
easier scan through the search results and through normal list views.

I agree with this, my above suggestion isn't a replacement for this feature.

**Comment by sokolgeo** [comment]
Yes, but in org-mode I have 
1. configuration option to set up if I want Archived issues be shown by default
2. super quick shortcut to display Archived items and to hide them again - on the fly
With touch interface I was only thinking about simple and quick implementation. Because how to implement more complicated p.p.1,2 above schema in user-friendly way - I have no clue!
