### ISSUE TITLE
Tag inheritance bug

### ISSUE THREAD

**Issue by keithcrone** [orgzly/orgzly-android#63]
I'm having a problem in a few searches where tags are being inherited multiple times, I BELIEVE based on how deep into an outline the search results are (tags are duplicated 7x for items that are 7 levels deep).

Unfortunately, I can't figure out what is causing it because it doesn't happen on every search, just a handful.

**Comment by keithcrone** [comment]
A couple of screenshots to see it

https://drive.google.com/file/d/0B719tcMMYHVFdVJqYmk4LWE1U0k/view?usp=drivesdk

https://drive.google.com/file/d/0B719tcMMYHVFUU9Cd25oR2tHMW8/view?usp=drivesdk

**Comment by nevenz** [comment]
I can't reproduce this yet, when I create the notebook with same notes.

You mention notes 7 levels deep where you see this issue too -- did you create notebook from screenshots after that? And you can still reproduce the issue with it? What about if you start with no notebooks?

Thanks!

**Comment by nevenz** [comment]
Ok, I've just reproduced it after moving one of the "weekly" notes down. Fun stuff. :)

I assume you did some moving, cutting or pasting perhaps (in the small posted notebook).

**Comment by keithcrone** [comment]
Actually no. Those few entries were just me experimenting with getting away from Todoist and trying to manage all information from Orgzly. The notebook is technically new as I had created it 30 minutes before and started playing with searches.

The one that goes 7 levels hasn't been moved or adjusted in forever. It's a large list I use to monitor information in a small business I run. Recreating it would probably take me a while.

But while you're on the subject of moving entries, after posting this I did notice a few instances where new entries were being put in the wrong place. For example, if I long press on an entry like Misc (in this example) and Add Child, the new entry is placed under Work and I have to move it up. Again, it doesn't happen everywhere, just a few entries

**Comment by nevenz** [comment]
> The notebook is technically new as I had created it 30 minutes before and started playing with searches.

Hmm, so not even deleting? Just creating new notes (and editing for setting scheduled time and tags)? I'll keep looking then.

> For example, if I long press on an entry like Misc (in this example) and Add Child, the new entry is placed under Work and I have to move it up.

That sounds even worse. 😄  It actually becomes the child of Work? How do you move it back under Misc?

**Comment by keithcrone** [comment]
I recreated the tag inheritance thing pretty easily now. In these screenshots:
* create A, B, C, each with children 1,2,3 and various corresponding tags
* did a search, no problems
* created ABC and moved everything underneath it
* search shows tag trouble
So maybe when I initially was creating those few entries in my real notebook, I moved a couple under a parent (like Personal) and then kept creating from there (sounds reasonable).

https://drive.google.com/file/d/0B719tcMMYHVFWHktcFJ6N0V6M0U/view?usp=drivesdk

https://drive.google.com/file/d/0B719tcMMYHVFMXJjMG1SOHk3YkU/view?usp=drivesdk

I can't get the other bug to happen here but it happens every time in the other notebook.
* long press Personal
* + New Under
* entry is a child of Misc
To move it, I have to use the arrows to move it out to the parent level, up to the correct position, and then back down to the child level

**Comment by nevenz** [comment]
> I recreated the tag inheritance thing pretty easily now
> So maybe when I initially was creating those few entries in my real notebook, I moved a couple under a parent (like Personal) and then kept creating from there (sounds reasonable).

Great -- bug is due to inheritance relationship not being removed when cutting the notes (move is just cut & paste basically), so when they are pasted, duplicate relationships appear.

> I can't get the other bug to happen here but it happens every time in the other notebook.

I managed to reproduce this one too, in notebook created as you mentioned (creating few notes first, then moving them under one, etc.).

Sweet, I'll write tests to cover these, they'll be very useful for any related changes in the future too.

I'll see to push the new beta by tomorrow.

Thanks!

**Comment by nevenz** [comment]
v1.4.13-beta.2 is pushed to Google Play and APK is also available at https://github.com/orgzly/orgzly-android/releases/tag/v1.4.13-beta.2

Let me know if you're still seeing any issues.

**Comment by keithcrone** [comment]
All fixed after I cleared the database and reloaded.
