### ISSUE TITLE
No syncing if no any file change in notebook of webDAV repo

### ISSUE THREAD

**Issue by NiceFeather** [orgzly/orgzly-android#630]
- [ ] I have searched for existing issues that may be the same as or related to mine.

I found it did sync while swiping down the screen even no any file change in notebook of webDAV repo, maybe this could cause more problems. Is this issue a bug, or an item need to improved?

**Comment by nevenz** [comment]
What do you mean by syncing though?

Sync icon in status bar indicates that sync service is running, which is done to check for changes. Icon is required by Android for foreground services. If there are no remote changes, you should just get "No change" for all notebooks in Notebooks view.

Is there anything different you're seeing?

**Comment by NiceFeather** [comment]
Considering a variety of situations, remote notes may be modified by third-party applications, so you have to connect to the server for file comparison to get the latest version. I've fully understood the above, and close this question right now, thank you very much for your reply.

**Comment by NiceFeather** [comment]
There will cause a conflict and need a merge operation but if local and remote notes are happen to both modified.
