### ISSUE TITLE
Question: Syncing to Dropbox

### ISSUE THREAD

**Issue by Subspecies** [orgzly/orgzly-android#637]
Did I try to do this wrong? I want to use Orgzly on another device. I synced from my first device to Dropbox. From my second device, I don't see how I would sync to that file, other than to type in (by hand) the name of the Dropbox directory where it resides. This failed. Are there some step-by-step instructions for this? Am I trying something that does not work? Should I just manually load the files? Thanks for any help!

**Comment by nevenz** [comment]
How did you sync from your first device?

You need to create a Dropbox repository (Settings / Sync), and yes, enter the path to the directory where your org files are located.

Are you getting some error when you say that it failed?

**Comment by Subspecies** [comment]
I just deleted the manually installed notebooks, so that I can get a fresh start at trying to sync. But the second device still shows the notebook and its contents. Is there another step needed in order to eliminate this notebook and ensure that it doesn't interfere with my attempt to sync with it in Dropbox?

To be clear, my attempt to sync with Dropbox from my first device was successful. So my problem is getting my second device to sync. I manually typed in the directory, as requested by Orgzly, and this did not do anything.

**Comment by Subspecies** [comment]
*JOY* The notebooks came up, including their contents. (I'm pretty sure that this is the linked version, because there is a notification for BOTH the notebooks I have on Dropbox that gives the full address including the file name, and that is more than what I had typed in (I had not typed in the file name when Orgzly asked me to type in the Dropbox sync location.) 

I have no idea why the link \BACKUP\ORGZLY worked this time and not the first time I tried it.

-- For Reference --

To be clear, my attempt to sync with Dropbox from my first device was successful. So my problem was getting my second device to sync. I had manually typed in the directory, as requested by Orgzly, and this did not do anything. (But my second attempt worked, and I don't know what I did differently.)

To make sure there would be no interference from the notebooks that I had manually installed, I deleted them from the device (using Windows Explorer on my PC via the USB connection) AND I long-clicked and deleted the notebooks on the device.

**Comment by nevenz** [comment]
> I had manually typed in the directory, as requested by Orgzly, and this did not do anything. (But my second attempt worked, and I don't know what I did differently.)

You did actually tap the Sync button, right? Since auto-syncing is not supported for Dropbox yet, even if enabled.

**Comment by Subspecies** [comment]
Yes, thanks, I was not relying on auto-syncing. It's very nice to have this on a phone now so I can input things on the fly. By the way, I wasn't sure if the screen would be big enough, but it's not bad.
