### ISSUE TITLE
Location of Searches?

### ISSUE THREAD

**Issue by Subspecies** [orgzly/orgzly-android#639]
I looked in the instructions, but don't see a location for searches. I have synced a second device to my notebooks, but the searches I created don't show up. Do have have to manually create them, or did I miss part of the sync process, or is there a location I should manually transfer the searches from? Thanks!

**Comment by nevenz** [comment]
Syncing of searches is not supported yet. But you can export them to a JSON file, copy the file manually to a different device and then import them.

**Comment by Subspecies** [comment]
Oh, I just thought it was me, lol. Good to know. In my case, it isn't a big deal to add manually. At least I'm not fishing around for a feature that isn't there yet. Thanks for all you extraordinary work. I rated this five stars, and use it because all the other software in this genre that I examined had very unintuitive limitations.

**Comment by NiceFeather** [comment]
We all think this is a good feature requirement, And nevenz has labelled it as a new feature, you can reopen it, Thank you. @Subspecies

**Comment by awalker4** [comment]
Syncing the searches would be a great feature, especially if the json can be loaded alongside the other notebooks. I change up my searches pretty often, and I'd love to be able to do that right out of my org-agenda directory. Seems that would give you syncing for free. 

Thanks for the amazing app!
