### ISSUE TITLE
Displaying/parsing TAB whitespace in heading content

### ISSUE THREAD

**Issue by tdkohlbeck** [orgzly/orgzly-android#64]
I Love Orgzly! But this minor issue is bugging me, and I'm not sure if it's something that should be changed on my end (emacs/settings) or on Orgzly's end.

Basically, when I issue an org-mode command in emacs that adds metadata (e.g. clocking times), it will automatically insert tabs to align itself below the heading (see "with tab" example in first photo). But this doesn't look great in Orgzly (see "with tab" example in second photo).

Is this something that Orgzly should be responsible for, or is there some formatting option I that I should be using that mitigates this issue?

I didn't screenshot my clocking example, but here's different behaviors in both applications:

## Emacs
![org-mode-tab-example-emacs](https://cloud.githubusercontent.com/assets/7794722/24933964/f9fec9b8-1ecd-11e7-8174-fb7ac00745f4.png)
## Orgzly
![org-mode-tab-example-orgzly](https://cloud.githubusercontent.com/assets/7794722/24933998/1c707460-1ece-11e7-89c6-16bf9bbae387.png)

**Comment by nevenz** [comment]
It's actually important if you're talking about CLOCK or some text.

If it's note content (everything below heading and last supported special keyword), what you're seeing in "with tab" is expected. Orgzly won't trim content's whitespace.

The thing is that parsing CLOCK is not done yet, so it's simply considered part of the content, so it's left alone, per above.

**Comment by nevenz** [comment]
If you're seeing this for CLOCK only, you can open a new issue for supporting its parsing.

If not, you can re-open this one.
