### ISSUE TITLE
org-set-column doesn't indent tags consistently

### ISSUE THREAD

**Issue by bbo2adwuff** [orgzly/orgzly-android#641]
Indentation does not work as expected with org-set-column.

How to reproduce:

In emacs (org 9.1.9) I save following org:
```Org
* Test                                                              :taghead:
** sub1                                                              :tagsub:
*** subsub1                                                       :tagsubsub:
*** subsubsub1                                                 :tagsubsubsub:
*** subsub2                                                       :tagsubsub:
    Test content
** TODO sub2                                                         :tagsub:

* Test
** sub1
** sub2                                                              :tagsub:
```
As you can see already visually, in emacs I get correct line length of 77 when there is a tag in the line:
```bash
awk '{print length}' org_test_tags.org 
77
77
77
77
77
16
77
0
6
7
77
```

After saving it in orgzly (1.8.2) I get:
```Org
* Test                                                              :taghead:
** sub1                                                             :tagsub:
*** subsub1                                                     :tagsubsub:
*** subsubsub1                                               :tagsubsubsub:
*** subsub2                                                     :tagsubsub:
    Test content
** TODO sub2                                                        :tagsub:
* Test
** sub1
** sub2                                                             :tagsub:
```

And here is the bug, too short lines with tags:
```bash
awk '{print length}' orgzly_test_tags.org 
77
76
75
75
75
16
76
6
7
76
```

**Comment by bbo2adwuff** [comment]
I forgot to mention that org-tags-column is set to -77.

**Comment by nevenz** [comment]
Do you use `org-indent-mode` in Org mode?

What's your "Adjust based on indent mode" preference in Orgzly? You would get that if it's enabled.

**Comment by bbo2adwuff** [comment]
Wow, after playing around with the `org-indent-mode` I am not so sure if I understand what is happening here

The file `org_test_tags.org` that I copy to my phone and use for diff I created in emacs (org 9.1.9).

### Indentation per level set to 2:

```
diff -s org_test_tags.org org_test_tags_ind2.org

2,5c2,5
< ** sub1                                                              :tagsub:
< *** subsub1                                                       :tagsubsub:
< *** subsubsub1                                                 :tagsubsubsub:
< *** subsub2                                                       :tagsubsub:
---
> ** sub1                                                             :tagsub:
> *** subsub1                                                     :tagsubsub:
> *** subsubsub1                                               :tagsubsubsub:
> *** subsub2                                                     :tagsubsub:
7,8c7
< ** TODO sub2                                                         :tagsub:
< 
---
> ** TODO sub2                                                        :tagsub:
11c10
< ** sub2                                                              :tagsub:
---
> ** sub2                                                             :tagsub:
```
Same behaviour as above (so I am able to reproduce the issue when creating a new file).

### Indentation per level set to 1:
```
diff -s org_test_tags.org org_test_tags_ind1.org

5a6
> 
8d8
< 
```
Indentation okay, but I'd say the 5a6 new line is not desired.

### Indentation per level set to 1:
```
diff -s org_test_tags.org org_test_tags_ind0.org

5a6
> 
8d8
< 
```
Surprisingly gives me exactingly the same result as indentation of 1.

### `org-indent-mode` off

```
diff -s org_test_tags.org org_test_tags_ind_off.org

8d7
< 
```
This seems to work for my example :)

But still I am not sure if I get my head around this issue :confused:

**Comment by nevenz** [comment]
An additional star in a sub-note contributes to the indentation, which is why you see changes only when setting `org-indent-indentation-per-level` to 2 or greater.

This preference shouldn't be affecting head/content spacing. "sub2" has no content, so the empty line (line 8) is removed.

**Comment by bbo2adwuff** [comment]
Thanks for the explanation!

So I think this can be closed after I got the indentation working, though at the first moment it was not very intuitively... But that's probably the way it's when you offer many options.

And a big thanks for writing orgzly :star2:
