### ISSUE TITLE
Add support for pinning entries

### ISSUE THREAD

**Issue by GuiltyDolphin** [orgzly/orgzly-android#645]
Possibly related: #107

It would be helpful if there were support for pinning particular entries (in the same manner as OpenTasks), wherein a pinned entry will always display as a notification until it is unpinned. We should be able to unpin directly from the notification.

Currently, to achieve something similar to this, one must use scheduling, which I'm not a huge fan of doing as I often just want to make a note easily accessible for a while, then unpin it when done, and not have to remember to unschedule (or risk wondering why a particular action got scheduled later on).

**Comment by nevenz** [comment]
> Possibly related: #107

What's the difference here, except perhaps in the way notes are selected (which could be done by configuring a set of tags to use for it)?

**Comment by GuiltyDolphin** [comment]
I wasn't 100% sure what the issue was suggesting---if it is suggesting the same feature, then feel free to close this as duplicate @nevenz

Would #107 allow us to go into a note and press a button to pin the entry? That's the kind of functionality I'm thinking.

**Comment by nevenz** [comment]
Sure, this issue is linked now, so we'll revisit when doing #107.
