### ISSUE TITLE
Searches Fail with custom note states 

### ISSUE THREAD

**Issue by vv111y** [orgzly/orgzly-android#65]
I use -- 

[.] [-] [?] | [X]  

for my todo states. 
The searches don't work with these. Other behaviour is good. 
Any ideas?
Also, thank you so much for this amazing app

**Comment by nevenz** [comment]
I can't reproduce this, can you post a search query you are using?

**Comment by vv111y** [comment]
State searches:
`i.todo
.i.todo`

**Comment by nevenz** [comment]
"todo" is not a special keyword - it doesn't represent all todo-type states. (Though that would be useful and is [planned](https://github.com/orgzly/documentation/blob/master/searching-proposal.org).)

The actual state goes after "i". So:

* `i.[.]` returns all notes with `[.]` state
* `.i.[.]` returns all notes which don't have that that state

**Comment by vv111y** [comment]
Ah, got it. Thanks. 
Closing
