### ISSUE TITLE
Reminders at midnight

### ISSUE THREAD

**Issue by BartG95** [orgzly/orgzly-android#651]
https://github.com/orgzly/orgzly-android/blob/a7d2a4ddec6f2fa974e8aaceb8c7ac213088c801/app/src/main/java/com/orgzly/android/reminders/ReminderService.kt#L396

Is this line responsible for the fact that notes with only a day set, have their reminders at 9:00 AM?
If so, wouldn't it be more logical to make that 00:00 AM? (If I am not mistaken, that was the original behavior).

Context: I usually do not set a time for my notes, so I expect them to either:
* Not have a reminder (if want a reminder, I will set a time);
* Or a reminder at midnight.

The thing is, my phone is in DND mode at midnight, so reminders at midnight don't disturb me. My phone stops DND mode at 7:00 AM, so the rather useless reminders at 9:00 AM do disturb me.
You might argue that I could set my phone to hold DND mode till 9:00 AM, but then notes that do have a time (the urgent ones, for me) won't come thru. (I never have reminders before 7:00 AM, so till that time DND mode is fine.)

**Comment by ScottFreeCode** [comment]
Early morning makes more sense than midnight to me, personally, as just a fellow Orgzly user. When would I ever want to be notified at midnight? While 0 time into the day is "logical" in a purely abstract sense, it doesn't seem reasonable (to me anyway, assuming I'm not missing some other use case) for reminders unless one is using midnight as a workaround for no reminder at all. (Not everyone even turns their phone to DND at night either, for one reason or another; we'd have to do some kind of survey or test to figure out whether that would be more annoying than 9 for more people than 9 is annoying.)

That said, I think the root of the matter is that 9 may or may not be first thing in the morning for any given person. **Being able to set the default time** would allow you to set it before 7, me to set it to whatever time I get up and do want to be notified (right now I have several reminders set to when my alarm goes off), etc. (I'm not sure whether there's already an issue for that, but I know I saw a comment about planning for it in the source when I was looking into something else, a while back.)

**Comment by andipabst** [comment]
https://github.com/orgzly/orgzly-android/blob/a7d2a4ddec6f2fa974e8aaceb8c7ac213088c801/app/src/main/java/com/orgzly/android/reminders/ReminderService.kt#L395-L396

Actually, this is in the code as a TODO in the previous line. 
As a user I'd also like to be able to set this from the preferences. It could be added in this settings screen: https://github.com/orgzly/orgzly-android/blob/master/app/src/main/res/xml/prefs_screen_reminders.xml

**Comment by nevenz** [comment]
> Not have a reminder (if want a reminder, I will set a time)

We do need a preference to ignore daily reminders as well. Preference for choosing the time would then depend on it.
