### ISSUE TITLE
Scheduled tasks don't appear in the Agenda

### ISSUE THREAD

**Issue by Ypot** [orgzly/orgzly-android#665]
If I add a time stamp to a scheduled task, the task appears 2 times on the [Agenda](http://www.orgzly.com/help#search-agenda) . 
If I delete its time stamp, leaving alone the schedule time, it doesn't appear on the [Agenda](http://www.orgzly.com/help#search-agenda)  at all.

**Comment by nevenz** [comment]
How does a query look like? It seems there's a bug when `o.e` is used (at least).

**Comment by Ypot** [comment]
> How does a query look like? It seems there's a bug when `o.e` is used (at least).
(b.1 or b.2 or b.3 or b.4) o.e o.s ad.31

**Comment by nevenz** [comment]
3d91846c
