### ISSUE TITLE
Multiple elements cut/copy and paste 

### ISSUE THREAD

**Issue by falematte** [orgzly/orgzly-android#67]
It would be really useful to be able to cut/copy multiple headers at the same time.

**Comment by mkaito** [comment]
Or moving multiple elements at once.

**Comment by snosov1** [comment]
I've looked through the code and it seems like this is already supported, but not enabled. If I enable the cut and paste buttons in the actions menu - it seems to work alright:
```
    private static final int[] ITEMS_HIDDEN_ON_MULTIPLE_SELECTED_NOTES = {
            R.id.book_cab_new,
            //R.id.book_cab_cut,
            //R.id.book_cab_paste,
            R.id.book_cab_move
};
```

There are still some corner cases, like, when you select items from different hierarchy levels they might form up an "unintended" hierarchy after pasting. But put that aside - it seems to be working fine.

Is there any particular reason this is not enabled?

**Comment by nevenz** [comment]
> There are still some corner cases, like, when you select items from different hierarchy levels they might form up an "unintended" hierarchy after pasting. But put that aside - it seems to be working fine.

Have you tried moving the pasted notes around, like promoting and demoting?

It might look OK, but it's not pasted right.

**Comment by snosov1** [comment]
Yeah, it seems to work in "simple" cases, but I've found at least one issue - if you select unrelated level1 (l1) and level2 (l2) headings and paste them under some other heading - it first looks like there's a l1->l2 hierarchy, but after you fold and unfold the top heading, l2 just disappears.

Do you have a plan to fix/enable this?

**Comment by nevenz** [comment]
> Do you have a plan to fix/enable this?

I do have it for v1.6.3 currently, but I might push it to the next version. I'll check what's the effort, that `PasteNotesAction` is not a fun place to be in.

**Comment by snosov1** [comment]
It looks like the "only" thing that needs to be done - is to change the level of the pasted notes to the single (correct) value and adjust their ancestors accordingly. But looking over all this SQL stuff, it doesn't seem that straightforward =)

Anyway, thanks for the clarification.

**Comment by Nadrieril** [comment]
Is this still planned for a future version ? It would be a huge usability boost for me; I wouldn't even mind the indentation glitches if it worked.

**Comment by nevenz** [comment]
> Is this still planned for a future version ? It would be a huge usability boost for me; I wouldn't even mind the indentation glitches if it worked.

It is, I need it badly too. I'm finishing a big refactoring, so things have been slow lately.
