### ISSUE TITLE
Use Locale-Specific Date/Time Format

### ISSUE THREAD

**Issue by andipabst** [orgzly/orgzly-android#671]
- [x] I have searched for existing issues that may be the same as or related to mine.

Currently, all dates and times are formatted `yyyy-MM-dd EEE HH:mm`. But for my locale it is common to use `EEE, dd.MM.yyy HH:mm`.

It would be nice, if Orgzly would use my own locale-specific format, which I am already used to see.

**Comment by nevenz** [comment]
Where do you see this non-locale format?

**Comment by andipabst** [comment]
I noticed it in two places: in reminder notifications and the title of the date selection on a note. Especially in the notifications it was quite irritating.

**Comment by nevenz** [comment]
> I noticed it in two places: in reminder notifications and the title of the date selection on a note. 

The latter reflects Org mode's format and since it can include repeater or delay/warning period, it's probably best it stays the same.

But the one in notification could be changed.

**Comment by nevenz** [comment]
Actually never mind - times in notifications include all fields too and times in note view or list use local-specific format (and can still include the repeater). So we should probably be consistent and change this everywhere to local-specific time.
