### ISSUE TITLE
Holidays on the agenda

### ISSUE THREAD

**Issue by Ypot** [orgzly/orgzly-android#678]
I am using the  built in agenda. It’s cool. 
On my init.el I have added my holidays. How would you recommend to have those days on orgzly’s agenda?

Example in the init.el:
(setq holiday-other-holidays '(
			       (holiday-fixed 1 1 "Servi Fest")
) )

**Comment by nevenz** [comment]
You'd have to convert those to tasks with perhaps plain timestamps. I don't see Orgzly supporting such syntax.
