### ISSUE TITLE
No notification when recurring task trigged

### ISSUE THREAD

**Issue by hxdq** [orgzly/orgzly-android#679]
- [x] I have searched for existing issues that may be the same as or related to mine.

**Comment by nevenz** [comment]
How does the used time look like? Notification fire for the main time (ignoring repeater).

**Comment by hxdq** [comment]
> How does the used time look like? Notification fire for the main time (ignoring repeater).
Since recurring tasks appear in agenda, why can't make it to fire a notification?

**Comment by nevenz** [comment]
> Since recurring tasks appear in agenda, why can't make it to fire a notification?

Preference could be added for that.

**Comment by nevenz** [comment]
I thought this issue is for adding that preference, reopen if you still need it.

**Comment by titibandit** [comment]
I am interested in this feature: that a reminder is fired for each instance of a recurring task.
Since they already appear in the agenda through searches, it would make sense for every occurrence of a recurring task to fire a reminder.
A preference to activate that would be a good solution.
