### ISSUE TITLE
Attachment links syntax

### ISSUE THREAD

**Issue by Ypot** [orgzly/orgzly-android#680]
There is a kind of link that I think it could be very useful for orgzly, because of its relative path, its unique ID and its function to show inline images.

The syntax would be this one, and maybe orgzly not only could read it, but could generate it by itself when sharing files with the app. This one would show the image.jpg in the folder determined by the ID with a relative path:

* Heading  :ATTACH:
:PROPERTIES:
:ID:       82bd9766-d8bd-418f-a5bb-5c569e488915
:END:
**[[attachment: image.jpg]]**

**Comment by nevenz** [comment]
Is this different from #1 ?

**Comment by Ypot** [comment]
#1 sorry
