### ISSUE TITLE
Lowercase title isn't recognized

### ISSUE THREAD

**Issue by Nebucatnetzer** [orgzly/orgzly-android#689]
- [x] I have searched for existing issues that may be the same as or related to mine.

When the #+title: preamble is in lowercase Orgzly doesn't display it.

**Comment by nevenz** [comment]
Thanks.

You'll need to sync (load) notebook or just edit/save preface for the title to be updated in the database. I don't think adding a migration for this is worth it.

**Comment by Nebucatnetzer** [comment]
Thank you for fixing it so quickly.
I don't mind if there's no migration for it since I converted my files all with sed.
But now I can reapply the setting to Emacs :).
