### ISSUE TITLE
Links without protocols not rendering as links in widget

### ISSUE THREAD

**Issue by GuiltyDolphin** [orgzly/orgzly-android#696]
- [X] I have searched for existing issues that may be the same as or related to mine.

It appears that if you strip the protocol from a link in a header, the link no longer displays as clickable in the notes widget view. For example, try `[[duckduckgo.com][DuckDuckGo]]` versus `[[https://duckduckgo.com][DuckDuckGo]]`---the first does not render as a link, whereas the second does.

**Comment by nevenz** [comment]
> It appears that if you strip the protocol from a link in a header, the link no longer displays as clickable

This is expected. There's no way to reliably detect that the string it an URL if the scheme is missing.

> in the notes widget view

Support for links in widgets is not complete. I don't think custom spans are supported in [RemoveViews](https://developer.android.com/reference/android/widget/RemoteViews). I haven't been able to make those work in a widget.

**Comment by GuiltyDolphin** [comment]
> > It appears that if you strip the protocol from a link in a header, the link no longer displays as clickable
> 
> This is expected. There's no way to reliably detect that the string it an URL if the scheme is missing.

Okay, I've played around with Org a bit more and I'm inclined to agree with you here. Whilst Org will highlight such links (`[[duckduckgo.com]]`), activating the link will prompt to create a heading (my guess is that without the protocol it'll just treat everything as a heading reference).

> > in the notes widget view
> 
> Support for links in widgets is not complete. I don't think custom spans are supported in [RemoveViews](https://developer.android.com/reference/android/widget/RemoteViews). I haven't been able to make those work in a widget.

So is the plan to one day have any `[[link][description]]` and `[[link]]` links display in the widget as such, and be clickable (with possibly an error action if the link would be treated by Org as a heading, and such a heading doesn't exist)?

**Comment by nevenz** [comment]
> So is the plan to one day have any [[link][description]] and [[link]] links display in the widget as such, and be clickable (with possibly an error action if the link would be treated by Org as a heading, and such a heading doesn't exist)?

If possible, yes. I think this is a duplicate of #565?

**Comment by GuiltyDolphin** [comment]
@nevenz I think you're right. Closing as a duplicate of #565.
