### ISSUE TITLE
Add support for progress indicators in lists and headings

### ISSUE THREAD

**Issue by GuiltyDolphin** [orgzly/orgzly-android#699]
- [X] I have searched for existing issues that may be the same as or related to mine.

Org supports many useful features with checkboxes, including the ability to track how far through completing a list we are (see https://www.gnu.org/software/emacs/manual/html_node/org/Checkboxes.html for more information).

I'm requesting that we support the following (preferably in both headings and lists, though I realise these may need to be done separately, depending on Orgzly infrastructure):

- support for `[%]`-style markers, which indicate the current percentage progress
- support for `[/]`-style markers, which indicate the current absolute progress
- support for `[-]` and `[X]`, i.e., that a checklist item automatically gets marked with `[-]` if _some, but not all_ of its children are complete, then to `[X]` when all of its children are complete.

These should update whenever a checkbox is ticked/unticked in view mode.

**Comment by nevenz** [comment]
This is #311.

**Comment by GuiltyDolphin** [comment]
Yup, thanks---that didn't come up in my search.
