### ISSUE TITLE
File link related breaks

### ISSUE THREAD

**Issue by lingnand** [orgzly/orgzly-android#700]
- [x ] I have searched for existing issues that may be the same as or related to mine.

Original discussion here: https://github.com/orgzly/orgzly-android/issues/360#issuecomment-562863010

Just thought to log this properly so as not to lose it.

I've also made a few more observations since we had the discussion last time. In summary:

- URL-encoded link breaks
- filename with `.` inside also breaks
- folder does not work?

**Comment by nevenz** [comment]
> filename with . inside also breaks

Clicking on `file:File%20With%20.Space.pdf` from app tries to open `File%20With%20.Space.pdf` for me, which Org mode does too. What do you see exactly?

> folder does not work?

This could be probably supported. You can open a new issue for it.

**Comment by lingnand** [comment]
Sorry for the late reply - just got around to testing it again today, you are right, names with `.` inside actually works fine for me now. I can't remember how I got into that in the first place anymore. Thanks for looking into it.

Re opening folder - I'll open a new issue as suggested.
