### ISSUE TITLE
Share defaults to lexicographically first notebook, not the chosen default

### ISSUE THREAD

**Issue by garrison** [orgzly/orgzly-android#701]
- [X] I have searched for existing issues that may be the same as or related to mine.

First, thank you for Orgzly.  I am using version 1.8.2, via F-Droid.  I have four notebooks, named A, B, C, and D.  I have selected C as my "Default notebook" in the settings (under "Notes & Notebooks").  However, when I select "share" to orgzly from another app, A is initially selected as the target of the note, presumably because it appears first in lexicographic order.  However, I would prefer if C were selected instead, as I have explicitly chosen that to be my default notebook.

**Comment by nevenz** [comment]
I can't reproduce this. Does notebook `C` exist? And do you just have `C` in Settings, not `C.org` for example?

**Comment by garrison** [comment]
Thanks.  Making sure the name of C was given precisely in Settings fixed it.  I had earlier renamed this notebook, and did not notice that the Settings still pointed to the old name.  I was not expecting this to be a free text entry -- thought that instead it would be a radio button, so did not even consider that the notebook listed there might not exist.

**Comment by nevenz** [comment]
>  I was not expecting this to be a free text entry

Yeah, that was a quick&dirty implementation, see #612.
