### ISSUE TITLE
s.now does not display todays schedules

### ISSUE THREAD

**Issue by iexos** [orgzly/orgzly-android#704]
Hi, there is a regression introduced in 1.8.3 which messes with my system. I would be happy for a fast hotfix :)

Filter:
```
s.now i.todo
```
Create new task with `TODO`, scheduled today (no time), it is not visible with this filter. Add repeat `.+1w` and it becomes visible. Clearly not intended.

**Comment by nevenz** [comment]
I can't reproduce this. Note that `s.now` is equivalent to `s.lt.now`. So it should return all notes with scheduled time in the past. Which should be the case for any new note scheduled for today.

Can you post the note in org format? Or a screenshot? Thanks!

**Comment by iexos** [comment]
Now i cannot reproduce it either...:confused:
When it happened earlier, it was possible to change visibility by just adding the recurrence.

I will reopen if it reoccurs, sorry for the noise

**Comment by iexos** [comment]
Ok, it happened again, but the other way around wrt repeating:

![notebook](https://i.imgur.com/uZqLmfh.png)

![search](https://i.imgur.com/tQ8S2Y4.png)

**Comment by janws** [comment]
I ran into this issue today as well with 1.8.4. It is there with a new notebook and one new note, but it is not consistent. Some notes do get displayed. In Emacs the agenda works as expected and the .org does not contain any spurious times later that day.

**Comment by nevenz** [comment]
Thanks. I've been using `s.now` for a while and managed to reproduce it.
