### ISSUE TITLE
Improve editing

### ISSUE THREAD

**Issue by dorneanu** [orgzly/orgzly-android#706]
Hi! First of all thank you very much for making ORG mode available for Android as well. I've started using Org some months ago (also the main reason for switching from VIM to Spacemacs after 15 years) and I love it.

While using your app I've noticed that the basic features are really implemented:
- refile
- schedules/deadlines
- syncing (synching is also amazing)

But I miss most a reasonable Org file editor. Yes, you can add headers and sub-headers (and the some content to each header) but the workflow is very slow especially when you want to quickly make notes. Instead of writing note after note (also including sub-notes) like you'd do in an editor, I have to first create the header first and *then* write. (see [Screenshot](https://photos.app.goo.gl/QPpRrs1ZYv7y58Pc7)) 

In Markor (a Markdown editing tool) write and then from the bottom you can apply the styling (especially the indentation buttons are quite useful when creating sub-notes). (see [Screenshot](https://photos.app.goo.gl/so9axSqRZwVtARR87)) 

The author of Markor is not willing to implement support for org mode, which I can understand. Would it be possible to add better editing features to orgzly? 

Thanks in advance and stay healthy! 

BR from Berlin/Germany, 
Victor

**Comment by nevenz** [comment]
I think this is #393?

**Comment by dorneanu** [comment]
Yes, that's true. Thanks for quick reply.
