### ISSUE TITLE
How can one donate to orgzly-android development?

### ISSUE THREAD

**Issue by carlduevel** [orgzly/orgzly-android#710]
I enjoy orgzly for some time now. Thanks @nevenz for your awesome work.
As this is not my area of expertise I at least want to contribute by sending
you a few bucks to support the development of this great app.
How can I do so?

**Comment by stites** [comment]
bump on this -- I am using fdroid (actually I'm using a downloaded CI apk) but would love to send some $$$ in the form of Github Sponsors/buymeacoffee/Patreon or whatever is in vogue these days.

**Comment by stites** [comment]
Was this just closed because of inactivity? I think I purchased an upgrade in the play store, but just use fdroid. That said orgzly is my daily driver and I would happily sponsor long-term.
