### ISSUE TITLE
Add CREATED property for a new note.

### ISSUE THREAD

**Issue by yqu212** [orgzly/orgzly-android#711]
- [x] I have searched for existing issues that may be the same as or related to mine.

It would be great to have the CREATED property for each new note.

**Comment by yqu212** [comment]
I notice an option  "Use property for created-at time". Is it what I want? @nevenz

**Comment by ajft** [comment]
@yqu212 yes, if you set that option it will go back through existing notes and add the CREATED property to existing notes, with the date & time of when they were created

**Comment by yqu212** [comment]
@ajft Thanks.
