### ISSUE TITLE
[Question] Sync doesn't work 

### ISSUE THREAD

**Issue by LinXueyuanStdio** [orgzly/orgzly-android#715]
- [x] I have searched for existing issues that may be the same as or related to mine.

Steps:
1. create a notebook
2. add a sync repo, webdav type, empty
3. add another sync repo, directory type, empty
4. click sync

Result:
will throw ONLY_BOOK_WITHOUT_LINK_AND_MULTIPLE_REPOS. But I would like to push my local notebook to two empty repos. How can I do that?
Besides, I don't know the meaning of field "linkRepo" in class BookNamesake, either.

**Comment by nevenz** [comment]
Syncing one notebook with two different repositories is not supported and there are no plans to do it. It would complicate things too much. Notebook can only have one link. That's what `linkRepo` is (I don't see it in `BookNamesake` though).

Multiple repositories are supported, but notebooks from different repositories sync to different notebooks in Orgzly.

**Comment by elig0n** [comment]
Please make a note of this in the app itself as it gives a false sense of being assured when having multiple repos and only one of them is actually synced...
