### ISSUE TITLE
header-args property is getting deleted

### ISSUE THREAD

**Issue by srgkoshelev** [orgzly/orgzly-android#726]
I have several headlines with `:header-args:` property set, including language specific, e.g. `:header-args:python:`.
It seems that Orgzly doesn't recognize them (which is _OK_) and deletes them (which is _not OK_) because if I open the file from my computer the calculations are messed up.

Could you please look into it?

Thank you!

**Comment by nevenz** [comment]
Can post the exact snippet of the header with properties in org format?

**Comment by srgkoshelev** [comment]
If I start with a document having `header-args`, e.g.:
```
* Test heading
:PROPERTIES:
:header-args:python:: :results output
:END:
```

Then get it to orgzly and open:
[Orgzly scheenshot](https://drive.google.com/file/d/1-NjzQMxLS_h9r0c98Cpk-3iQGxO_k-Ae/view?usp=sharing)
Notice the lack of property there. 

If I save the document and open it back in emacs, this happens:
```
* Test heading

```

The issue arises also with non language specific property, e.g. `:header-args: :session test`.

**Comment by nevenz** [comment]
Thanks. It seems that the used regex doesn't handle property names and/or values with `:` in them as it should.

**Comment by srgkoshelev** [comment]
Awesome, thank you!

Do you know when the updated version will be available on GPlay?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by nevenz** [comment]
> Do you know when the updated version will be available on GPlay?

I'll release the beta version today or tomorrow.
