### ISSUE TITLE
Larger expand/collapse tappable area

### ISSUE THREAD

**Issue by ethack** [orgzly/orgzly-android#727]
- [x] I have searched for existing issues that may be the same as or related to mine.

I have a hard time expanding/collapsing with the +/-. A lot of the time I will intend to expand or collapse a list (which I do frequently) but instead it will edit the note.

I'd like if the +/- could be bigger, or at least the tappable area that causes the expand/collapse to be bigger.

I've tried increasing the font size from default to large which helps. But I like the default size of all the other text better so I'd prefer if I could change only the +/-. 

I think the add item + at the bottom (screenshot below) is a good size and have no issues when pressing that. If the rest could be closer to that size or at least a similar tappable area it would help me a lot.

![Screenshot_20200615-215628](https://user-images.githubusercontent.com/1696711/84727202-2ae53700-af54-11ea-808d-3c8a0fffa466.png)

For reference, I'm on a Pixel 3 with Android 10.

Possibly related: https://github.com/orgzly/orgzly-android/issues/616

P.S. I am really liking the app. Open source code plus plaintext file format is an extremely attractive combination!

**Comment by nevenz** [comment]
It has been increased as much as the height of the item allows in e38d92b0507033dc79636b5b0563c5242bdab641.

![Screenshot_1593685105](https://user-images.githubusercontent.com/10671476/86347518-b0f4c380-bc5e-11ea-8378-f38001b1b6bb.png)

Hopefully that will help.  The only other way to make the area bigger is to introduce a new list density. Unless increasing the width only would make a difference.

**Comment by nevenz** [comment]
Please reopen if you're still having the same issue after v1.8.4.
