### ISSUE TITLE
Show tags in search list

### ISSUE THREAD

**Issue by psamim** [orgzly/orgzly-android#73]
Hi,

As a feature request, It would be helpful to display tags of each note, besides it, like in notebooks, when searching.

Thanks

**Comment by nevenz** [comment]
Tags in search results should already be displayed like in notebooks, unless I'm misunderstanding something?

(Displaying *inherited* tags need to be enabled in settings though.)

**Comment by psamim** [comment]
You are right. It was my mistake.

The mistake was because apparently tags are displayed besides notes' titles, while inherited tags in search lists are displayed below the note's title besides a folder icon. Sorry.

Thanks

**Comment by nevenz** [comment]
It should be all in one line (title, tags, inherited tags) -- perhaps line is wrapping if the title is longer, so it might look weird.

I'll be probably changing the layout at one point in the future, adding new setting to display a clean one-element-per-line kind of view.
