### ISSUE TITLE
Add the switch arrow in the widget so as to switch to the next searches.

### ISSUE THREAD

**Issue by xx299x** [orgzly/orgzly-android#731]
![image](https://user-images.githubusercontent.com/23482348/85886931-7da6d480-b819-11ea-9083-257614ab760e.png)

Through touch to the arrow, switch to the next searches.

**Comment by nevenz** [comment]
Does this rotates, or there's another button to the left?

But even adding just one button, space on the widget its quite limited, especially if using a narrower widget. And currently, a specific search is only two clicks away. So I'm not sure if this is worth it. Do you have only few saved searches?

**Comment by xx299x** [comment]
> Does this rotates, or there's another button to the left?
> 
> But even adding just one button, space on the widget its quite limited, especially if using a narrower widget. And currently, a specific search is only two clicks away. So I'm not sure if this is worth it. Do you have only few saved searches?

I indeed only have a few saved searches. I agree with you.
