### ISSUE TITLE
Give notebook a title that isn't the filename

### ISSUE THREAD

**Issue by logbaseaofn** [orgzly/orgzly-android#745]
- [x] I have searched for existing issues that may be the same as or related to mine.

What I expect:

- If I create a notebook from Orgzly:

    I am prompted with a field for a display name *and* a filename. I would like the file, when synced to use the filename, not the display name. 

- When syncing a repo:

    The notebook starts out with the name the same as the filename, but I can change it.

**Comment by ScottFreeCode** [comment]
For what it's worth by editing the "preamble" of a notebook anq entering a line `#+TITLE: {display name}` a display name can be configured that Orgzly can detect and use. (This is the Org format used by orgmode on Emacs.)

A UI for directly setting this, or for setting those kinds of preamble directives in general, would be nice though.

**Comment by logbaseaofn** [comment]
Perfect, that's exactly what I was looking for! I agree and UI for this sort of stuff would be preferred. I'll close this issue, but if someone wants to open a feature request for an addition to the UI, I'm sure that'd be valid.
