### ISSUE TITLE
import/backup configuration Orgzly App

### ISSUE THREAD

**Issue by romariorobby** [orgzly/orgzly-android#746]
that would be nice if it can export and import configuration setting of orgzly app. 

- I have searched for existing issues that may be the same as or related to mine.

**Comment by ScottFreeCode** [comment]
I believe there is an export settings button buried somewhere in the menus, though it just uses a default file name for the export so you have to go find it afterward rather than being able to pick a location when exporting.

**Comment by nevenz** [comment]
> I believe there is an export settings button buried somewhere in the menus, though it just uses a default file name for the export so you have to go find it afterward rather than being able to pick a location when exporting.

Maybe you're thinking about notebook export?

This is #156.
