### ISSUE TITLE
export settings

### ISSUE THREAD

**Issue by jarss** [orgzly/orgzly-android#752]
- I have searched for existing issues that may be the same as or related to mine.

It would be great if we could export our settings. The more complex (and great) the app becomes, the more features, the more important this is so we don't lose our setup.

**Comment by ScottFreeCode** [comment]
I believe there is an export settings button buried somewhere in the menus, though it just uses a default file name for the export so you have to go find it afterward rather than being able to pick a location when exporting.

**Comment by nevenz** [comment]
#746, #156.
