### ISSUE TITLE
Selecting multiple notebooks

### ISSUE THREAD

**Issue by contrapunctus-1** [orgzly/orgzly-android#755]
Orgzly v1.8.4 from F-Droid

1. I added a big folder with >50 Org files to Orgzly
2. I later realized I didn't really want those in Orgzly, so I want to remove them.

Removing the sync directory just left them all without a link, rather than removing them.

I expected to be able to select multiple files by long-pressing them, but seems like one can only select one at a time. Trying to delete them from the Orgzly main view requires long-press - overflow menu - delete, which is more work than I'd like to do for >50 files.

As a hacky workaround, I could clear the storage of Orgzly, but then I'd have to reconfigure it again.

My suggestions - any one of these will probably alleviate this situation -
* Add an option to remove files which don't have links.
* Allow multi-select for notebooks.
  + Useful additions are long-press-and-drag to select multiple sets of multiple files (see Simple File Manager), and a Select All action available during multi-select.
* Instead of storing this state as a private database, store it in the filesystem itself (e.g. each synced Org file represented by a symlink, or a text file of the same name, perhaps containing the path to the real file + other metadata), so other tools (e.g. a file manager which does have multi-select, drag-select, and select all, like SFM mentioned above) can be used to perform this and other operations missing in Orgzly. Probably the most powerful option (reduces the work of implementing duplicate features in each app, improves modularity and user choice), but it's not exactly fashionable. 😅

Thank you for your work on Orgzly.

**Comment by nevenz** [comment]
> Add an option to remove files which don't have links.

Perhaps this could be added when deleting a repository, but it's a bit risky, even with a confirmation.

> Instead of storing this state as a private database, store it in the filesystem itself

This would change tons of stuff, I don't think it's really an option.

> Allow multi-select for notebooks

There's #749, I'm going to close this one as a duplicate.
