### ISSUE TITLE
Notebook chooser (shortcut) - support user defined searches

### ISSUE THREAD

**Issue by lingnand** [orgzly/orgzly-android#770]
- I have searched for existing issues that may be the same as or related to mine.

So far we are able to drop shortcuts that point to a specific notebook, so that a single tap goes to it directly; it would be nice if we can extend this functionality to allow shortcut to *searches* too - so a single tap goes to a defined search view.

**Comment by ScottFreeCode** [comment]
Duplicate of #772?

(I know that one came first, but it has some reacts and this one doesn't as of this comment.)

**Comment by lingnand** [comment]
You are right, I'll close this

**Comment by bitclick** [comment]
yes this is a duplicate of #78
