### ISSUE TITLE
Offer a 1x1 widget/shortcut for saved searches

### ISSUE THREAD

**Issue by bitclick** [orgzly/orgzly-android#772]
Notebooks are accessible by 1x1 widgets/shortcuts. For saved searches only the bigger list-widget is available. This makes finding a specific search difficult with lots of searches. 

Please offer 1x1 shortcuts for searches like the existing shortcuts for Notebooks.

Yes, I have searched for existing issues that may be the same as or related to mine.

**Comment by nevenz** [comment]
It's #78.
