### ISSUE TITLE
Notifications aren't working sometimes

### ISSUE THREAD

**Issue by lytex** [orgzly/orgzly-android#783]
- [X] I have searched for existing issues that may be the same as or related to mine.
Related issues may be #593 and #606 

I started to notice that orgzly fails to remind me of some task, pretty randomly, and I haven't been able to spot any pattern. However that issue started to happen when the number/size of notes started to grow significantly, so it may be a problem of having a lot of org files.

I suggest stress tests could be added to narrow down the issue and see if its a matter of number/size of notes. See for example these tests by @nobiot:

* https://github.com/nobiot/10000-org-files-linked
* https://github.com/nobiot/10000-org-files
* these repos include folders with 100 as well as 10000 org files

**Comment by yqu212** [comment]
I have encountered the same issue. The reminder just can't work reliably.

**Comment by nevenz** [comment]
Does it happen for both daily reminders (no time part set) and times with the time part, or perhaps only one of those?

Also, what's the device and Android version used?

**Comment by yqu212** [comment]
I'm not sure which type the failed reminder is. What is reminder with time part? I use daily reminder, which is not reliable.

My phone is on MIUI 12.0.3.0 powered by Android 10.

**Comment by lytex** [comment]
As far as I'm aware, it has happened on both types of reminders, but I have only seen 1 out of 1 daily reminder not working, and time reminders sometimes work and sometimes don't.

I will gather more data on daily reminders

**Comment by lytex** [comment]
Daily notifications do work sometimes, so it seems it's not an issue of daily or time reminders only

**Comment by 809825706** [comment]
try to permit it running background？

**Comment by nevenz** [comment]
What's your device and Android version used @lytex? If anyone else has this issue, please specify the used device and Android version, so we can figure out if there's a pattern. There could be some battery optimization going on (and what @809825706 said).

Also to be clear (just in case) - reminders do not honor repeaters - they are displayed only on days that match the set time. This is different from what you see in the agenda's view.

Anyway, I'll replace Evernote's android-job library (which has been deprecated) with WorkManager, for start.

**Comment by nevenz** [comment]
> Anyway, I'll replace Evernote's android-job library (which has been deprecated) with WorkManager, for start.

Scratch that, WorkManager doesn't support scheduling jobs to run at the exact time. I'll add some debugging for the next version instead.

**Comment by lytex** [comment]
I'm using a Samsung A-50 with Android 10, but I manually disabled all battery optimizations since they were killing some apps in the background (see for example https://dontkillmyapp.com/samsung) and I think it works better but still has failed sometimes.

I was writing every reminder to check if it triggered a notification, which was a bit tedious. Are you creating some log like that when you say you'll add some debugging?

**Comment by nevenz** [comment]
> Are you creating some log like that when you say you'll add some debugging?

I was thinking a snackbar notification every time reminders are scheduled (as an option), but that still might be hard to debug.

There are already useful logs you could access with "adb logcat", but you'd need "adb" and USB connection for that. So perhaps a separate file could be created and exported someplace.

**Comment by zykov1** [comment]
Hello there!
Firstly I want to say a BIG THANKS to nevenz and other people behind Orgzly.
I think that your app is great! It is very flexible. I've just register on Github to appreciate your efforts.

Now to the issue: I haven't any notifications on my Asus Zenfone 3 Zoom ZE553KL (Android 8).
With the version 1.8.4 (comparing to 1.8) the bug gets worse:
before the notifications just came a hour or two later, now they couldn't made it for a whole day!
I tried every tip from dontkillmyapp.com/asus - it won't help :/
Notifications from some other apps don't work too.
I've noticed a pattern:
if an app have a custom notification screen that pops out (not just a standard notification) -
it almost always works. Maybe it's a way to go (as an option for "stubborn" devices like mine)?

This is the only bug that denies me from using Orgzly as the my main planner.
I hope it can be fixed soon.

**Comment by lytex** [comment]
Today I have used a lot less orgzly, and notifications would only be triggered when I open orgzly (1 hour later for example), despite having all battery optimizations disabled. 

At least, that would be a simpler requirement (send all notifications that were not previously notified even if they're late, instead of reliably sending all notifications at most X minutes late), since it seems from @zykov1 that notifications do not work consistently on android, regardless of battery optimizations.

Maybe as a workaround orgzly could access notifications and make a double check to see if notifications have been delivered to the user?

Just brainstorming here!

**Comment by lytex** [comment]
I have been using the latest version building from source and I'm not having these problems anymore. The bug seems pretty erratic and difficult to pin down exactly. Plus, it may be just a battery optimization issue.
