### ISSUE TITLE
FR: Allow specifying location of Orgzly database

### ISSUE THREAD

**Issue by Gitoffthelawn** [orgzly/orgzly-android#787]
I'm not seeing a place in the Settings to define where the Orgzly database is stored (local copy; not syncing).

Would it be possible to allow the user to specify where it should be stored (not referring to syncing)?

(BTW, where is it stored currently?)

**Comment by nevenz** [comment]
Database is in `/data/data/com.orgzly/databases/orgzly.db`.

> Would it be possible to allow the user to specify where it should be stored (not referring to syncing)

I don't think so, Android stores databases in `/data/data/package-name/databases/`.

Storing them outside of the app-specific directory would be a security risk.

What's the reason for wanting it stored elsewhere?

**Comment by Gitoffthelawn** [comment]
Thanks.

> What's the reason for wanting it stored elsewhere?

1. Access on non-rooted devices.  To my knowledge `/data/data/` is not accessible on non-rooted devices.
2. Privacy/security. Not accidentally leaving databases in storage that cannot be accessed (or even seen) via a file manager.
3. Storing the data in a single place that can be easily backed-up.

**Comment by nevenz** [comment]
> Access on non-rooted devices. To my knowledge /data/data/ is not accessible on non-rooted devices.

Right. it's for:

> Privacy/security. Not accidentally leaving databases in storage that cannot be accessed (or even seen) via a file manager.

> Storing the data in a single place that can be easily backed-up.

Perhaps you can check https://support.google.com/android/answer/2819582. As for app-level backup - syncing is the recommended way. And #156 will be for settings.

I'm closing this, as it's not possible to do it on Android, AFAIK.
