### ISSUE TITLE
How do I use a saved search?

### ISSUE THREAD

**Issue by maheshsundaram** [orgzly/orgzly-android#791]
- I have searched for existing issues that may be the same as or related to mine.

Reproduction steps:
1. Tap top left 3 bars menu icon
2. Select Searches
3. Tap on search item

Result:
Edit search item view

Expected:
View search results

How do I use a saved search to view the results? I have tried long pressing them (just selects) and also swiping them (edit mode).

Thank you, very excited about using Orgzly!

**Comment by VojtechStep** [comment]
The searches you define appear below the "Searches" item in the sidebar (see screenshot). When you click on these, they list the matching items. You can also use a widget on your home screen.

![Screenshot_20201209_212400_com.orgzly.png](https://user-images.githubusercontent.com/15523887/101629663-fdb8a380-3a21-11eb-9e8c-419efcb031df.png)

**Comment by maheshsundaram** [comment]
Oh I see! I am so silly 😬 Thank you!
