### ISSUE TITLE
Reschedule based on original schedule time, not done time

### ISSUE THREAD

**Issue by brandsimon** [orgzly/orgzly-android#794]
I have some tasks which I want to do e.g. every Monday, so I set the repeater to add one week, but sometimes I only get to do them on Tuesday, wednesday, ...
When I now hit the nice reschedule button in the notification or set the TODO to DONE on tuesday, the next schedule would be on tuesday (not my wanted monday).
Is there already a way to achieve what I want?

**Comment by 809825706** [comment]
look at [wiki](https://github.com/orgzly/documentation), you should set `+1w`, not `.+1w`. then, it will only reminder you on every Monday.

**Comment by brandsimon** [comment]
@809825706 
Thank you very much. I did not find it, but this is working!
