### ISSUE TITLE
Go to note location over anything

### ISSUE THREAD

**Issue by keithcrone** [orgzly/orgzly-android#81]
Right now, in Search and the Widget, clicking a note takes me directly to the note. What if I want to move it or add children or even siblings? I think the location context in an outline structure can be just as important. Going to a note's location gives me the option of doing anything I want in relation to it, including editing. 

Notifications don't go anywhere. [I promise it isn't a complaint. This is a great piece of software and you did label this an Alpha release. I'm just throwing the idea of maybe implementing the same method call in all three options to open a note's location]

We could even handle recurrence from the note's location.

**Comment by MackieLoeffel** [comment]
When you click on a note in the widget, you can use the back button to navigate to the note location, but this doesn't work in search.

**Comment by keithcrone** [comment]
That works on some initial search, but if I manipulate the notebook in some fashion, say close that branch and open another (or simply collapse all) subsequent events show the last state rather than the note.

**Comment by MackieLoeffel** [comment]
You are correct. I would think, that this is a bug, but it may also be working as intended. What do you think, @nevenz ? The problem is that the `BookFragment` is reused, if it already exists.

Notifications can use the same logic as the widget (open note and navigate to note's location by pressing the back button). I don't know about the search, because the backbutton should take you back to the search there. Another option would be to add a button in the note edit view, which takes you back to the note's location.

**Comment by keithcrone** [comment]
There is a button from Search to take you to the note's location which is great.

Even the note's location as a simple text reference on the note screen would be great.

**Comment by nevenz** [comment]
> Notifications don't go anywhere

Yeah, this is still to be implemented. Should be the same as for widget I guess.

> You are correct. I would think, that this is a bug, but it may also be working as intended

I'm not sure I understand what's the potential bug? Can someone give an example?

> Another option would be to add a button in the note edit view, which takes you back to the note's location
> Even the note's location as a simple text reference on the note screen would be great.

These both sound interesting.

Both can be achieved with a path to the note on the top of note's view, with clickable root (notebook), which would open the notebook positioned to the note. Even notes can be clickable and opened on click (which will be more useful in the future with narrowing implemented). Basically similar to what Workflowy does, except that Workflowy doesn't scroll to the note when "Home" is pressed.

**Comment by MackieLoeffel** [comment]
> I'm not sure I understand what's the potential bug? Can someone give an example?

The "bug" is, that if you press the back-button in the note screen after opening the note via the widget, the notebook view is not always positioned to the note, but only if the book view was created together with the note view.

> Both can be achieved with a path to the note on the top of note's view, with clickable root (notebook), which would open the notebook positioned to the note. Even notes can be clickable and opened on click (which will be more useful in the future with narrowing implemented). 

I like this idea and it means, that you would not have to use the back button from the note to get to its location.

**Comment by nevenz** [comment]
> The "bug" is, that if you press the back-button in the note screen after opening the note via the widget, the notebook view is not always positioned to the note, but only if the book view was created together with the note view.

Ah, yes, looks buggy. So instead of:

```
Log.w(TAG, "Fragment displaying book " + bookId + " already exists");
```

we want `scrollToNoteIfSet`, but making sure before that that the note is visible (`sparseTree`). (None of this tested, just looking at the code.)

**Comment by nevenz** [comment]
> The "bug" is, that if you press the back-button in the note screen after opening the note via the widget, the notebook view is not always positioned to the note, but only if the book view was created together with the note view.

This doesn't seem to be the case any more. In fact, note is even highlighted now, which might not be expected after simple back press, but it doesn't hurt.

> I like this idea and it means, that you would not have to use the back button from the note to get to its location.

Breadcrumbs were added in v1.7.7.
