### ISSUE TITLE
Can't search for absence of tag

### ISSUE THREAD

**Issue by mgraham** [orgzly/orgzly-android#811]
I am using version 1.8.4, and I have what seems like a very basic question.

I'm trying to figure out how to search for the absence of a tag using the NOT operator.

I can't find an example, so I'm assuming the syntax is: `(NOT t.tag1)`

Searching the built-in "Getting Started with Orgzly" notebook for `t.tag1` returns two items:
```
Note can have tags :tag1:tag2:
Sub-note inherits the tag :tag3:
```

Searching for `(NOT t.tag1)` returns the same results.

(I have searched for existing issues that may be the same as or related to mine.)

**Comment by JimBreton** [comment]
Does '.t.tag1' work?

I don't see the prefix period given as a supported example in the doc, but it seems to work if I try it.

**Comment by mgraham** [comment]
So `.` is the negation operator? Ah - I totally missed that - sorry.   Yes that works.  Thank you!
