### ISSUE TITLE
Deleted remote notebooks are restored

### ISSUE THREAD

**Issue by doak** [orgzly/orgzly-android#833]
- [x] I have searched for existing issues that may be the same as or related to mine.

From the [documentation](http://www.orgzly.com/help/#synchronization):
> Note that Orgzly doesn't yet detect deletion of remote notebooks. If you delete a notebook in the repository it will be restored after sync (unless you deleted it in the app as well). 

Although its documented, this should still be tracked as a bug imho.

**Comment by doak** [comment]
Just found a corresponding feature request #287. I am sorry, I had only searched for bug reports.

**Comment by MisterY** [comment]
Depends on your definition of a bug. Bugs usually indicate something that was implemented and is now broken. Why would it be a bug if it was never implemented?

**Comment by doak** [comment]
;)
My point of view which is one step further away: Sync with local file system is implemented. But it handles deletions wrong. Hence I would call it a bug rather than a missing feature.

**Comment by nevenz** [comment]
I'll close this one as a duplicate of #287.
