### ISSUE TITLE
Round corners for widget

### ISSUE THREAD

**Issue by kauesena** [orgzly/orgzly-android#842]
It would be nice to have the option to make the corners of the widget round. In my case, I have a Galaxy phone and most built-in widgets of the launcher have round corners.  The contrast of the Orgzly widget with the calendar widget bugs me a bit. Bellow there is a printscreen of while swiping sideways on the homescreen.

Thank you for such a nice app which allowed me to further organize my plain life in plain text!

![Screenshot_20210305-093830_One UI Home](https://user-images.githubusercontent.com/30255100/110116856-dfe7aa00-7d96-11eb-80d5-e017d7231f8b.jpg)

**Comment by cbkerr** [comment]
Hi @kauesena, I'd been searching for something widget-related and came across this.

I noticed that my orgzly widget on a Galaxy phone running Android 12 and One UI 4.1 has rounded corners. Is this issue still present for you?

**Comment by kauesena** [comment]
> Hi @kauesena, I'd been searching for something widget-related and came across this.
> 
> I noticed that my orgzly widget on a Galaxy phone running Android 12 and One UI 4.1 has rounded corners. Is this issue still present for you?

Oh, mine now has rounded corners too and fits very well with other widgets! I'll close the issue.
