### ISSUE TITLE
v1.8.5-beta.1 breaks .none / .no for notes without a property

### ISSUE THREAD

**Issue by SamHasler** [orgzly/orgzly-android#859]
I had a search that included `s.no` that no longer works after updating to v1.8.5-beta.1

Searching for just `s.no` finds no notes. I would expect it to find all unscheduled notes.

**Comment by Ypot** [comment]
True. This search doesn't work for me:
t.TAG it.todo (s.none OR s.le.today)

**Comment by nevenz** [comment]
Thanks, the issue was introduced in the code for #705.

Should `s.no` return inactive timestamps? I don't think so - a different value could be supported for that (`s.inactive` or whatever).

**Comment by Ypot** [comment]
Nope. Just tasks that have no schedule at all.

**Comment by Ypot** [comment]
Solved with the new update: 1.8.5-beta.2

**Comment by SamHasler** [comment]
Yes, all working now.

Many thanks.
