### ISSUE TITLE
Events are not listed in order by time in the agenda view

### ISSUE THREAD

**Issue by qaiviq** [orgzly/orgzly-android#868]
When scheduled notes show up in the agenda view, and by extension the agenda widget, the events are separated by date, but within each date the ordering does not match the time of the event. It seems they are ordered alphabetically by the name of the notebook they are in (all of the events in notebook `Apple` would come before those in notebook `Banana`), and after that by their position in the notebook, regardless of the scheduled time of each event.

**Comment by nevenz** [comment]
I think this is #298.
