### ISSUE TITLE
Could not find org-java-1.3-SNAPSHOT.jar

### ISSUE THREAD

**Issue by rafagalvez** [orgzly/orgzly-android#884]
- I have searched for existing issues that may be the same as or related to mine.
FAILURE: Build completed with 3 failures.

I can't run the test suite using vanilla Android Studio Arctic Fox 2020.3.1 Patch 2. The IDE cannot find org-java-1.3-SNAPSHOT.jar.

I manually looked for it at search.maven.com, and indeed [the latest public version in there is 1.2.3](https://search.maven.org/artifact/com.orgzly/org-java).

This is the error message from the log:

1: Task failed with an exception.

* What went wrong:
Execution failed for task ':app:checkFdroidDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:fdroidDebugRuntimeClasspath'.
   > Failed to transform org-java-1.3-SNAPSHOT.jar (com.orgzly:org-java:1.3-SNAPSHOT:20210903.112053-15) to match attributes {artifactType=enumerated-runtime-classes, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=integration, org.gradle.usage=java-runtime}.
      > Could not find org-java-1.3-SNAPSHOT.jar (com.orgzly:org-java:1.3-SNAPSHOT:20210903.112053-15).
        Searched in the following locations:
            https://oss.sonatype.org/content/repositories/snapshots/com/orgzly/org-java/1.3-SNAPSHOT/org-java-1.3-20210903.112053-15.jar

**Comment by stefan2904** [comment]
`com.orgzly.org-java-1.3-SNAPSHOT.jar` is available on https://oss.sonatype.org, but it looks like in the latest snapshot the .jar is missing:

![image](https://user-images.githubusercontent.com/527767/134223189-470f61ab-07b5-40c2-859b-67104d1fa6cd.png)

**Comment by nevenz** [comment]
Should be OK now, fixed in orgzly/org-java@b36a79c, thanks.
