### ISSUE TITLE
Can't sync to local directory

### ISSUE THREAD

**Issue by farzin-az** [orgzly/orgzly-android#885]
- I have searched for existing issues that may be the same as or related to mine.
android version: 6.0
orgzly version: 1.8.5
I want to make orgzly sync to a directory in my internal storage so that I can sync it via syncthing with my computer. When I go to sync/repositories/directory and click on browse it doesn't show anything from my system, neither internal storage nor SDcard. It is totally blank!
when I want to insert my directory address like this: /storage/emulated/0/orgzly it says that the directory URL is invalid.

**Comment by farzin-az** [comment]
I solved it myself!
After clicking browse, you should go to settings and toggle on the 'Display advanced devices' option. But I don't know why it wasn't toggled on by default and caused me lots of trouble to find it out the solution.

**Comment by nevenz** [comment]
Might be device-specific, I don't even see that option.
