### ISSUE TITLE
Orgzly does not support Digest Authentication

### ISSUE THREAD

**Issue by tfpk** [orgzly/orgzly-android#893]
This issue is referenced in #729 ; but I thought it might be useful to specify a seperate change. I'm not sure whether to class it as a "bug" or a "feature"...

Orgzly does not support Digest authentication (which is currently the recommended way to connect to a WebDAV server).

The workaround is to use `AuthType Basic`, but there's no documentation that reflects this.

The frontend shows a `"Login or password is invalid"` error.

The backend shows the following stack trace:

```
10-05 17:05:15.596 29374 29533 I System.out: Authenticating for response: Response{protocol=http/1.1, code=401, message=Unauthorized, url=[REDACTED]}
10-05 17:05:15.597 29374 29533 I System.out: Challenges: [Digest authParams={realm=org, nonce=[REDACTED], algorithm=MD5, qop=auth}]
10-05 17:05:15.758 29374 29533 W System.err: h.f.a.b.c: Error contacting https://[redacted] (401 Unauthorized)
10-05 17:05:15.758 29374 29533 W System.err:    at h.f.a.b.d.f.b(ValidatingResponseHandler.java:3)
10-05 17:05:15.758 29374 29533 W System.err:    at h.f.a.b.d.a.a(ExistsResponseHandler.java:4)
10-05 17:05:15.758 29374 29533 W System.err:    at h.f.a.b.d.a.a(ExistsResponseHandler.java:1)
10-05 17:05:15.758 29374 29533 W System.err:    at h.f.a.b.b.a(OkHttpSardine.java:56)
10-05 17:05:15.758 29374 29533 W System.err:    at h.f.a.b.b.c(OkHttpSardine.java:6)
10-05 17:05:15.758 29374 29533 W System.err:    at com.orgzly.android.q.r.a(WebdavRepo.kt:8)
10-05 17:05:15.758 29374 29533 W System.err:    at com.orgzly.android.ui.repo.webdav.b$b.run(WebdavRepoViewModel.kt:4)
10-05 17:05:15.758 29374 29533 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-05 17:05:15.758 29374 29533 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-05 17:05:15.758 29374 29533 W System.err:    at java.lang.Thread.run(Thread.java:923)

```

I'd be happy to PR in some better documentation somewhere if someone has a suggestion for where to put it. I don't have the bandwidth right now to PR a fix, but I might be able to look later.

**Comment by nevenz** [comment]
I'm not sure if the change will work, let me know if you can test the APK or the server you use is public. Thanks.

**Comment by tfpk** [comment]
Happy to test an APK; I'd prefer not to make my server public if possible :)

Is there a download link for an APK with this patch?

**Comment by nevenz** [comment]
There's a ZIP file generated on https://github.com/orgzly/orgzly-android/actions/workflows/android-build-master.yml.

Latest one being is https://github.com/orgzly/orgzly-android/suites/4370286417/artifacts/114939730. You can install `app/build/outputs/apk/premium/debug/app-premium-debug.apk` that's inside.
