### ISSUE TITLE
Repository - side notebook deletion

### ISSUE THREAD

**Issue by sokolgeo** [orgzly/orgzly-android#899]
x I have searched for existing issues that may be the same as or related to mine.

I use a number of .org files in a folder synced into Orgzly. Problem is: when I delete synced .org notebook file from the folder, Orgzly recreates it in the folder on next sync!

How could I delete from outside Orgzly a .org filed synced with Orgzly, without Orgzly re-creating it in the file system on next sync? 

Shall I only delete .org files in my folder from  Orgzly? This way Orgzly knows the .org file is to be deleted and does not re-creates it on next sync. This kind of kills the workflow when .org files are created, changed, _deleted_ outside of Orgzly and these deletions are correctly synced into Orgzly.

Is there a way to tell Orgzly to delete Notebook in Orgzly if linked .org file in folder repository is no longer exist? May be some simple Orgzly setting like "Delete notebook if source file is no longer available in repository" ?

Thank you

**Comment by nevenz** [comment]
Currently, you have to delete the notebook from Orgzly in any case. It's #287.

**Comment by danielkrajnik** [comment]
+1 has there been any progress on this?

Like sokolgeo said all benefits of Orgzly disappear when syncing doesn't work properly.

I need to move to a read-only viewer that uses .ics files instead until this gets fixed.
