### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by alphapapa** [orgzly/orgzly-android#9]
I want to thank you for writing Orgzly and making it free software.  I've been using Emacs and Org for several years now, and I have tried using the old MobileOrg implementation now and then, but it was always cumbersome, and now doesn't work with Dropbox's recent API changes.  Orgzly is just amazing, has a great UI, and seems to just work great!  I'm so happy that I can directly use my Dropbox-synced Org files on my phone now, with support for Org-mode features.  And now that it's free software, I can use it with confidence that it won't disappear someday, just like I know I can depend on Emacs.  Thanks for undertaking the Herculean effort to make this work on Android!

**Comment by nevenz** [comment]
YW, fixed. 😄
