### ISSUE TITLE
Parsing of comments

### ISSUE THREAD

**Issue by ottopichlhoefer** [orgzly/orgzly-android#90]
A line in org-mode I.e.
```org
# <2017-05-18 Do>-<2017-05-19 Fr>
```
is parsed in Orgzly as:
```org
# <2017-05-18 Do>-  
<2017-05-19 Fr>
```

**Comment by nevenz** [comment]
Where do you see this, in Orgzly itself? Not in the generated org file?

Perhaps it's just line wrapping?

I can make this happen if I turn on the displaying of content in search results and set notebook to be displayed left from the note. On the small device, there's just not enough space.

It shouldn't be comments-specific.

**Comment by ottopichlhoefer** [comment]
Yes you'r right. On turning the device sideways (making lines longer) the effect disappears.

Sorry for the noise.
