### ISSUE TITLE
Beginning A Search of Notes Inside Notebook Autofills Search Bar With Notebook Name

### ISSUE THREAD

**Issue by GithubContributor832** [orgzly/orgzly-android#912]
When searching for notes inside notebook the search bar automatically fills with b."notebook name" which is quite confusing. If the notebook name is Notes it appears b."Notes" in search bar before typing anything in. I have to clear and then search everytime. Notebook search does not do this.

**Comment by ShivanshGoel221B** [comment]
> When searching for notes inside notebook the search bar automatically fills with b."notebook name" which is quite confusing. If the notebook name is Notes it appears b."Notes" in search bar before typing anything in. I have to clear and then search everytime. Notebook search does not do this.

I looked into this and I believe it is the intended behavior and not a bug. The query is displayed in the search bar.
Hence, b."Notes" means that it needs to be searched inside the Notebook "Notes" only.
