### ISSUE TITLE
Preface doesn't show inline images nor monospace font

### ISSUE THREAD

**Issue by BioEssence** [orgzly/orgzly-android#927]
Hello,

org file preface behaves weirdly for me in Orgzly. I have enabled the display of prefaces by changing "Settings > Notes & Notebooks > Notebook's preface" from "Hide" to "Display".

The first issue is that images are not shown inline inside a preface even though I have them enabled by toggling on "Settings > Notes & Notebooks > Images > Enable images" and setting "/storage/emulated/0/Notes/" for "Settings > Notes & Notebooks > Note > Root for relative links (e.g. file:readme.txt)".

The second issue is that preface font is not monospaced even though I have it enabled by toggling on "Settings > Look & Feel > Monospaced font".

Mentioned issues can be seen in the following screenshot:
![screenshot](https://user-images.githubusercontent.com/11742251/160694578-a68c0413-adef-460e-a271-5bcd90446415.jpg)

The preface should show the inline image and it should have a monospaced font. This is not the case in the above screenshot.

Test files: [test.zip](https://github.com/orgzly/orgzly-android/files/8374565/test.zip).

I'm using Orgzly on Realme 6 phone which runs Android 11.

Thanks for the help.

**Comment by nevenz** [comment]
Thanks!
