### ISSUE TITLE
Backup/restore configuration

### ISSUE THREAD

**Issue by bkhl** [orgzly/orgzly-android#936]
Since I use the app on more than one phone, I've found myself needing to manually change a bunch of config to match my preferences. If I make some change, I tend to end up with mismatching config on different phones and getting disorientated.

It would have been handy if there was a way to dump/restore the application config to a file.

**Comment by romariorobby** [comment]
Yeah, i do the same. For now, i just backup search queries. but backup whole orgzly config would be helpful.

**Comment by xiaoruoruo** [comment]
I think this is dupe of #156
