### ISSUE TITLE
Refiling UI

### ISSUE THREAD

**Issue by dk87** [orgzly/orgzly-android#95]
Hi,

it would be great if we can move an item between notepads :smile:

Best
dk87

**Comment by nevenz** [comment]
You should already be able to cut the notes and paste them to a different notebook?

**Comment by dk87** [comment]
could it, however, be useful to provide an interface (e.g. drop-down menu) in the detail view of a note providing this?

**Comment by jonhind** [comment]
Yes please !!!

**Comment by Somantiq** [comment]
Currently I view the cut-and-paste as a dangerous operation. If I am interrupted in the middle, I lose the original note. This proposal would solve it. Or, maybe, make the "cut" operation tentative like in Excel - i.e. the original note is not removed unless pasted somewhere else. Just a thought.
