### ISSUE TITLE
F-Droid version is way behind (2017)

### ISSUE THREAD

**Issue by Zykino** [orgzly/orgzly-android#955]
- I have searched for existing issues that may be the same as or related to mine. Or maybe #574 which was opened in 2019...

I just found out that Orgzly did not stop development in 2017 but is still well alive. But [F-Droid most recent version](https://f-droid.org/packages/com.orgzly/) is 1.4.13 and has been published the 2017-04-17.

I don't know if the build are failing or what, but it seems like there is a broken link between github and F-Droid here.

**Comment by licaon-kter** [comment]
Did you read https://github.com/orgzly/orgzly-android/issues/5#issuecomment-1184484462 yet? Will be fixed when the next version is released

**Comment by rafagalvez** [comment]
Thank you @licaon-kter. By next version you mean next fdroidserver version, when https://gitlab.com/fdroid/fdroidserver/-/issues/1004 is closed?

**Comment by licaon-kter** [comment]
No, next app version, the one that does not use that library that depends on Google proprietary libs.

**Comment by Zykino** [comment]
Nop, I did not see the issue 5. I saw others but did not went as far as this one.
Thank you for already taking care of it :)

If you really want you may close the issue. I would have let it open until F-Droid version is published.

**Comment by MisterY** [comment]
It is published.

**Comment by nevenz** [comment]
Thanks all.
