### ISSUE TITLE
Syncing to local files is much slower after the app upgrade

### ISSUE THREAD

**Issue by decadent** [orgzly/orgzly-android#959]
- I have searched for existing issues that may be the same as or related to mine.

I got the version 1.8.7 from the Play Store after a long period with the previous one—not sure which, but before the redesign for Android 12. I'm using synchronization with files in a local directory, and in the new version it works much slower than previously. I have a habit of invoking the synchronization after I'm done with my changes or sometimes in between, so I'm used to waiting for it for a while—but I'm quite sure that it took a much shorter time before. Even when there are no changes either in notebooks or in files, synchronization takes fifty seconds now, whereas it was done in about ten-fifteen seconds before. Afaik unmodified notebooks were determined quickly before, and only saving or loading changed ones took time.

For the context, I have 46 top-level notebooks, and with my manner of notetaking there are over twenty thousands notes in total.

I have a vague suspicion that UI updates might factor in this problem, if synchronization doesn't work entirely in a separate thread—because the notebook list keeps flashing during the process, irregularly but mostly every second (and also making the alarm icon in the status bar flash for some reason). However, the list wasn't static in the previous version either. Alternatively, it feels like synchronization actually gathers notes from every Org file and compares to the in-app list, instead of going by the file modification time—since the sidebar progress bar indicates that time is spent on each notebook.

I'm using Android 11 on a Pixel 3a. I rebooted the device for good measure, which predictably didn't affect the issue.

**Comment by decadent** [comment]
As an aside: does any other method of synchronization work considerably faster than local files? At least in the case of many unmodified notebooks?

Local files are rather convenient in that Syncthing moves the files themselves to and from the desktop machine, so I can trigger the synchronization in Orgzly even when not on the network.

**Comment by nevenz** [comment]
Thanks, that was helpful.

> As an aside: does any other method of synchronization work considerably faster than local files? At least in the case of many unmodified notebooks?

It shouldn't.

**Comment by decadent** [comment]
By the way, are these ‘dynamic shortcuts’ something that's displayed on the home screen? Or is this for the Assistant? Because on the home screen I, personally, only have shortcuts to add a note and trigger synchronization—so unless this updating is needed for some possible functionality like the Assistant, there might be potential for optimization, by skipping the updating altogether if no ‘dynamic shortcuts’ are in use. Presuming, of course, that this information is available to the app.

Dunno if this would save much time now that the updating is in a separate thread.

**Comment by billwanjohi** [comment]
For others not sure how to acquire the (fixed) beta version while we wait for 1.8.8: https://github.com/orgzly/orgzly-android/issues/234#issuecomment-347024186
