### ISSUE TITLE
"Done" button (checkmark) sometimes missing when editing note

### ISSUE THREAD

**Issue by felixwiemuth** [orgzly/orgzly-android#991]
- I have searched for existing issues that may be the same as or related to mine.

When editing a note, there is usually a checkmark button in the top right to save the changes and exit the note view. Since v1.8.7 or v1.8.8, this button sometimes does not appear when editing a note. It reappears when clicking the "eye button", switching to viewing mode (and then it stays when switching back to editing mode).

This does not always happen, but rather often, somewhere between 20-60% of the cases. There is no invisible button either.

I observed it the first time after the new design was introduced. Maybe it is related to the fix of the graphics glitch, in v1.8.8?

I have set it to open notes in editing mode by default (if that is a setting).

OS: Android 13
Current app version (still has the bug): v1.8.9

**Comment by nevenz** [comment]
Removed edit/view mode in 6b1fb9d7, thanks.
