### ISSUE TITLE
Trigger sync from shell

### ISSUE THREAD

**Issue by doak** [orgzly/orgzly-android#999]
I was used to trigger sync by a Bash script (Termux) with `am startservice -n com.orgzly/com.orgzly.android.sync.SyncService`. It seems this service does not exist anymore since v1.8.9.

Is there another way to trigger the sync from a shell?

Background:
The script watches/waits for files changes (the org-files gets synced by `syncthing`) and triggers Orgzly to sync in case of an update.

**Comment by nevenz** [comment]
Use `com.orgzly.android.ActionReceiver` instead and send a broadcast. E.g.:

```
adb+ shell am broadcast -a com.orgzly.intent.action.SYNC_START com.orgzly/.android.ActionReceiver
```

**Comment by doak** [comment]
@nevenz, thanks a lot!
